// <auto-generated>
// The engine's BackgroundCubemapShader (BackgroundCubemapShader.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class BackgroundCubemapShader : BackgroundShader
{
    [Stage] public TextureCube Cubemap;


    // Shading of the sprite
    [Stage]
    public override float4 Shading()
    {
        var directionVector = new float3(1, 1 - 2 * streams.TexCoord.y, 1 - 2 * streams.TexCoord.x);
        return Intensity * Cubemap.Sample(LinearSampler, normalize(directionVector));
    }
}
