// <auto-generated>
// The engine's BrightFilterShader (BrightFilterShader.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
///   A bright filter shader:
///   Builds a soft bright-pass mask from pixel luminance, then keeps only the bright contribution.
///
///   `ThresholdOffset` shifts the point where pixels start contributing.
///   `BrightPassSteepness` makes the filter more selective by requiring stronger luminance to reach full contribution.
/// </summary>
[Shader(External = true, Internal = true)]
[System.Diagnostics.DebuggerNonUserCode]
public abstract partial class BrightFilterShader : ImageEffectShader
{
    [Stage, Color] public float3 ColorModulator;

    [Stage] public float BrightPassSteepness = 2.0f;
    [Stage] public float ThresholdOffset = 0.2f;

    [Stage]
    public override float4 Shading()
    {
        float3 color = Texture0.Sample(PointSampler, streams.TexCoord).rgb;

        // The result goes through a pyramid of half-float targets: an infinity or NaN there
        // becomes a black block the size of the mip it happened on.
        color = HalfPrecisionUtils.ClampToSafeRange(color);

        // Calculate relative luminance
        float luminance = LuminanceUtils.Luma(color);

        // method 1
        // Apply threshold
        // float middle = luminance - ThresholdOffset;
        // float range = 0.5f;
        // float value = smoothstep(0, 1, saturate(middle * range));
        // color *= value;

        // method 2
        // color *= luminance < ThresholdOffset ? 0.0f : 1.0f;

        // method 3
        color *= smoothstep(0, 1, saturate(sqrt(luminance) / (BrightPassSteepness + 1) - ThresholdOffset));

        return new float4(color * ColorModulator, 1.0f);
    }
}
