// <auto-generated>
// The engine's BufferToTextureColumns (BufferToTextureColumns.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Sean Boettger <sean@whypenguins.com>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(ComputeShaderBase), typeof(VoxelPositionStream), typeof(DataPacking))]
[Define("IndirectStoreMacro", If = "!defined(IndirectStoreMacro)")]
[Define("IndirectReadAndStoreMacro", If = "!defined(IndirectStoreMacro)")]
public abstract partial class BufferToTextureColumns : LocalSamples
{
    [Stage, Link("BufferToTexture.VoxelFragments")] public RWBuffer<uint> VoxelFragments;

    [Stage, Link("BufferToTexture.clipMapResolution")] public float3 clipMapResolution;

    [Stage, Link("BufferToTexture.storageUints")] public float storageUints;

    [Stage, Link("BufferToTexture.clipOffset")] public uint clipOffset;

    [Compose] public VoxelAttribute[] AttributesTemp;
    [Compose] public VoxelAttribute[] AttributesIndirect;

    [Override]
    public virtual void Compute()
    {
        int3 clipMapResolutionI = (int3)clipMapResolution;

        uint3 pos = streams.DispatchThreadId.xyz;
        uint clipIndex = streams.DispatchThreadId.y + clipOffset;

        pos.y = 0;
        streams.PositionVXPS = Sdsl.Implicit<int3>(pos);
        streams.VoxelVolumeSize = clipMapResolutionI;

        uint wStride = Sdsl.Implicit<uint>(clipMapResolutionI.x * clipMapResolutionI.y * clipMapResolutionI.z);
        uint VoxelFragmentsIndex = Sdsl.Implicit<uint>(clipIndex * wStride + pos.x + pos.y * clipMapResolutionI.x + pos.z * clipMapResolutionI.x * clipMapResolutionI.y);
        VoxelFragmentsIndex *= (uint)storageUints;

        uint yStride = Sdsl.Implicit<uint>(clipMapResolutionI.x * (uint)storageUints);
        uint initialVoxelFragmentsIndex = VoxelFragmentsIndex;

        foreach (var attr in AttributesTemp)
            attr.InitializeDummy();
        foreach (var attr in AttributesIndirect)
            attr.InitializeDummy();

        Sdsl.MacroStatement("IndirectStoreMacro");

        VoxelFragmentsIndex += Sdsl.Implicit<uint>((uint)storageUints * clipMapResolutionI.x);

        foreach (var attr in AttributesIndirect)
            attr.DirectWrite(streams.PositionVXPS, clipIndex, Sdsl.Implicit<uint>((int)clipMapResolutionI.y));

        streams.PositionVXPS.y++;
        for (int i = 0; streams.PositionVXPS.y < clipMapResolutionI.y - 1; streams.PositionVXPS.y++)
        {
            uint VoxelFragmentsIndexOld = VoxelFragmentsIndex;

            //See VoxelStorageClipmaps.cs Line #307
            Sdsl.MacroStatement("IndirectReadAndStoreMacro");

            foreach (var attr in AttributesIndirect)
                attr.DirectWrite(streams.PositionVXPS, clipIndex, Sdsl.Implicit<uint>((int)clipMapResolutionI.y));

            VoxelFragmentsIndex = Sdsl.Implicit<uint>(VoxelFragmentsIndexOld + (uint)storageUints * clipMapResolutionI.x);
        }
        foreach (var attr in AttributesTemp)
            attr.InitializeDummy();

        foreach (var attr in AttributesIndirect)
            attr.InitializeDummy();

        Sdsl.MacroStatement("IndirectStoreMacro");

        foreach (var attr in AttributesIndirect)
            attr.DirectWrite(streams.PositionVXPS, clipIndex, Sdsl.Implicit<uint>((int)clipMapResolutionI.y));
    }
}
