// <auto-generated>
// The declarations of the engine's BufferToTexture (BufferToTexture.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Sean Boettger <sean@whypenguins.com>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(ComputeShaderBase), typeof(VoxelPositionStream), typeof(DataPacking))]
[Define("IndirectStoreMacro", If = "!defined(IndirectStoreMacro)")]
[Define("IndirectReadAndStoreMacro", If = "!defined(IndirectStoreMacro)")]
public abstract partial class BufferToTexture : LocalSamples
{
    [Stage] public RWBuffer<uint> VoxelFragments;

    [Stage] public float3 clipMapResolution;

    [Stage] public float storageUints;

    [Stage] public uint clipOffset;

    [Compose] public VoxelAttribute[] AttributesTemp;
    [Compose] public VoxelAttribute[] AttributesIndirect;

    [Override]
    public virtual void Compute() => throw Gpu.Only;
}
