// <auto-generated>
// The declarations of the engine's ColorTransformShader (ColorTransformShader.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// A generic interface for processing/filtering a color.
/// </summary>
[Shader(External = true)]
public abstract partial class ColorTransformShader
{
    public virtual float4 Compute(float4 color) => throw Gpu.Only;
}
