// <auto-generated>
// The engine's ColorUtility (ColorUtility.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class ColorUtility
{
    // Converts an srgb color to linear space
    public virtual float ToLinear(float sRGB)
    {
        // http://chilliant.blogspot.jp/2012/08/srgb-approximations-for-hlsl.html
        return sRGB * (sRGB * (sRGB * 0.305306011f + 0.682171111f) + 0.012522878f);
    }


    // Converts an srgb color to linear space
    public virtual float3 ToLinear(float3 sRGB)
    {
        return sRGB * (sRGB * (sRGB * 0.305306011f + 0.682171111f) + 0.012522878f);
    }


    // Converts an srgb color to linear space
    public virtual float4 ToLinear(float4 sRGBa)
    {
        float3 sRGB = sRGBa.rgb;
        return new float4(sRGB * (sRGB * (sRGB * 0.305306011f + 0.682171111f) + 0.012522878f), sRGBa.a);
    }


    // simple screen gamma conversion
    public virtual float4 GammaToLinear(float4 RGBa, float Gamma = 2.2f)
    {
        RGBa.rgb = pow(RGBa.rgb, 1.0f / Gamma);
        return RGBa;
    }

    public virtual float4 LinearToGamma(float4 RGBa, float Gamma = 2.2f)
    {
        RGBa.rgb = pow(RGBa.rgb, Gamma);
        return RGBa;
    }


    //https://chilliant.blogspot.com/2012/08/srgb-approximations-for-hlsl.html
    // Converts an sRGB color to linear space
    public virtual float4 SRgbToLinear(float4 sRGBa)
    {
        float3 sRGB = sRGBa.rgb;
        return new float4(sRGB * (sRGB * (sRGB * 0.305306011f + 0.682171111f) + 0.012522878f), sRGBa.a);
    }


    // Converts an linear color to sRGB space
    public virtual float4 LinearToSRgb(float4 RGBa)
    {
        float3 RGB = RGBa.rgb;

        float3 S1 = sqrt(RGB);
        float3 S2 = sqrt(S1);
        float3 S3 = sqrt(S2);

        return new float4(0.662002687f * S1 + 0.684122060f * S2 - 0.323583601f * S3 - 0.0225411470f * RGB, RGBa.a);
    }


    //https://github.com/vvvv/VL.Stride/pull/395#issuecomment-760253956
    // Converts a color from linear to sRGB
    public virtual float4 LinearToSRgbPrecise(float4 RGBa)
    {
        float3 rgb = RGBa.rgb;
        float3 higher = 1.055f * pow(rgb, 1.0f / 2.4f) - 0.055f;
        float3 lower = rgb * 12.92f;

        float3 cutoff = step(rgb, 0.0031308f);
        RGBa.rgb = lerp(higher, lower, cutoff);
        return RGBa;
    }


    // Converts a color from sRGB to linear
    public virtual float4 SRgbToLinearPrecise(float4 sRGBa)
    {
        float3 srgb = sRGBa.rgb;
        float3 higher = pow((srgb + 0.055f) / 1.055f, 2.4f);
        float3 lower = srgb / 12.92f;

        float3 cutoff = step(srgb, 0.04045f);
        sRGBa.rgb = lerp(higher, lower, cutoff);
        return sRGBa;
    }
}
