// <auto-generated>
// The declarations of the engine's ColorUtility (ColorUtility.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class ColorUtility
{
    // Converts an srgb color to linear space
    public virtual float ToLinear(float sRGB) => throw Gpu.Only;


    // Converts an srgb color to linear space
    public virtual float3 ToLinear(float3 sRGB) => throw Gpu.Only;


    // Converts an srgb color to linear space
    public virtual float4 ToLinear(float4 sRGBa) => throw Gpu.Only;


    // simple screen gamma conversion
    public virtual float4 GammaToLinear(float4 RGBa, float Gamma = 2.2f) => throw Gpu.Only;

    public virtual float4 LinearToGamma(float4 RGBa, float Gamma = 2.2f) => throw Gpu.Only;


    //https://chilliant.blogspot.com/2012/08/srgb-approximations-for-hlsl.html
    // Converts an sRGB color to linear space
    public virtual float4 SRgbToLinear(float4 sRGBa) => throw Gpu.Only;


    // Converts an linear color to sRGB space
    public virtual float4 LinearToSRgb(float4 RGBa) => throw Gpu.Only;


    //https://github.com/vvvv/VL.Stride/pull/395#issuecomment-760253956
    // Converts a color from linear to sRGB
    public virtual float4 LinearToSRgbPrecise(float4 RGBa) => throw Gpu.Only;


    // Converts a color from sRGB to linear
    public virtual float4 SRgbToLinearPrecise(float4 sRGBa) => throw Gpu.Only;
}
