// <auto-generated>
// The declarations of the engine's CombineLevelsFromCoCShader (CombineLevelsFromCoCShader.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

// Define to visualize debug colors for the different CoC levels.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// This takes in entry several blurred levels, and depending on the pixel CoC,
/// the final color will be an interpolation between 2 of these levels.
/// Level 0 is the original sharp image. The last level is the blurriest version.
/// Expects as input:
/// - Texture0: a [CoC, Linear Depth] buffer
/// - Texture1 ~ TextureX: the different blur levels. (0 == no blur)
/// </summary>
///
/// <typeparam name="TLevelCount">Total number of layers used, including the original non-blurred image.</typeparam>
[Shader(External = true)]
[Define("DEBUG_COC_LEVEL_COLOR", "0")]
public abstract partial class CombineLevelsFromCoCShader : ImageEffectShader
{
    [Generic] public static int TLevelCount;
    // The CoC corresponding to each level of blur
    [Stage, Size("TLevelCount")] public float[] CoCLevelValues;

    [Stage]
    public override float4 Shading() => throw Gpu.Only;
}
