// <auto-generated>
// The engine's ComputeColorLighten3ds (ComputeColorLighten3ds.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
public abstract partial class ComputeColorLighten3ds : ComputeColor
{
    [Compose] public ComputeColor color1;
    [Compose] public ComputeColor color2;

    public override float4 Compute()
    {
        float4 backColor = color1.Compute();
        float4 frontColor = color2.Compute();


        // From http://msdn.microsoft.com/en-us/library/windows/desktop/hh706313(v=vs.85).aspx
        //
        //  b = background, f = foreground, c = color, a = alpha, r = result color obtained with the specific blend formula
        //
        //  Lighten:
        //      color = max((1 - fa) * ba * bc + (fa * fc), (1 - ba) * fa * fc + (ba * bc))
        //      alpha = fa * (1-ba) + ba
        return new float4(max(lerp(backColor.a * backColor.rgb, frontColor.rgb, frontColor.a), lerp(frontColor.a * frontColor.rgb, backColor.rgb, backColor.a)), Sdsl.Static<BlendUtils>().BasicAlphaBlend(backColor.a, frontColor.a));
    }
}
