// <auto-generated>
// The engine's ComputeColorConstantColorLink (ComputeColorConstantColorLink.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Returns the color behind the key passed as generic.
/// </summary>
/// <remarks>
/// LinkName: generic LinkType - the name of the key used to set the color.
/// </remarks>
[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
public abstract partial class ComputeColorConstantColorLink : ComputeColor
{
    [Generic] public static LinkType LinkName;
    [CBuffer("PerMaterial"), Stage, Color, Link("LinkName")] public float4 constantColor;

    public override float4 Compute()
    {
        return constantColor;
    }
}
