// <auto-generated>
// The declarations of the engine's ComputeColorTextureRepeat (ComputeColorTextureRepeat.sdsl, Stride 4.4.0-beta7), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Samples a repeated texture with default sampler. Default sampler should be on repeat for this shader to behave correctly.
/// </summary>
/// <remarks>
/// TTexture: generic Texture2D - the texture to sample.
/// TStream: generic Semantic - the texcoord index semantic used to sample the texture.
/// TFactor: generic float - the repeat factor.
/// </remarks>
[Shader(External = true)]
public abstract partial class ComputeColorTextureRepeat : ComputeColor
{
    [Generic] public static Texture2D TTexture;
    [Generic] public static Semantic TStream;
    [Generic] public static float TFactor;
    [Stage, Stream("TStream")] public float2 TexCoord;

    public override float4 Compute() => throw Gpu.Only;
}
