// <auto-generated>
// The engine's ComputeColorTextureScaledOffsetDynamicSamplerRandomUV (ComputeColorTextureScaledOffsetDynamicSamplerRandomUV.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Samples a texture with a custom sampler and fix texture coordinates offset and scale.
/// </summary>
/// <remarks>
/// TTexture: generic Texture2D - the texture to sample.
/// TStream: generic Semantic - the texcoord index semantic used to sample the texture.
/// TScale: generic LinkType - the float2 key for scaling factor of the texture coordinates.
/// TOffset: generic LinkType - the float2 key for texture coordinates offset.
/// TSampler: generic SamplerState - the custom sampler.
/// </remarks>
[Shader(External = true)]
[Mixin(typeof(DynamicTexture), Generics = "TTextureName, PerMaterial")]
[Mixin(typeof(DynamicSampler), Generics = "TSampler, PerMaterial")]
[Mixin(typeof(DynamicTextureStream), Generics = "TStream")]
public abstract partial class ComputeColorTextureScaledOffsetDynamicSamplerRandomUV : ComputeColor
{
    [Generic] public static LinkType TTextureName;
    [Generic] public static Semantic TStream;
    [Generic] public static LinkType TSampler;
    [Generic] public static MemberName TRgba;
    [Generic] public static LinkType TScale;
    [Generic] public static LinkType TOffset;
    [CBuffer("PerMaterial"), Stage, Link("TScale")] public float2 scale;

    [CBuffer("PerMaterial"), Stage, Link("TOffset")] public float2 offset;


    //------------------------------------------------------------------------------
    // Gererate pseudorandom number
    //------------------------------------------------------------------------------
    public virtual float Random(in float2 uv)
    {
        float2 noise = (frac(sin(dot(uv, new float2(12.9898f, 78.233f) * 2.0f)) * 43758.5453f));
        return abs(noise.x + noise.y) * 0.5f;
    }


    //------------------------------------------------------------------------------
    // Gererate texture coordinates for random placement
    //------------------------------------------------------------------------------
    public virtual float2 RandomUV(in float2 uv)
    {
        const uint NUM_PATTERNS = 2 * 2 * 4 * 4 * 4;

        uint pattern = (uint)(Random(floor(uv)) * (float)NUM_PATTERNS) % NUM_PATTERNS;
        float2 result = frac(uv);

        // flip
        if ((uint)(pattern % 2) != 0)
        {
            result.x = 1.0f - result.x;
        }
        pattern /= 2;
        if ((uint)(pattern % 2) != 0)
        {
            result.y = 1.0f - result.y;
        }

        // rotate
        pattern /= 2;
        if (pattern % 4 == 1)
        {
            result = new float2(result.y, 1.0f - result.x);
        }
        else if (pattern % 4 == 2)
        {
            result = new float2(1.0f - result.y, result.x);
        }
        else if (pattern % 4 == 3)
        {
            result = 1.0f - result;
        }

        // offset
        pattern /= 4;
        result.x += (pattern % 4) * 0.25f;
        pattern /= 4;
        result.y += (pattern % 4) * 0.25f;

        return result;
    }

    public override float4 Compute()
    {
        return Sdsl.Member(Texture.Sample(Sampler, RandomUV(streams.TexCoord * scale + offset)), TRgba);
    }
}
