// <auto-generated>
// The engine's ComputeColorTextureScaledOffsetDynamicSampler (ComputeColorTextureScaledOffsetDynamicSampler.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Samples a texture with a custom sampler and fix texture coordinates offset and scale.
/// </summary>
/// <remarks>
/// TTexture: generic Texture2D - the texture to sample.
/// TStream: generic Semantic - the texcoord index semantic used to sample the texture.
/// TScale: generic LinkType - the float2 key for scaling factor of the texture coordinates.
/// TOffset: generic LinkType - the float2 key for texture coordinates offset.
/// TSampler: generic SamplerState - the custom sampler.
/// </remarks>
[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
[Mixin(typeof(DynamicTexture), Generics = "TTextureName, PerMaterial")]
[Mixin(typeof(DynamicSampler), Generics = "TSampler, PerMaterial")]
[Mixin(typeof(DynamicTextureStream), Generics = "TStream")]
public abstract partial class ComputeColorTextureScaledOffsetDynamicSampler : ComputeColor
{
    [Generic] public static LinkType TTextureName;
    [Generic] public static Semantic TStream;
    [Generic] public static LinkType TSampler;
    [Generic] public static MemberName TRgba;
    [Generic] public static LinkType TScale;
    [Generic] public static LinkType TOffset;
    [CBuffer("PerMaterial"), Stage, Link("TScale")] public float2 scale;

    [CBuffer("PerMaterial"), Stage, Link("TOffset")] public float2 offset;

    public override float4 Compute()
    {
        return Sdsl.Member(Texture.Sample(Sampler, streams.TexCoord * scale + offset), TRgba);
    }
}
