// <auto-generated>
// The declarations of the engine's ComputeColorWhite (ComputeColorWhite.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class ComputeColorWhite : ComputeColor
{
    public override float4 Compute() => throw Gpu.Only;
}
