// <auto-generated>
// The engine's ComputeColorScaler (ComputeColorScaler.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class ComputeColorScaler : ComputeColor
{
    [Generic] public static float TScaleValue;

    public override float4 Compute()
    {
        float4 baseColor = base.Compute();
        // TODO Check where to put gamma correction? => float tempScaleValue = pow(TScaleValue, 2.2)
        // USe faster 2.0 instead of 2.2
        return new float4(baseColor.xyz * TScaleValue * TScaleValue, baseColor.w);
    }
}
