// <auto-generated>
// The declarations of the engine's ComputeColorTextureScaledOffset (ComputeColorTextureScaledOffset.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Samples a texture with the default sampler and fix texture coordinates offset and scale.
/// </summary>
/// <remarks>
/// TTexture: generic Texture2D - the texture to sample.
/// TStream: generic Semantic - the texcoord index semantic used to sample the texture.
/// TScale: generic float2 - the scaling factor of the texture coordinates.
/// TOffset: generic float2 - the texture coordinates offset.
/// </remarks>
[Shader(External = true)]
public abstract partial class ComputeColorTextureScaledOffset : ComputeColor
{
    [Generic] public static Texture2D TTexture;
    [Generic] public static Semantic TStream;
    [Generic] public static float2 TScale;
    [Generic] public static float2 TOffset;
    [Stream("TStream")] public float2 TexCoord;

    public override float4 Compute() => throw Gpu.Only;
}
