// <auto-generated>
// The engine's DynamicTextureCube (DynamicTextureCube.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Defines a Texture2D.
/// </summary>
/// <remarks>
/// TEXTURE_KEY: generic LinkType - the name of the ParameterKey that will link to this texture.
/// </remarks>
[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
public abstract partial class DynamicTextureCube
{
    [Generic] public static LinkType TTexture;
    [Generic] public static MemberName LocalResourceGroup;
    [RGroup("LocalResourceGroup"), Stage, Link("TTexture")] public TextureCube CubeMap;
}
