// <auto-generated>
// The declarations of the engine's FilmGrainShader (FilmGrainShader.sdsl, Stride 4.4.0-beta7), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Film-grain shader.
/// Adapted from the shader of Martins Upitis.
/// http://devlog-martinsh.blogspot.ca/2013/05/image-imperfections-and-film-grain-post.html
/// </summary>
[Shader(External = true, Internal = true)]
[Mixin(typeof(Texturing))]
public abstract partial class FilmGrainShader : ColorTransformShader
{
    // Amount
    public float Amount;

    // Time changing at each frame for the animation
    public float Time;

    // Size of the grain
    public float GrainSize;

    // How the luminance influences the amount of grain.
    public float LuminanceFactor;

    public override float4 Compute(float4 color) => throw Gpu.Only;


    // Random texture generation
    public virtual float4 rnm(float2 tc) => throw Gpu.Only;

    public virtual float fade(float t) => throw Gpu.Only;

    public virtual float pnoise3D(float3 p) => throw Gpu.Only;

    public virtual float2 coordRot(float2 tc, float angle) => throw Gpu.Only;
}
