// <auto-generated>
// The declarations of the engine's FogEffect (FogEffect.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Simple fog
/// </summary>
[Shader(External = true, Internal = true)]
public abstract partial class FogEffect : ImageEffectShader
{
    [Stage] public float FogStart;
    [Stage] public float Density;
    [Stage] public float zFar;
    [Stage] public float zNear;
    [Stage] public bool skipBG;

    [Stage, Color] public float3 FogColor;
    [Stage] public Texture2D DepthTexture;

    [Stage]
    public override float4 Shading() => throw Gpu.Only;
}
