// <auto-generated>
// The engine's GBufferOutputNormals (GBufferOutputNormals.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Outputs material world space normal vectors (packed from [-1;-1] to [0;1] to fit smaller render targets)
/// </summary>
[Shader(External = true)]
[Mixin(typeof(MaterialPixelShadingStream), typeof(NormalPack))]
public abstract partial class GBufferOutputNormals : ComputeColor
{
    public override float4 Compute()
    {
        return new float4(EncodeNormal(streams.normalWS), 1);
    }
}
