// <auto-generated>
// The declarations of the engine's HalfPrecisionUtils (HalfPrecisionUtils.sdsl, Stride 4.4.0-beta7), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Helpers for values that end up in half-float render targets.
/// </summary>
[Shader(External = true)]
public abstract partial class HalfPrecisionUtils
{
    /// <summary>
    /// Half the half-float maximum (65504), leaving headroom for the blurs and sums that follow.
    /// </summary>
    public const float MaxSafeValue = 32000.0f;


    /// <summary>
    /// Clamps a color to [0, MaxSafeValue]; a NaN becomes 0.
    /// </summary>
    public static float3 ClampToSafeRange(float3 color) => throw Gpu.Only;
}
