// <auto-generated>
// The engine's Hammersley (Hammersley.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Hammersley sampling on a Plane, Sphere, etc...
/// </summary>
[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
public abstract partial class Hammersley : Math
{
    public virtual float2 GetSamplePlane(int k, int samplesCount)
    {
        var u = 0.0f;
        var p = 0.5f;
        for (int kk = k; kk > 0; p *= 0.5f, kk >>= 1)
        {
            if (Sdsl.Implicit<bool>(kk & 1))
                // kk mod 2 == 1
                u += p;
        }

        var v = (k + 0.5f) / samplesCount;

        return new float2(u, v);
    }
}
