// <auto-generated>
// The engine's LambertianPrefilteringSHNoComputePass1 (LambertianPrefilteringSHNoComputePass1.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// The first pass of a shader performing Lambertian pre-filtering using Spherical Harmonics
/// </summary>
[Shader(External = true, BaseGenerics = "THarmonicsOrder")]
[Mixin(typeof(ImageEffectShader), typeof(Texturing))]
public abstract partial class LambertianPrefilteringSHNoComputePass1 : SphericalHarmonicsBase
{
    [Generic] public static int THarmonicsOrder;
    // the input texture containing the radiance
    public TextureCube RadianceMap;

    // Index of the spherical harmonics coefficient to compute
    public int CoefficientIndex;

    // The Cosine kernel factors
    public const float A0 = 1.0f;
    public const float A1 = 2.0f / 3.0f;
    public const float A2 = 1.0f / 4.0f;
    public const float A3 = 0.0f;
    public const float A4 = -1.0f / 24.0f;
    [Size("5 * 5")] public static readonly float[] A = new float[5 * 5] { A0, A1, A1, A1, A2, A2, A2, A2, A2, A3, A3, A3, A3, A3, A3, A3, A4, A4, A4, A4, A4, A4, A4, A4, A4 };

    [Override, Stage]
    public virtual float4 Shading()
    {
        float3 result = 0;

        float2 uv = streams.TexCoord * 2.0f - 1.0f;

        // Calculate weight
        float dist = 1.0f + dot(uv, uv);
        float weight = 4.0f / (sqrt(dist) * dist);

        Unroll();
        for (int faceIndex = 0; faceIndex < 6; faceIndex++)
        {
            // Extract direction from texel u, v
            float3 dirVS = normalize(uvToDirectionVS(uv.x, uv.y, faceIndex));

            // Calculates the values of the SH bases
            EvaluateSHBases(dirVS);

            float3 radiance = RadianceMap.Sample(PointSampler, dirVS).xyz;

            result += A[CoefficientIndex] * streams.SHBaseValues[CoefficientIndex] * radiance * weight;
        }

        return new float4(result, weight * 6);
    }

    public virtual float3 uvToDirectionVS(float u, float v, int viewIndex)
    {
        if (viewIndex == 0)
            return new float3(1, -v, -u);
        // face X
        if (viewIndex == 1)
            return new float3(-1, -v, u);
        // face -X
        if (viewIndex == 2)
            return new float3(u, 1, v);
        // face Y
        if (viewIndex == 3)
            return new float3(u, -1, -v);
        // face -Y
        if (viewIndex == 4)
            return new float3(u, -v, 1);
        // face Z
        if (viewIndex == 5)
            return new float3(-u, -v, -1);

        // face -Z
        return 0;
    }
}
