// <auto-generated>
// The declarations of the engine's LightConstantWhite (LightConstantWhite.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Defines a white environment light
/// </summary>
[Shader(External = true)]
[Mixin(typeof(LightStream))]
public abstract partial class LightConstantWhite : EnvironmentLight
{
    public override void PrepareEnvironmentLight() => throw Gpu.Only;
}
