// <auto-generated>
// The declarations of the engine's LightPointGroup (LightPointGroup.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Defines a group of point lights
/// </summary>
[Shader(External = true)]
[Mixin(typeof(LightPoint))]
public abstract partial class LightPointGroup : DirectLightGroupPerDraw
{
    [Generic] public static int TMaxLightCount;
    [CBuffer("PerDraw.Lighting"), Size("TMaxLightCount")] public LightPoint.PointLightData[] Lights;

    public override int GetMaxLightCount() => throw Gpu.Only;


    /// <summary>
    /// Compute the light color/direction for the specified index within this group
    /// </summary>
    public override void PrepareDirectLightCore(int lightIndex) => throw Gpu.Only;

    public override float ComputeAttenuation(float3 position, int lightIndex) => throw Gpu.Only;
}
