// <auto-generated>
// The declarations of the engine's LightClustered (LightClustered.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(ShaderBaseStream), typeof(Camera))]
public abstract partial class LightClustered : ScreenPositionBase
{
    [Stage, Stream] public uint2 lightData;
    [Stage, Stream] public int lightIndex;
    [RGroup("PerView.Lighting"), Stage] public Texture3D<uint2> LightClusters;
    [RGroup("PerView.Lighting"), Stage] public Buffer<uint> LightIndices;
    [CBuffer("PerView.Lighting"), Stage] public float ClusterDepthScale;
    [CBuffer("PerView.Lighting"), Stage] public float ClusterDepthBias;
    [CBuffer("PerView.Lighting"), Stage] public float2 ClusterStride;

    public virtual void PrepareLightData() => throw Gpu.Only;
}
