// <auto-generated>
// The declarations of the engine's LightSpotAttenuationDefault (LightSpotAttenuationDefault.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Code for attenuating a group of spotlights using angular attenuation.
/// </summary>
[Shader(External = true)]
public abstract partial class LightSpotAttenuationDefault : LightUtil
{
    //override float ComputeAttenuation(SpotLightDataInternal light, float3 position, inout float3 lightVectorNorm)
    public virtual float ComputeAttenuation(float3 PositionWS, float3 AngleOffsetAndInvSquareRadius, float3 DirectionWS, float3 position, ref float3 lightVectorNorm) => throw Gpu.Only;
}
