// <auto-generated>
// The declarations of the engine's LuminanceUtils (LuminanceUtils.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// A utility shader for luminance.
/// </summary>
[Shader(External = true)]
public abstract partial class LuminanceUtils
{
    /// <summary>
    /// Calculate the perceptive luminance (601Y')
    /// </summary>
    /// <remarks>
    /// http://en.wikipedia.org/wiki/HSL_and_HSV#Lightness
    /// http://www.poynton.com/PDFs/YUV_and_luminance_harmful.pdf
    /// </remarks>
    public static float Luma(float3 color) => throw Gpu.Only;
}
