// <auto-generated>
// The engine's MaterialSurfaceGlossinessMapMetalFlakes (MaterialSurfaceGlossinessMapMetalFlakes.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Material glossiness map (for a metal flakes layer)
/// </summary>
[Shader(External = true, BaseGenerics = "TInvert")]
[System.Diagnostics.DebuggerNonUserCode]
[Mixin(typeof(Transformation), typeof(PositionStream4))]
public abstract partial class MaterialSurfaceGlossinessMapMetalFlakes : MaterialSurfaceGlossinessMap
{
    [Generic] public static bool TInvert;
    [Compose] public ComputeColor surfaceToEyeDistanceFactor;

    public override void Compute()
    {
        var metalFlakesGlossiness = streams.matGlossiness;

        // Compute base glossiness
        base.Compute();

        var distanceFactor = surfaceToEyeDistanceFactor.Compute().r;

        // Correct both glossiness factor (to avoid aliasing and unrealistic values)
        float normalLength = length(streams.matNormal);
        //streams.matGlossiness =  normalLength * streams.matGlossiness / (normalLength + streams.matGlossiness * (1.0f - normalLength));
        metalFlakesGlossiness = normalLength * metalFlakesGlossiness / (normalLength + metalFlakesGlossiness * (1.0f - normalLength));

        // Interpolate the factors using the surface to camera distance
        float LOD = saturate(distance(Eye.xyz, streams.PositionWS.xyz) * distanceFactor);

        streams.matGlossiness = lerp(metalFlakesGlossiness, streams.matGlossiness, LOD);
    }
}
