// <auto-generated>
// The engine's MaterialSurfaceNormalStreamShading (MaterialSurfaceNormalStreamShading.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.
// Temporary code for testing IMaterialSurface

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(NormalStream))]
public abstract partial class MaterialSurfaceNormalStreamShading : ShadingBase
{
    [Stage]
    public override float4 Shading()
    {
        // Run surface shading but don't take the result
        base.Shading();
        return new float4(streams.normalWS * 0.5f + 0.5f, 1.0f);
    }
}
