// <auto-generated>
// The engine's MaterialSurfaceShadingSpecularHair (MaterialSurfaceShadingSpecularHair.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Performs hair shading.
/// </summary>
[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
[Mixin(typeof(MaterialPixelShadingStream), typeof(MaterialHairShared), typeof(NormalStream), typeof(Transformation), typeof(MaterialPixelStream))]
public abstract partial class MaterialSurfaceShadingSpecularHair : IMaterialSurfaceShading
{
    [Generic] public static int ShadingModel;
    [Generic] public static bool DebugRenderPasses;
    [Compose] public ComputeColor SpecularHighlightsShiftNoiseTexture;
    [Compose] public ComputeColor SecondarySpecularGlintsNoiseTexture;

    [Compose] public IMaterialHairLightAttenuationFunction hairLightAttenuationFunction;
    [Compose] public IMaterialHairDirectionFunction hairDirectionFunction;
    [Compose] public IMaterialHairShadowingFunction hairShadowingFunction;
    [Compose] public IMaterialHairDiscardFunction hairDiscardFunction;
    [Compose] public IMaterialSpecularMicrofacetEnvironmentFunction environmentFunction;
    [CBuffer("PerMaterial"), Stage, Color] public float3 HairSpecularColor1;

    // The color of the primary specular reflection.
    [CBuffer("PerMaterial"), Stage, Color] public float3 HairSpecularColor2;

    // The color of the secondary specular reflection.
    [CBuffer("PerMaterial"), Stage] public float HairScalesAngle;
    [CBuffer("PerMaterial"), Stage] public float HairSpecularShiftRatio;
    [CBuffer("PerMaterial"), Stage] public float HairSpecularExponent1;
    [CBuffer("PerMaterial"), Stage] public float HairSpecularExponent2;
    [CBuffer("PerMaterial"), Stage] public float HairSpecularScale1;
    [CBuffer("PerMaterial"), Stage] public float HairSpecularScale2;
    [CBuffer("PerMaterial"), Stage] public float HairShiftNoiseScale;
    // Controls how much the noise should affect the specular highlight direction.
    [CBuffer("PerMaterial"), Stage] public float HairGlintsNoiseStrength;


    /// <summary>
    /// Holds all the required input data for hair shading.
    /// </summary>

    /// <summary>
    /// Holds all the required input data for hair shading.
    /// </summary>
    public struct SurfaceData
    {
        public float hairScalesAngle;
        public float hairSpecularShiftRatio;
        public float3 WBinormal;
        public float3 WViewDir;
        public float3 WNormal;
        public float hairSpecularExponent1;
        // TODO: This is ignored by the indirect lighting.
        public float hairSpecularExponent2;
        // TODO: This is ignored by the indirect lighting.
        public float3 hairSpecularColor1;
        public float3 hairSpecularColor2;
        public float cavity;
        public float hairSpecularScale1;
        public float hairSpecularScale2;
        public float hairSecondarySpecularGlintsNoise;
        public float hairSpecularHighlightsShiftNoise;
    }

    //stream SurfaceData surfaceData;
    public static SurfaceData surfaceData;

    // TODO: How to make the variable not get exposed in the CodeBehind? Sadly making this a streams variable causes a shader compilation error.
    public virtual SurfaceData GenerateSurfaceData()
    {
        SurfaceData result;
        result.hairScalesAngle = HairScalesAngle;
        result.hairSpecularShiftRatio = HairSpecularShiftRatio;
        result.WViewDir = streams.viewWS;
        result.WNormal = streams.normalWS;

        // TODO: Use mesh normal or normal map normal?
        result.WBinormal = hairDirectionFunction.Compute(streams.meshNormal, streams.meshTangent, (float3x3)WorldInverseTranspose);

        // TODO: PERFORMANCE: Get rid of the float3x3 cast?
        result.hairSpecularExponent1 = HairSpecularExponent1;
        result.hairSpecularExponent2 = HairSpecularExponent2;

        result.hairSpecularColor1 = HairSpecularColor1;
        result.hairSpecularColor2 = HairSpecularColor2;

        result.hairSpecularScale1 = HairSpecularScale1;
        result.hairSpecularScale2 = HairSpecularScale2;

        // We can't use "streams.matSpecularVisible" here because it is multiplied by the specular color.
        result.cavity = lerp(1.0f, streams.matCavity, streams.matCavitySpecular);

        result.hairSpecularHighlightsShiftNoise = (SpecularHighlightsShiftNoiseTexture.Compute().r - 0.5f) * HairShiftNoiseScale;
        //result.hairSpecularHighlightsShiftNoise = SpecularHighlightsShiftNoiseTexture.Compute().r * HairShiftNoiseScale;
        result.hairSecondarySpecularGlintsNoise = lerp(1.0f, SecondarySpecularGlintsNoiseTexture.Compute().r, HairGlintsNoiseStrength);

        return result;
    }

    public override void PrepareForLightingAndShading()
    {
        surfaceData = GenerateSurfaceData();
    }

    public virtual void CalculateShiftAngles(SurfaceData surfaceData, out float shiftAngle1, out float shiftAngle2)
    {
        // The hair shift is being calculated differently from Mizuchi because the Mizuchi implementation is weird.
        float scalesAngle = surfaceData.hairScalesAngle;
        shiftAngle1 = 2.0f * scalesAngle;
        shiftAngle2 = -shiftAngle1 * surfaceData.hairSpecularShiftRatio;

        // hairSpecularShiftRatio is theoretically 1.5
        shiftAngle1 += surfaceData.hairSpecularHighlightsShiftNoise;
        shiftAngle2 += surfaceData.hairSpecularHighlightsShiftNoise;
        // I think Mizuchi subtracts the noise from the 2nd shift angle. That isn't correct according to my research, so I changed it.
    }

    public virtual float HairSingleSpecularTerm_Kajiya(float3 T, float3 toLightVec, float3 viewDir, float shiftAngle)
    {
        float cosTL = dot(T, toLightVec);
        float sinTL = sqrt(1.0f - cosTL * cosTL);

        // in Kajiya's model: specular component: cos(t, rl) * cos(t, e) + sin(t, rl)sin(t, e)
        float cosT_RL = -cosTL;
        float sinT_RL = sinTL;
        float cosTE = dot(T, viewDir);
        float sinTE = sqrt(1.0f - cosTE * cosTE);

        // Kajiya-Kay highlight: reflected direction shifted
        float cosT_RL_shifted = cosT_RL * cos(shiftAngle) - sinT_RL * sin(shiftAngle);
        float sinT_RL_shifted = sqrt(1 - cosT_RL_shifted * cosT_RL_shifted);
        return max(0.0f, cosT_RL_shifted * cosTE + sinT_RL_shifted * sinTE);
    }


    //------------------------------------------------------------------------------
    // From Shader X3, Chapter 2.14 (Hair Rendering and Shading), P.244 :
    // "sum the contribution of two separate specular terms per light"
    // "each term has different specular colors, exponents, and is shifted in different directions
    //------------------------------------------------------------------------------
    public virtual float HairSingleSpecularTerm_Scheuermann(float3 T, float3 H, float exponent)
    {
        float dotTH = dot(T, H);
        //float sinTH = sqrt(1.0 - dotTH * dotTH);  // Original version from Mizuchi. Causes artifacts with Scheuermann approximation because of the mathematically correct rotation. The original implementation doesn't suffer from that issue.
        float sinTH = sqrt(max(1.0f - dotTH * dotTH, 0.0f));
        // We limit the value above 0.0 so it doesn't cause NaN errors with the Scheuermann approximation (because of the mathematically correct rotation).
        return pow(sinTH, exponent);
    }


    //==============================================================================
    // From Shader X3, Chapter 2.14 (Hair Rendering and Shading), P.244 :
    // "specular highlights are shifted because the scales on the surface of a hair strand have tilted normals"
    // "ideally we would tilt the tangent in the direction of the viewer"
    // "in practice it is sufficient to tilt in the direction of the geometric normal"
    //==============================================================================
    //------------------------------------------------------------------------------
    // Original formula
    //------------------------------------------------------------------------------
    //float3 ShiftTangent(float3 T, float3 N, float shiftAmount)
    //{
    //    return normalize(T + shiftAmount * N);
    //}
    //
    //------------------------------------------------------------------------------
    // Alternative formula (mathematically correct rotation):
    // Return vector X (= vector T rotated by angle shiftAngle towards direction N)
    //------------------------------------------------------------------------------
    public virtual float3 ShiftTangent(float3 T, float3 N, float shiftAngle)
    {
        // While this function performs mathematically correct rotation, it's probably not desired
        // (because the shift texture doesn't represent angles) and instead the original formula should be preferred.
        // This is because it can cause the rotation to go beyond 90 degrees, causing the shading vector to point inside the surface,
        // causing weird artifacts and issues in other parts of the shading code, which weren't modified to work with the mathematically
        // correct rotation but still assume the original shift implemnetation.
        float cosTX = cos(shiftAngle);
        float sinTX = sqrt(1.0f - cosTX * cosTX) * sign(shiftAngle);

        if (ShadingModel == HAIR_SHADING_SCHEUERMANN_APPROXIMATION)
        {
            //return normalize(N + T * shiftAngle);   // Original formula
            // Simplification (if T,N normal) - Use when T and N are normal
            //float cosTN = 0.0;
            //float sinTN = 1.0;
            return cosTX * T + sinTX * N;
        }
        else
        {
            // Handling case when T and N are not really normal
            float cosTN = dot(T, N);
            float sinTN = sqrt(1.0f - cosTN * cosTN);
            float3 X = (cosTX * sinTN - cosTN * sinTX) * T + sinTN * sinTX * N;
            return normalize(X);
        }
    }

    public virtual float HairSpecularAttenuation(float dotNL)
    {
        if (ShadingModel == HAIR_SHADING_KAJIYAKAY_SHIFTED)
        {
            // No ad-hoc attenuation in Kajiya-Kay formula
            // The coefficient for diffuse is applied during ComputeHairLightingSpecular(),
            // therefore we do not apply dotNL.
            return 1.0f;
        }
        else
        {
            //------------------------------------------------------------------------------
            // From Shader X3, Chapter 2.14 (Hair Rendering and Shading), P.246 :
            // "specular attenuation for hair facing away from light"
            //------------------------------------------------------------------------------
            return saturate(1.75f * dotNL + 0.25f);
        }
    }

    public virtual float3 ComputeSpecularKajiya(SurfaceData surfaceData, float3 toLightVec, float shiftAngle, float specularScale, float specularExponent, float3 specularColor)
    {
        //--------------------------------------------------------------------------
        // Shifted Kajiya-Kay formula (extension of Kajiya-Kay)
        // Similar to what is used in AMD TressFX sample.
        //--------------------------------------------------------------------------
        float shiftedSpecular = HairSingleSpecularTerm_Kajiya(surfaceData.WBinormal, toLightVec, surfaceData.WViewDir, shiftAngle);
        return (specularScale * specularColor * pow(shiftedSpecular, specularExponent));
    }

    public virtual float3 ComputeSpecularScheuermann(SurfaceData surfaceData, float3 halfVector, float shiftAngle, float specularScale, float specularExponent, float3 specularColor)
    {
        //--------------------------------------------------------------------------
        // Scheuermann formula
        //--------------------------------------------------------------------------
        // From Shader X3, Chapter 2.14 (Hair Rendering and Shading), P.245 :
        // "The lack of real self-shadowing will cause the specular highlights to be
        //  too bright on the hair facing away from the light"
        // "To fade out the specular highlight on the shadowed side of the hair, we
        //  multiply by an attenuation term that is similar to the diffuse term."
        //--------------------------------------------------------------------------

        // shift tangents
        float3 shiftDirection = default;

        if (ShadingModel == HAIR_SHADING_SCHEUERMANN_APPROXIMATION)
        {
            shiftDirection = surfaceData.WNormal;
        }
        else if (ShadingModel == HAIR_SHADING_SCHEUERMANN_IMPROVED)
        {
            shiftDirection = surfaceData.WViewDir;
        }

        float3 T = Sdsl.Const(ShiftTangent(surfaceData.WBinormal, shiftDirection, shiftAngle));

        // specular term
        return (specularScale * specularColor * HairSingleSpecularTerm_Scheuermann(T, halfVector, specularExponent));
    }


    //==============================================================================
    // Specular term for hair (for Direct Lighting)
    //==============================================================================
    public virtual float3 ComputeHairLightingSpecular(SurfaceData surfaceData, float3 halfVector, float3 toLightVec)
    {
        // modulate specular shift by a texture
        float shiftAngle1 = default;
        float shiftAngle2 = default;
        CalculateShiftAngles(surfaceData, out shiftAngle1, out shiftAngle2);

        float hairSpecularExponent1 = surfaceData.hairSpecularExponent1;
        // We already make sure on the CPU side that "surfaceData.hairSpecularExponent1" can't be "0.0".
        float hairSpecularExponent2 = surfaceData.hairSpecularExponent2;

        // We already make sure on the CPU side that "surfaceData.hairSpecularExponent2" can't be "0.0".
        float3 specular1;
        float3 specular2;
        if (ShadingModel == HAIR_SHADING_KAJIYAKAY_SHIFTED)
        {
            // primary highlight: reflected direction shift towards tip
            specular1 = ComputeSpecularKajiya(surfaceData, toLightVec, shiftAngle1, surfaceData.hairSpecularScale1, hairSpecularExponent1, surfaceData.hairSpecularColor1);
            // secondary highlight: reflected direction shifted toward root
            specular2 = ComputeSpecularKajiya(surfaceData, toLightVec, shiftAngle2, surfaceData.hairSpecularScale2, hairSpecularExponent2, surfaceData.hairSpecularColor2);
        }
        else
        {
            // specular terms
            specular1 = ComputeSpecularScheuermann(surfaceData, halfVector, shiftAngle1, surfaceData.hairSpecularScale1, hairSpecularExponent1, surfaceData.hairSpecularColor1);
            specular2 = ComputeSpecularScheuermann(surfaceData, halfVector, shiftAngle2, surfaceData.hairSpecularScale2, hairSpecularExponent2, surfaceData.hairSpecularColor2);
        }

        // modulate secondary specular term with noise
        specular2 *= surfaceData.hairSecondarySpecularGlintsNoise;

        float3 specular = (specular1 + specular2) * hairShadowingFunction.Compute();
        // Used to apply shadowing/scattering.
        return specular * surfaceData.cavity;
    }

    public virtual float3 ComputeSpecularIndirectLighting(SurfaceData surfaceData, float shiftAngle, float3 specularColor)
    {
        float3 shiftedNormal = Sdsl.Const(ShiftTangent(surfaceData.WBinormal, surfaceData.WNormal, shiftAngle));

        // specular term
        float shiftedNdotV = Sdsl.Const(max(dot(shiftedNormal, surfaceData.WViewDir), 0.0f));

        float3 specular = environmentFunction.Compute(specularColor, streams.alphaRoughness, shiftedNdotV) * streams.envLightSpecularColor;

        // Since "SpecularTerm_IBL()", which is replaced by "environmentFunction.Compute()",
        // applies the cavity parameter internally, we do it too:
        specular *= surfaceData.cavity;

        return specular;
    }


    //==============================================================================
    // Specular term for hair (for Indirect Lighting)
    //------------------------------------------------------------------------------
    // Similarly to what is done for the direct lighting, we compute the specular component based on the shifted hair tangents.
    // This is not physically realistic because:
    // - the ambientBRDF map does not convolve the hair specular BRDF
    // However, this is a satisfying approximation at first.
    //==============================================================================
    public virtual float3 ComputeHairImageBasedLightingSpecular(SurfaceData surfaceData)
    {
        //return 1.0;

        // shift tangents
        float shiftAngle1 = default;
        float shiftAngle2 = default;
        CalculateShiftAngles(surfaceData, out shiftAngle1, out shiftAngle2);

        float3 specular1 = ComputeSpecularIndirectLighting(surfaceData, shiftAngle1, surfaceData.hairSpecularColor1);
        float3 specular2 = ComputeSpecularIndirectLighting(surfaceData, shiftAngle2, surfaceData.hairSpecularColor2);

        specular1 *= surfaceData.hairSpecularScale1;
        // TODO: This is a workaround to make the indirect lighting look better. Not sure if we should keep it as it basically scales the specular reflection like it does for the direct lighting.
        specular2 *= surfaceData.hairSpecularScale2;
        // TODO: This is a workaround to make the indirect lighting look better. Not sure if we should keep it as it basically scales the specular reflection like it does for the direct lighting.

        // modulate secondary specular term with noise
        specular2 *= surfaceData.hairSecondarySpecularGlintsNoise;

        return specular1 + specular2;
    }

    public override float3 ComputeDirectLightContribution()
    {
        if (DebugRenderPasses)
        {
            return 0.0f;
            // Return 0.0 because the indirect lighting function already returns the debug color.
        }

        float3 specular = ComputeHairLightingSpecular(surfaceData, streams.H, streams.lightDirectionWS);

        // Vector pointing from the pixel towards the light.
        float NdotLUnsaturated = Sdsl.Const(dot(normalize(streams.normalWS), normalize(streams.lightDirectionWS)));
        // TODO: PERFORMANCE: Normalization necessary?

        //specular *= saturate(NdotLUnsaturated * 0.5 + 0.5);   // This could be used in combination with hair SSS.
        specular *= HairSpecularAttenuation(NdotLUnsaturated);
        specular *= hairLightAttenuationFunction.Compute();
        specular *= streams.lightColor * streams.lightAttenuation * streams.matDiffuseSpecularAlphaBlend.y;
        //specular *= streams.lightDirectAmbientOcclusion;

        // TODO: Multiply by alpha or not?
        return specular * streams.matDiffuse.a;
        // TODO: Technically we should use "streams.shadingColorAlpha" but its value is assigned AFTER the shading, which makes it useless.
    }

    public override float3 ComputeEnvironmentLightContribution()
    {
        if (DebugRenderPasses)
        {
            return GetDebugColor(PassID);
        }

        // TODO: Multiply by alpha or not?
        return ComputeHairImageBasedLightingSpecular(surfaceData).rgb * streams.matDiffuse.a;
        // TODO: Technically we should use "streams.shadingColorAlpha" but its value is assigned AFTER the shading, which makes it useless.
    }

    public override void AfterLightingAndShading()
    {
        hairDiscardFunction.Discard();
    }
}
