// <auto-generated>
// The engine's MaterialHairLightAttenuationFunctionDirectional (MaterialHairLightAttenuationFunctionDirectional.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
[Mixin(typeof(NormalStream), typeof(LightStream))]
public abstract partial class MaterialHairLightAttenuationFunctionDirectional : IMaterialHairLightAttenuationFunction
{
    [Generic] public static int NormalMode;
    [Generic] public static LinkType THardnessReciprocal;
    [Generic] public static LinkType TBoundaryShift;
    [CBuffer("PerMaterial"), Stage, Link("THardnessReciprocal")] public float HardnessReciprocal;
    // == 1.0 / hardness
    [CBuffer("PerMaterial"), Stage, Link("TBoundaryShift")] public float BoundaryShift;

    public virtual float CalculateNdotL()
    {
        float3 meshNormalWorldSpaceShifted = Sdsl.Const(normalize(lerp(streams.meshNormalWS, -streams.lightDirectionWS, BoundaryShift)));
        float3 normalMapNormalShifted = Sdsl.Const(normalize(lerp(streams.normalWS, -streams.lightDirectionWS, BoundaryShift)));

        // If no normal map is present, this will be equal to the mesh normal.
        if (NormalMode == 0)
        // Mesh normals:
        {
            return dot(meshNormalWorldSpaceShifted, streams.lightDirectionWS);
        }
        else if (NormalMode == 1)
        // Normal map normals:
        {
            return dot(normalMapNormalShifted, streams.lightDirectionWS);
        }
        else
        // Mesh & normal map normals:
        {
            // Alternate approach:
            //return max(dot(normalMapNormalShifted, streams.lightDirectionWS),
            //           dot(meshNormalWorldSpaceShifted, streams.lightDirectionWS));

            // More conservative approach:
            return min(dot(normalMapNormalShifted, streams.lightDirectionWS), dot(meshNormalWorldSpaceShifted, streams.lightDirectionWS));
        }
    }

    [Redeclare]
    public override float Compute()
    {
        float saturatedNdotL = saturate(CalculateNdotL());
        return pow(saturatedNdotL, HardnessReciprocal);
    }
}
