// <auto-generated>
// The engine's MaterialSpecularMicrofacetVisibilityImplicit (MaterialSpecularMicrofacetVisibilityImplicit.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Interface for a microfacet Geometric Shadowing function
/// </summary>
[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
public abstract partial class MaterialSpecularMicrofacetVisibilityImplicit : IMaterialSpecularMicrofacetVisibilityFunction
{
    public override float Compute()
    {
        return VisibilityImplicit(streams.NdotL, streams.NdotV);
    }
}
