// <auto-generated>
// The engine's MaterialSubsurfaceScatteringScatteringProfileSkin (MaterialSubsurfaceScatteringScatteringProfileSkin.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class MaterialSubsurfaceScatteringScatteringProfileSkin : IMaterialSubsurfaceScatteringScatteringProfile
{
    [Redeclare]
    public override float3 Compute(float dd)
    {
        // Hardcoded skin profile from https://github.com/iryoku/separable-sss
        return new float3(0.233f, 0.455f, 0.649f) * exp(dd / 0.0064f) + new float3(0.1f, 0.336f, 0.344f) * exp(dd / 0.0484f) + new float3(0.118f, 0.198f, 0.0f) * exp(dd / 0.187f) + new float3(0.113f, 0.007f, 0.007f) * exp(dd / 0.567f) + new float3(0.358f, 0.004f, 0.0f) * exp(dd / 1.99f) + new float3(0.078f, 0.0f, 0.0f) * exp(dd / 7.41f);
    }
}
