// <auto-generated>
// The declarations of the engine's MaterialHairLightAttenuationFunctionDirectional (MaterialHairLightAttenuationFunctionDirectional.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(NormalStream), typeof(LightStream))]
public abstract partial class MaterialHairLightAttenuationFunctionDirectional : IMaterialHairLightAttenuationFunction
{
    [Generic] public static int NormalMode;
    [Generic] public static LinkType THardnessReciprocal;
    [Generic] public static LinkType TBoundaryShift;
    [CBuffer("PerMaterial"), Stage, Link("THardnessReciprocal")] public float HardnessReciprocal;
    // == 1.0 / hardness
    [CBuffer("PerMaterial"), Stage, Link("TBoundaryShift")] public float BoundaryShift;

    public virtual float CalculateNdotL() => throw Gpu.Only;

    [Redeclare]
    public override float Compute() => throw Gpu.Only;
}
