// <auto-generated>
// The engine's MaterialSurfaceNormalMap (MaterialSurfaceNormalMap.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Material normal map
/// </summary>
[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
public abstract partial class MaterialSurfaceNormalMap : IMaterialSurfacePixel
{
    [Generic] public static bool TIsNormalXY1;
    [Generic] public static bool TScaleAndBias;
    [Compose] public ComputeColor normalMap;

    public override void Compute()
    {
        var normal = normalMap.Compute();

        // For unsigned textures we need to convert (0, 1) to (-1, 1) range
        if (TScaleAndBias)
        {
            normal = (2.0f * normal) - 1.0f;
        }

        // If Z is calculated from XY do it here
        if (TIsNormalXY1)
        {
            normal.z = sqrt(max(0, 1.0f - (normal.x * normal.x + normal.y * normal.y)));
        }

        // Note! Don't normalize the streams.matNormal here, it's being normalize when streams.normalWS is calculated
        streams.matNormal = normal.xyz;
    }
}
