// <auto-generated>
// The declarations of the engine's MaterialSurfaceSubsurfaceScatteringShading (MaterialSurfaceSubsurfaceScatteringShading.sdsl, Stride 4.4.0-beta7), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Performs subsurface scattering using shadow maps.
/// </summary>
[Shader(External = true)]
[Mixin(typeof(IMaterialSurfaceShading), typeof(MaterialPixelShadingStream), typeof(ShadowStream), typeof(Math))]
public abstract partial class MaterialSurfaceSubsurfaceScatteringShading : IMaterialSubsurfaceScatteringScatteringProfile
{
    [CBuffer("PerMaterial"), Stage] public float Translucency;
    [CBuffer("PerMaterial"), Stage] public float ScatteringWidth;

    [Compose] public IMaterialSubsurfaceScatteringScatteringProfile scatteringProfileFunction;

    [Stream] public float scatteringStrength;

    // TODO: Do we need the stage keyword here?
    public virtual float3 CalculateTransmittance(float thickness, float translucency, float sssWidth, float3 meshNormalWS, float3 lightDirectionWS, float3 attenuatedLightColor, float3 surfaceAlbedo) => throw Gpu.Only;

    [Override]
    public virtual void PrepareForLightingAndShading() => throw Gpu.Only;

    [Override]
    public virtual float3 ComputeDirectLightContribution() => throw Gpu.Only;

    [Override]
    public virtual void AfterLightingAndShading() => throw Gpu.Only;
}
