// <auto-generated>
// The declarations of the engine's MaterialSurfaceShadingSpecularHair (MaterialSurfaceShadingSpecularHair.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Performs hair shading.
/// </summary>
[Shader(External = true)]
[Mixin(typeof(MaterialPixelShadingStream), typeof(MaterialHairShared), typeof(NormalStream), typeof(Transformation), typeof(MaterialPixelStream))]
public abstract partial class MaterialSurfaceShadingSpecularHair : IMaterialSurfaceShading
{
    [Generic] public static int ShadingModel;
    [Generic] public static bool DebugRenderPasses;
    [Compose] public ComputeColor SpecularHighlightsShiftNoiseTexture;
    [Compose] public ComputeColor SecondarySpecularGlintsNoiseTexture;

    [Compose] public IMaterialHairLightAttenuationFunction hairLightAttenuationFunction;
    [Compose] public IMaterialHairDirectionFunction hairDirectionFunction;
    [Compose] public IMaterialHairShadowingFunction hairShadowingFunction;
    [Compose] public IMaterialHairDiscardFunction hairDiscardFunction;
    [Compose] public IMaterialSpecularMicrofacetEnvironmentFunction environmentFunction;
    [CBuffer("PerMaterial"), Stage, Color] public float3 HairSpecularColor1;

    // The color of the primary specular reflection.
    [CBuffer("PerMaterial"), Stage, Color] public float3 HairSpecularColor2;

    // The color of the secondary specular reflection.
    [CBuffer("PerMaterial"), Stage] public float HairScalesAngle;
    [CBuffer("PerMaterial"), Stage] public float HairSpecularShiftRatio;
    [CBuffer("PerMaterial"), Stage] public float HairSpecularExponent1;
    [CBuffer("PerMaterial"), Stage] public float HairSpecularExponent2;
    [CBuffer("PerMaterial"), Stage] public float HairSpecularScale1;
    [CBuffer("PerMaterial"), Stage] public float HairSpecularScale2;
    [CBuffer("PerMaterial"), Stage] public float HairShiftNoiseScale;
    // Controls how much the noise should affect the specular highlight direction.
    [CBuffer("PerMaterial"), Stage] public float HairGlintsNoiseStrength;


    /// <summary>
    /// Holds all the required input data for hair shading.
    /// </summary>

    /// <summary>
    /// Holds all the required input data for hair shading.
    /// </summary>
    public struct SurfaceData
    {
        public float hairScalesAngle;
        public float hairSpecularShiftRatio;
        public float3 WBinormal;
        public float3 WViewDir;
        public float3 WNormal;
        public float hairSpecularExponent1;
        // TODO: This is ignored by the indirect lighting.
        public float hairSpecularExponent2;
        // TODO: This is ignored by the indirect lighting.
        public float3 hairSpecularColor1;
        public float3 hairSpecularColor2;
        public float cavity;
        public float hairSpecularScale1;
        public float hairSpecularScale2;
        public float hairSecondarySpecularGlintsNoise;
        public float hairSpecularHighlightsShiftNoise;
    }

    //stream SurfaceData surfaceData;
    public static SurfaceData surfaceData;

    // TODO: How to make the variable not get exposed in the CodeBehind? Sadly making this a streams variable causes a shader compilation error.
    public virtual SurfaceData GenerateSurfaceData() => throw Gpu.Only;

    public override void PrepareForLightingAndShading() => throw Gpu.Only;

    public virtual void CalculateShiftAngles(SurfaceData surfaceData, out float shiftAngle1, out float shiftAngle2) => throw Gpu.Only;

    public virtual float HairSingleSpecularTerm_Kajiya(float3 T, float3 toLightVec, float3 viewDir, float shiftAngle) => throw Gpu.Only;


    //------------------------------------------------------------------------------
    // From Shader X3, Chapter 2.14 (Hair Rendering and Shading), P.244 :
    // "sum the contribution of two separate specular terms per light"
    // "each term has different specular colors, exponents, and is shifted in different directions
    //------------------------------------------------------------------------------
    public virtual float HairSingleSpecularTerm_Scheuermann(float3 T, float3 H, float exponent) => throw Gpu.Only;


    //==============================================================================
    // From Shader X3, Chapter 2.14 (Hair Rendering and Shading), P.244 :
    // "specular highlights are shifted because the scales on the surface of a hair strand have tilted normals"
    // "ideally we would tilt the tangent in the direction of the viewer"
    // "in practice it is sufficient to tilt in the direction of the geometric normal"
    //==============================================================================
    //------------------------------------------------------------------------------
    // Original formula
    //------------------------------------------------------------------------------
    //float3 ShiftTangent(float3 T, float3 N, float shiftAmount)
    //{
    //    return normalize(T + shiftAmount * N);
    //}
    //
    //------------------------------------------------------------------------------
    // Alternative formula (mathematically correct rotation):
    // Return vector X (= vector T rotated by angle shiftAngle towards direction N)
    //------------------------------------------------------------------------------
    public virtual float3 ShiftTangent(float3 T, float3 N, float shiftAngle) => throw Gpu.Only;

    public virtual float HairSpecularAttenuation(float dotNL) => throw Gpu.Only;

    public virtual float3 ComputeSpecularKajiya(SurfaceData surfaceData, float3 toLightVec, float shiftAngle, float specularScale, float specularExponent, float3 specularColor) => throw Gpu.Only;

    public virtual float3 ComputeSpecularScheuermann(SurfaceData surfaceData, float3 halfVector, float shiftAngle, float specularScale, float specularExponent, float3 specularColor) => throw Gpu.Only;


    //==============================================================================
    // Specular term for hair (for Direct Lighting)
    //==============================================================================
    public virtual float3 ComputeHairLightingSpecular(SurfaceData surfaceData, float3 halfVector, float3 toLightVec) => throw Gpu.Only;

    public virtual float3 ComputeSpecularIndirectLighting(SurfaceData surfaceData, float shiftAngle, float3 specularColor) => throw Gpu.Only;


    //==============================================================================
    // Specular term for hair (for Indirect Lighting)
    //------------------------------------------------------------------------------
    // Similarly to what is done for the direct lighting, we compute the specular component based on the shifted hair tangents.
    // This is not physically realistic because:
    // - the ambientBRDF map does not convolve the hair specular BRDF
    // However, this is a satisfying approximation at first.
    //==============================================================================
    public virtual float3 ComputeHairImageBasedLightingSpecular(SurfaceData surfaceData) => throw Gpu.Only;

    public override float3 ComputeDirectLightContribution() => throw Gpu.Only;

    public override float3 ComputeEnvironmentLightContribution() => throw Gpu.Only;

    public override void AfterLightingAndShading() => throw Gpu.Only;
}
