// <auto-generated>
// The engine's MaterialHairDiscardFunctionOpaquePass (MaterialHairDiscardFunctionOpaquePass.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Renders only the opaque parts for the opaque hair pass.
/// </summary>
[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
[Mixin(typeof(MaterialPixelStream))]
public abstract partial class MaterialHairDiscardFunctionOpaquePass : IMaterialHairDiscardFunction
{
    [Generic] public static LinkType THairAlphaThreshold;
    [CBuffer("PerMaterial"), Stage, Link("THairAlphaThreshold")] public float HairAlphaThreshold;

    [Redeclare]
    public override void Discard()
    {
        if (streams.matDiffuse.a < HairAlphaThreshold)
        {
            discard();
        }
    }
}
