// <auto-generated>
// The declarations of the engine's NormalFromMeshInstanced (NormalFromMeshInstanced.sdsl, Stride 4.4.0-beta7), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Tebjan Halm
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Computes normals in view space.
/// </summary>
[Shader(External = true)]
[Mixin(typeof(TransformationInstancing))]
public abstract partial class NormalFromMeshInstanced : NormalFromMesh
{
    [Stage(AfterOverride = true)]
    public override void GenerateNormal_VS() => throw Gpu.Only;
}
