// <auto-generated>
// The engine's NormalVSSkinningNormalMapping (NormalVSSkinningNormalMapping.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Computes the transformation matrix from tangent to view space when skinning occured.
/// </summary>
[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
public abstract partial class NormalVSSkinningNormalMapping : NormalFromNormalMapping
{
    public override float3x3 GetTangentWorldTransform()
    {
        // TangentMatrix is already in world space, so return an identity matrix here
        return new float3x3(1, 0, 0, 0, 1, 0, 0, 0, 1);
    }
}
