// <auto-generated>
// The engine's NormalVSSkinningNormalMappingTessellation (NormalVSSkinningNormalMappingTessellation.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Calculates the normal  the normals from a normal map.
/// </summary>
[Shader(External = true)]
public abstract partial class NormalVSSkinningNormalMappingTessellation : NormalVSSkinningNormalMapping
{
    [Override, Stage(AfterOverride = true)]
    public virtual void GenerateNormal_VS()
    {
        // Because meshNormal is already integrating World space, use it as-is for final normalWS
        streams.normalWS = streams.meshNormal;
    }
}
