// <auto-generated>
// The declarations of the engine's NormalUpdate (NormalUpdate.sdsl, Stride 4.4.0-beta7), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Defines the methods to get the normal in world space.
/// </summary>
[Shader(External = true)]
public abstract partial class NormalUpdate : NormalStream
{
    [Stage]
    public virtual void GenerateNormal_VS() => throw Gpu.Only;

    [Stage]
    public virtual void GenerateNormal_PS() => throw Gpu.Only;

    public virtual float3x3 GetTangentMatrix() => throw Gpu.Only;

    [Stage]
    public virtual void UpdateTangentToWorld() => throw Gpu.Only;

    public virtual float3x3 GetTangentWorldTransform() => throw Gpu.Only;


    // This method is called by the MaterialSurfaceLightingAndShading to calculate the effective normal
    [Stage]
    public virtual void UpdateNormalFromTangentSpace(float3 normalInTangentSpace) => throw Gpu.Only;
}
