// <auto-generated>
// The declarations of the engine's ParticleBase (ParticleBase.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(ShaderBase), typeof(Texturing), typeof(ParticleUtilities))]
[Define("UsesSoftEdge", "0", If = "!defined(UsesSoftEdge)")]
public abstract partial class ParticleBase : DepthBase
{
    // -------------------------------------
    // streams
    // -------------------------------------

    // Shading position of the vertices/pixels
    [Stage, Stream("POSITION")] public float4 Position;
    [If("!(STRIDE_GRAPHICS_PROFILE >= GRAPHICS_PROFILE_LEVEL_10_0)"), Stage, Stream("SCREEN_POSITION")] public float4 ScreenPosition;

    // Linear depth of the position in view space in world units, used for soft edges
    [Stage, Stream("Z_DEPTH_VALUE")] public float ZDepth;

    // -------------------------------------
    // conditional streams - may or may not be present depending on existing particle fields
    // -------------------------------------
    //stage stream float4 Color : COLOR;
    [Modifiers("nointerpolation"), Stage, Stream("BATCH_LIFETIME")] public float Lifetime;
    [Modifiers("nointerpolation"), Stage, Stream("BATCH_RANDOMSEED")] public float RandomSeed;
    // Ideally should be uint. Note! The sdsl doesn't support nointerpolation, so cast the float as int before using it
    [CBuffer("PerMaterial"), Stage] public float4 ColorScale;

    // When the value is 0 there is no occlusion (100% emissive), when it is 1 there is 100% occlusion (still limited by alpha)
    [CBuffer("PerMaterial"), Stage] public float AlphaAdditive;

    // Z offset is how much the depth should be adjusted when rendering
    [CBuffer("PerMaterial"), Stage] public float ZOffset;

    // 0 if disabled, equal to 1/Distance otherwise
    [CBuffer("PerMaterial"), Stage] public float SoftEdgeInverseDistance;


    // -------------------------------------
    // VertexShader
    // -------------------------------------

    // Override Vertex shader main method from the ShaderBase shader
    [Override, Stage]
    public virtual void VSMain() => throw Gpu.Only;


    // -------------------------------------
    // PixelShader
    // -------------------------------------

    // Override Pixel shader main method from the ShaderBase shader
    [Override, Stage]
    public virtual void PSMain() => throw Gpu.Only;

    [Stage]
    public virtual float4 Shading() => throw Gpu.Only;
}
