// <auto-generated>
// The declarations of the engine's PostEffectBoundingRay (PostEffectBoundingRay.sdsl, Stride 4.4.0-beta7), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <remarks>
/// TSampleCount: generic int - number of iterations.
/// </remarks>
[Shader(External = true)]
[Mixin(typeof(DepthBase), typeof(Transformation), typeof(PositionStream4))]
public abstract partial class PostEffectBoundingRay : ImageEffectShader
{
    [Generic] public static int TSampleCount;

    public virtual float3 ComputeColorOut() => throw Gpu.Only;

    public virtual float3 ComputeColorIn(float4 positionWS, float stepSize, int stepIndex) => throw Gpu.Only;

    public virtual int HashXYZ(float3 input) => throw Gpu.Only;

    public virtual float RayStepJitter(float3 input, float stepSize) => throw Gpu.Only;

    public virtual float4 ComputeFinalColor(float3 lightAcc) => throw Gpu.Only;

    [Stage]
    public override void PSMain() => throw Gpu.Only;
}
