// <auto-generated>
// The engine's ShadowMapCasterNoPixelShader (ShadowMapCasterNoPixelShader.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Shadow map caster without pixel shader color outputs (only depth).
/// </summary>
[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
[Mixin(typeof(ShaderBase), typeof(PositionStream))]
public abstract partial class ShadowMapCasterNoPixelShader : Transformation
{
    [Override, Stage(AfterOverride = true)]
    public virtual void PSMain()
    {
        // no code = null pixel shader, as we are outputing depth only
    }
}
