// <auto-generated>
// The declarations of the engine's ShadowMapReceiverPointCubeMap (ShadowMapReceiverPointCubeMap.sdsl, Stride 4.4.0-beta7), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Selects the shadow map and computes the shadow factor.
/// </summary>
[Shader(External = true, Internal = true, BaseGenerics = "PerDraw.Lighting")]
[Mixin(typeof(ShadowMapFilterBase), Generics = "PerDraw.Lighting")]
[Mixin(typeof(PositionStream4), typeof(ShaderBaseStream), typeof(LightStream), typeof(Texturing), typeof(NormalStream))]
public abstract partial class ShadowMapReceiverPointCubeMap : ShadowMapGroup
{
    [Generic] public static int TLightCount;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount*6")] public float4x4[] WorldToShadow;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount*6")] public float4x4[] InverseWorldToShadow;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount")] public float[] DepthBiases;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount")] public float[] OffsetScales;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount")] public float2[] DepthParameters;


    // TODO: Deduplicate
    public virtual float3 GetShadowPositionOffset(float offsetScale, float nDotL, float3 normal) => throw Gpu.Only;

    public virtual float ComputeThickness(float3 positionWS, int cascadeIndex) => throw Gpu.Only;

    public override float3 ComputeShadow(float3 positionWS, int lightIndex) => throw Gpu.Only;
}
