// <auto-generated>
// The engine's ShadowMapFilterDefault (ShadowMapFilterDefault.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Performs default filtering: no filtering.
/// </summary>
[Shader(External = true, BaseGenerics = "PerLighting")]
public abstract partial class ShadowMapFilterDefault : ShadowMapFilterBase
{
    [Generic] public static MemberName PerLighting;

    /// <summary>
    /// Calculate the shadow factor based on the shadow map texture, the position, a sampler
    /// </summary>
    public override float FilterShadow(float2 position, float positionDepth)
    {
        return ShadowMapTexture.SampleCmpLevelZero(LinearClampCompareLessEqualSampler, position, positionDepth);
    }

    public override float FilterThickness(float3 pixelPositionWS, float3 meshNormalWS, float2 depthRanges, float4x4 worldToShadowCascadeUV, float4x4 inverseWorldToShadowCascadeUV, bool isOrthographic)
    {
        //const float filterRadiusInPixels = 1.0;    // 1 pixel filter radius
        const float filterRadiusInPixels = 1.5f;

        // 1.5 pixel filter radius
        float3 adjustedPixelPositionWS = default;
        float3 adjustedPixelPositionShadowSpace = default;

        if (isOrthographic)
        {
            CalculateAdjustedShadowSpacePixelPosition(filterRadiusInPixels, pixelPositionWS, meshNormalWS, worldToShadowCascadeUV, inverseWorldToShadowCascadeUV, out adjustedPixelPositionWS, out adjustedPixelPositionShadowSpace);
        }
        else
        {
            CalculateAdjustedShadowSpacePixelPositionPerspective(filterRadiusInPixels, pixelPositionWS, meshNormalWS, worldToShadowCascadeUV, inverseWorldToShadowCascadeUV, out adjustedPixelPositionWS, out adjustedPixelPositionShadowSpace);
        }

        return SampleThickness(adjustedPixelPositionShadowSpace, adjustedPixelPositionWS, depthRanges, inverseWorldToShadowCascadeUV, isOrthographic);
    }
}
