// <auto-generated>
// The engine's ShadowMapReceiverPointParaboloid (ShadowMapReceiverPointParaboloid.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Selects the shadow map and computes the shadow factor.
/// </summary>
[Shader(External = true, Internal = true, BaseGenerics = "PerDraw.Lighting")]
[System.Diagnostics.DebuggerNonUserCode]
[Mixin(typeof(ShadowMapFilterBase), Generics = "PerDraw.Lighting")]
[Mixin(typeof(PositionStream4), typeof(ShaderBaseStream))]
public abstract partial class ShadowMapReceiverPointParaboloid : ShadowMapGroup
{
    [Generic] public static int TLightCount;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount")] public float4x4[] View;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount")] public float2[] FaceOffsets;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount")] public float2[] BackfaceOffsets;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount")] public float2[] FaceSizes;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount")] public float[] DepthBiases;
    [CBuffer("PerDraw.Lighting"), Size("TLightCount")] public float2[] DepthParameters;

    public override float3 ComputeShadow(float3 position, int lightIndex)
    {
        float4 lightSpace = mul(new float4(position, 1), View[lightIndex]);

        // Store length and normalize
        float distanceToLight = length(lightSpace.xyz);
        float3 intermediate = lightSpace.xyz / distanceToLight;

        // Project x/y coordinates on parabola
        intermediate.xy /= 1.0f + abs(intermediate.z);

        float2 depthParameters = DepthParameters[lightIndex];

        // Apply bias
        distanceToLight -= DepthBiases[lightIndex];

        // Scale distance to light depth buffer range
        distanceToLight *= depthParameters.y;

        // Map from (-1,1) to (0,1)
        intermediate.xy = intermediate.xy * 0.5f + new float2(0.5f, 0.5f);
        intermediate.y = 1.0f - intermediate.y;

        // Apply offset into atlas and size of a single face in the atlas
        float2 samplePosition = intermediate.xy * FaceSizes[lightIndex] + FaceOffsets[lightIndex];

        // Apply offset for the back side face
        Flatten();
        if (lightSpace.z < 0)
        {
            samplePosition += BackfaceOffsets[lightIndex];
        }

        // Compare distance to light to value inside of the shadow map
        float shadow = FilterShadow(samplePosition, distanceToLight);

        // Calculate thickness for SSS:
        float tempThickness = 999.9f;

        // No scattering for now.
        streams.thicknessWS = tempThickness;

        return (shadow);
    }
}
