// <auto-generated>
// The declarations of the engine's ShadowMapCasterParaboloidProjection (ShadowMapCasterParaboloidProjection.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(PositionStream4), typeof(Texturing))]
public abstract partial class ShadowMapCasterParaboloidProjection : TransformationBase
{
    public const float ClippingEpsilon = 0.03f;
    // x = Near; y = 1/(Far-Near)
    [CBuffer("PerView.ShadowCaster")] public float2 DepthParameters;

    // Used to write the distance from an object to the light to the depth buffer
    [Stage, Stream("SV_DEPTH")] public float PixelDepth;

    [Stage]
    public override void PostTransformPosition() => throw Gpu.Only;

    [Stage]
    public override float4 ComputeShadingPosition(float4 world) => throw Gpu.Only;

    public virtual float4 ComputeParaboloidProjection(float4 world, out float depth) => throw Gpu.Only;

    [Stage]
    public override void PSMain() => throw Gpu.Only;
}
