// <auto-generated>
// The declarations of the engine's SignedDistanceFieldFontShader (SignedDistanceFieldFontShader.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(SignedDistanceFieldFont))]
public abstract partial class SignedDistanceFieldFontShader : ShaderBase
{
    // -------------------------------------
    // streams
    // -------------------------------------
    [Stage, Stream("POSITION")] public float4 Position;
    [Stage, Stream("COLOR")] public float4 Color;
    [Stage, Stream("BATCH_SWIZZLE")] public float Swizzle;


    // -------------------------------------
    // VertexShader
    // -------------------------------------
    [Stage]
    public override void VSMain() => throw Gpu.Only;


    // -------------------------------------
    // PixelShader
    // -------------------------------------
    [Stage]
    public override void PSMain() => throw Gpu.Only;

    [Stage]
    public virtual float4 Shading() => throw Gpu.Only;
}
