// <auto-generated>
// The declarations of the engine's SkyboxShaderCubemap (SkyboxShaderCubemap.sdsl, Stride 4.4.0-beta7), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class SkyboxShaderCubemap : SkyboxShaderBase
{
    [Stage] public TextureCube CubeMap;

    [Stage(AfterOverride = true)]
    public override float4 Shading() => throw Gpu.Only;
}
