// <auto-generated>
// The engine's SpriteSuperSampler (SpriteSuperSampler.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class SpriteSuperSampler : SpriteBase
{
    [Stage]
    public override float4 Shading()
    {
        // "call of duty"-type of h4x4 checker box, but reduced to 9 picks instead of 13:
        float2[] jitters = new float2[] { new float2(-2.0f, 0.0f), new float2(0.0f, 0.0f), new float2(2.0f, 0.0f), new float2(-1.0f, 1.0f), new float2(1.0f, 1.0f), new float2(-1.0f, -1.0f), new float2(1.0f, -1.0f), new float2(0.0f, 2.0f), new float2(0.0f, -2.0f) };

        float weightSum = 0;
        float4 color = 0;
        float2 texCoordBackup = streams.TexCoord;

        Unroll();
        for (uint j = 0; j < 9; ++j)
        {
            float2 jitter = jitters[j];
            float dist = max(abs(jitter.x), abs(jitter.y));
            float weight = 3 - dist;
            streams.TexCoord = texCoordBackup + jitter * Texture0TexelSize;
            color += weight * base.Shading();
            weightSum += weight;
        }

        streams.TexCoord = texCoordBackup;

        return color / weightSum;
    }
}
