// <auto-generated>
// The engine's SpriteEffect (SpriteEffect.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class SpriteEffect : SpriteBase
{
    // Color used to tint the sprite
    [Stage, Color] public float4 Color = new float4(1, 1, 1, 1);


    // Shading of the sprite
    [Stage]
    public override float4 Shading()
    {
        return base.Shading() * Color;
    }
}
