// <auto-generated>
// The declarations of the engine's SSLRResolvePass (SSLRResolvePass.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Screen Space Local Reflections shader for Resolve Pass
/// </summary>
[Shader(External = true)]
[Mixin(typeof(SSLRCommon), typeof(NormalPack), typeof(Math), typeof(BRDFMicrofacet))]
public abstract partial class SSLRResolvePass : ImageEffectShader
{
    [Generic] public static int ResolveSamples;
    [Generic] public static bool ReduceHighlights;
    [Size("8")] public static readonly float2[] Offsets = default!;

    [Stage(AfterOverride = true)]
    public override float4 Shading() => throw Gpu.Only;
}
