// <auto-generated>
// The declarations of the engine's SSLRCommon (SSLRCommon.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Screen Space Local Reflections shader with common variables and functions
/// </summary>
[Shader(External = true)]
[Mixin(typeof(Utilities), typeof(NormalPack))]
public abstract partial class SSLRCommon : ImageEffectShader
{
    [CBuffer("Data"), Stage] public float MaxColorMiplevel;
    [CBuffer("Data"), Stage] public float TraceSizeMax;
    [CBuffer("Data"), Stage] public float MaxTraceSamples;

    //stage float Padding0;
    [CBuffer("Data"), Stage] public float RoughnessFade;
    [CBuffer("Data"), Stage] public float TemporalTime;
    [CBuffer("Data"), Stage] public float BRDFBias;
    [CBuffer("Data"), Stage] public float ViewFarPlane;

    [CBuffer("Data"), Stage] public float4 ViewInfo;

    [CBuffer("Data"), Stage] public float3 CameraPosWS;
    [CBuffer("Data"), Stage] public float WorldAntiSelfOcclusionBias;

    [CBuffer("Data"), Stage] public float4x4 V;
    [CBuffer("Data"), Stage] public float4x4 IVP;


    // Sample raw device depth buffer
    public virtual float SampleZ(in float2 uv) => throw Gpu.Only;


    // Linearize raw device depth
    public virtual float LinearizeZ(in float depth) => throw Gpu.Only;


    // Sample linear depth
    public virtual float SampleDepth(in float2 uv) => throw Gpu.Only;


    // 1:-1 to 0:1
    public virtual float2 ClipToUv(float2 clipPos) => throw Gpu.Only;


    // 0:1 to 1:-1
    public virtual float2 UvToClip(float2 uv) => throw Gpu.Only;

    public virtual float3 ComputeWorldPosition(float2 uv, float rawDepth) => throw Gpu.Only;

    public virtual float3 ComputeWorldPosition(float2 uv) => throw Gpu.Only;

    public virtual float3 ComputeViewPosition(float2 uv, float rawDepth) => throw Gpu.Only;

    public virtual float3 SampleViewPosition(float2 uv) => throw Gpu.Only;

    public virtual float3 ScreenToView(float2 uv, float depth) => throw Gpu.Only;

    public virtual float max2(float2 v) => throw Gpu.Only;

    public virtual float2 RandN2(float2 pos, float2 random) => throw Gpu.Only;
}
