// <auto-generated>
// The declarations of the engine's TextureProjectionReceiverSpot (TextureProjectionReceiverSpot.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Computes the texture projection of a spotlight. Returns the color of the projected texture at this world space position.
/// </summary>
/// <remarks>
/// PerLightGroup: Parameter used to uniquely identify this group of lights.
/// TLightCount: The number of lights inside of this light group.
/// </remarks>
[Shader(External = true, Internal = true)]
[Mixin(typeof(TextureProjectionReceiverBase), Generics = "PerLightGroup, 1, TLightCount, TFlipMode")]
public abstract partial class TextureProjectionReceiverSpot : TextureProjectionGroup
{
    [Generic] public static MemberName PerLightGroup;
    [Generic] public static int TLightCount;
    [Generic] public static int TFlipMode;

    public override float3 ComputeTextureProjection(float3 positionWS, int lightIndex) => throw Gpu.Only;

    public override float3 ComputeSpecularTextureProjection(float3 positionWS, float3 reflectionWS, int lightIndex) => throw Gpu.Only;
}
