// <auto-generated>
// The declarations of the engine's TextureProjectionCommon (TextureProjectionCommon.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// Defines the texture that is projected onto geometry.
/// </summary>
[Shader(External = true)]
public abstract partial class TextureProjectionCommon
{
    [Generic] public static MemberName PerLightGroup;
    [CBuffer("PerLightGroup"), Link("TextureProjection.UVScale")] public float2 UVScale;

    [CBuffer("PerLightGroup"), Link("TextureProjection.UVOffset")] public float2 UVOffset;
    [RGroup("PerLightGroup"), Link("TextureProjection.ProjectionTexture")] public Texture2D ProjectionTexture;
}
