// <auto-generated>
// The engine's ToneMapMikeDayOperatorShader (ToneMapMikeDayOperatorShader.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// The tonemap operator from Mike Day, Insomniac Games.
/// </summary>
/// <remarks>
/// https://d3cw3dd2w32x2b.cloudfront.net/wp-content/uploads/2012/09/an-efficient-and-user-friendly-tone-mapping-operator.pdf
/// </remarks>
[Shader(External = true, Internal = true)]
public abstract partial class ToneMapMikeDayOperatorShader : ToneMapOperatorShader
{
    public float4 ToeCoeffs;
    public float4 ShoulderCoeffs;
    public float MiddleCrossOver;

    public virtual float Remap(float x)
    {
        float4 coeffs = (x < MiddleCrossOver) ? ToeCoeffs : ShoulderCoeffs;
        float2 fraction = coeffs.xy * x + coeffs.zw;
        return fraction.x / fraction.y;
    }

    public override float4 Compute(float4 color)
    {
        return new float4(Remap(color.r), Remap(color.g), Remap(color.b), color.a);
    }
}
