// <auto-generated>
// The declarations of the engine's ToneMapU2FilmicOperatorShader (ToneMapU2FilmicOperatorShader.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

/// <summary>
/// The U2Filmic tonemap operator.
/// </summary>
[Shader(External = true, Internal = true)]
public abstract partial class ToneMapU2FilmicOperatorShader : ToneMapOperatorShader
{
    public float ShoulderStrength;
    public float LinearStrength;
    public float LinearAngle;
    public float ToeStrength;
    public float ToeNumerator;
    public float ToeDenominator;
    public float LinearWhite;


    // Function used by the Uncharted2 tone mapping curve
    public virtual float3 U2Func(float3 x) => throw Gpu.Only;

    public override float4 Compute(float4 color) => throw Gpu.Only;
}
