// <auto-generated>
// The engine's TransformationInstancing (TransformationInstancing.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Tebjan Halm
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(Transformation))]
[Define("ModelTransformUsage", "0", If = "!defined(ModelTransformUsage)")]
public abstract partial class TransformationInstancing : TransformationBase
{
    public struct InstanceTransform
    {
        public float4x4 Matrix;
    }
    [RGroup("PerDraw.Instancing"), Stage] public StructuredBuffer<InstanceTransform> InstanceWorld;
    [RGroup("PerDraw.Instancing"), Stage] public StructuredBuffer<InstanceTransform> InstanceWorldInverse;

    public virtual float4x4 GetInstanceWorld(uint instanceId)
    {
        if (Sdsl.If("ModelTransformUsage == 0"))
        {
            return InstanceWorld[instanceId].Matrix;
        }
        else if (Sdsl.If("ModelTransformUsage == 1"))
        {
            return mul(Sdsl.Static<Transformation>().World, InstanceWorld[instanceId].Matrix);
        }
        else
        {
            return mul(InstanceWorld[instanceId].Matrix, Sdsl.Static<Transformation>().World);
        }
    }

    public virtual float4x4 GetInstanceWorldInverse(uint instanceId)
    {
        if (Sdsl.If("ModelTransformUsage == 0"))
        {
            return InstanceWorldInverse[instanceId].Matrix;
        }
        else if (Sdsl.If("ModelTransformUsage == 1"))
        {
            return mul(InstanceWorldInverse[instanceId].Matrix, Sdsl.Static<Transformation>().WorldInverse);
        }
        else
        {
            return mul(Sdsl.Static<Transformation>().WorldInverse, InstanceWorldInverse[instanceId].Matrix);
        }
    }
}
