// <auto-generated>
// The declarations of the engine's TransformationSkinningInstanced (TransformationSkinningInstanced.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Tebjan Halm
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(TransformationInstancing))]
public abstract partial class TransformationSkinningInstanced : TransformationSkinning
{
    [Stage(AfterOverride = true)]
    public override void PreTransformPosition() => throw Gpu.Only;
}
