// <auto-generated>
// The declarations of the engine's VoxelAttributeEmissionOpacityShader (VoxelAttributeEmissionOpacityShader.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Sean Boettger <sean@whypenguins.com>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Hlsl;
using static Csl.Hlsl.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(ShaderBaseStream))]
public abstract partial class VoxelAttributeEmissionOpacityShader : VoxelAttribute
{
    [Compose] public VoxelLayout_Float4 layout;

    public override void InitializeDummy() => throw Gpu.Only;

    public override void InitializeFromStreams() => throw Gpu.Only;

    public override void DirectWrite(uint3 address, uint strideIndex, uint stride) => throw Gpu.Only;

    public override void IndirectWrite(RWBuffer<uint> buffer, uint address) => throw Gpu.Only;

    public override void InitializeFromBuffer(RWBuffer<uint> buffer, uint address, uint2 base_stride) => throw Gpu.Only;

    public override float4 SampleLocal() => throw Gpu.Only;
}
