// <auto-generated>
// The declarations of the engine's VoxelVisualizationRawShader (VoxelVisualizationRawShader.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Sean Boettger <sean@whypenguins.com>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class VoxelVisualizationRawShader : ImageEffectShader
{
    [Compose] public IVoxelSampler Attribute;
    public float2 range;
    public float rangeOffset;
    public float mip;

    [Stage]
    public override float4 Shading() => throw Gpu.Only;
}
