// <auto-generated>
// The engine's Voxel2x2x2Mipmapper_AnisoXN (Voxel2x2x2Mipmapper_AnisoXN.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Sean Boettger <sean@whypenguins.com>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
public abstract partial class Voxel2x2x2Mipmapper_AnisoXN : Voxel2x2x2Mipmapper
{
    public virtual float4 blend(float4 s0, float4 s1)
    {
        return s0 * (1 - s1.a) + s1;
    }

    public override float4 Mipmap(float4 s000, float4 s100, float4 s110, float4 s101, float4 s011, float4 s010, float4 s001, float4 s111)
    {
        return (blend(s100, s000) + blend(s110, s010) + blend(s111, s011) + blend(s101, s001)) / 4;
    }
}
