// <auto-generated>
// The engine's VoxelAttributeEmissionOpacityShader (VoxelAttributeEmissionOpacityShader.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Sean Boettger <sean@whypenguins.com>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
[Mixin(typeof(ShaderBaseStream))]
public abstract partial class VoxelAttributeEmissionOpacityShader : VoxelAttribute
{
    [Compose] public VoxelLayout_Float4 layout;

    public override void InitializeDummy()
    {
        layout.InitializeDummy();
    }

    public override void InitializeFromStreams()
    {
        layout.InitializeFromStreams(streams.ColorTarget);
    }

    public override void DirectWrite(uint3 address, uint strideIndex, uint stride)
    {
        layout.DirectWrite(address, strideIndex, stride);
    }

    public override void IndirectWrite(RWBuffer<uint> buffer, uint address)
    {
        layout.IndirectWrite(buffer, address);
    }

    public override void InitializeFromBuffer(RWBuffer<uint> buffer, uint address, uint2 base_stride)
    {
        layout.InitializeFromBuffer(buffer, address);
    }

    public override float4 SampleLocal()
    {
        return layout.SampleLocal();
    }
}
