// <auto-generated>
// The engine's VoxelIsotropicWriter_Float4 (VoxelIsotropicWriter_Float4.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Sean Boettger <sean@whypenguins.com>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
public abstract partial class VoxelIsotropicWriter_Float4 : VoxelLayout_Float4
{
    [Stream] public float4 center;
    public RWTexture3D<float4> DirectOutput;
    [Compose] public VoxelFragmentPacker writer;

    public float maxBrightnessInv;

    [Compose] public VoxelModifierApplierIsotropic[] Modifiers;

    public override void InitializeDummy()
    {
        streams.center = new float4(0, 0, 0, 0);
    }

    public override void InitializeFromStreams(float4 original)
    {
        streams.center = original;
    }

    public override void DirectWrite(uint3 address, uint strideIndex, uint stride)
    {
        address.y += strideIndex * stride;
        float4 tempcenter = streams.center;
        foreach (var modifier in Modifiers)
        {
            modifier.Apply(ref tempcenter);
        }
        streams.center = tempcenter;

        DirectOutput[address] = new float4(streams.center.rgb * maxBrightnessInv, streams.center.a);
    }

    public override void IndirectWrite(RWBuffer<uint> buffer, uint address)
    {
        writer.Write(buffer, ref address, streams.center);
    }

    public override void InitializeFromBuffer(RWBuffer<uint> buffer, uint address)
    {
        writer.Read(buffer, ref address, out streams.center);
    }

    public override float4 SampleLocal()
    {
        return streams.center;
    }
}
