// <auto-generated>
// The engine's VoxelFragmentPackFloatR11G11B10 (VoxelFragmentPackFloatR11G11B10.sdsl, Stride 4.4.0-beta8), bodies included for the CPU, written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Sean Boettger <sean@whypenguins.com>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[System.Diagnostics.DebuggerNonUserCode]
[Mixin(typeof(DataPacking))]
public abstract partial class VoxelFragmentPackFloatR11G11B10 : VoxelFragmentPacker
{
    public override void Skip(ref uint address, float unpacked)
    {
        address += 1;
    }

    public override void Skip(ref uint address, float2 unpacked)
    {
        address += 1;
    }

    public override void Skip(ref uint address, float3 unpacked)
    {
        address += 1;
    }

    public override void Skip(ref uint address, float4 unpacked)
    {
        address += 2;
    }

    public override void Write(RWBuffer<uint> fragmentsBuffer, ref uint address, float3 unpacked)
    {
        writer.Write_Internal(fragmentsBuffer, ref address, Float3ToR11G11B10(unpacked));
    }

    public override void Read(RWBuffer<uint> fragmentsBuffer, ref uint address, out float3 unpacked)
    { Sdsl.Undefined(out unpacked);
        unpacked.rgb = R11G11B10ToFloat3(fragmentsBuffer[address]);
        address++;
    }


    //Until partial packing is implemented (if ever), write some halfs when not writing exactly 3 values
    //Otherwise many bits are wasted
    //Keep layout consistent though (or things like InterlockedMax can give unexpected results)
    public override void Write(RWBuffer<uint> fragmentsBuffer, ref uint address, float unpacked)
    {
        writer.Write_Internal(fragmentsBuffer, ref address, FloatToHalfFloat(unpacked.r));
    }

    public override void Write(RWBuffer<uint> fragmentsBuffer, ref uint address, float2 unpacked)
    {
        writer.Write_Internal(fragmentsBuffer, ref address, PackFloat2ToHalfFloat2(unpacked.rg));
    }

    public override void Write(RWBuffer<uint> fragmentsBuffer, ref uint address, float4 unpacked)
    {
        writer.Write_Internal(fragmentsBuffer, ref address, new uint2(Float3ToR11G11B10(unpacked.rgb), FloatToHalfFloat(unpacked.a)));
    }

    public override void Read(RWBuffer<uint> fragmentsBuffer, ref uint address, out float unpacked)
    {
        unpacked = HalfFloatToFloat(fragmentsBuffer[address]);
        address++;
    }

    public override void Read(RWBuffer<uint> fragmentsBuffer, ref uint address, out float2 unpacked)
    {
        unpacked = UnpackHalfFloat2ToFloat2(fragmentsBuffer[address]);
        address++;
    }

    public override void Read(RWBuffer<uint> fragmentsBuffer, ref uint address, out float4 unpacked)
    { Sdsl.Undefined(out unpacked);
        unpacked.rgb = R11G11B10ToFloat3(fragmentsBuffer[address]);
        address++;
        unpacked.a = HalfFloatToFloat(fragmentsBuffer[address]);
        address++;
    }
}
