// <auto-generated>
// The declarations of the engine's VoxelMarchCone (VoxelMarchCone.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Sean Boettger <sean@whypenguins.com>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
[Mixin(typeof(VoxelRadiusMarchMethod), typeof(MarchAttributes))]
[Define("sampleFunction", "Sample", If = "!defined(sampleFunction)")]
[Define("AttributeID", "0", If = "!defined(sampleFunction)")]
public abstract partial class VoxelMarchCone : VoxelMarchMethod
{
    [Generic] public static int steps;
    [Generic] public static float stepScale;
    [Generic] public static float coneRatio;
    [Generic] public static float offset;

    public override float4 March(float3 rayPos, float3 rayDir) => throw Gpu.Only;

    [Override]
    public virtual float4 MarchRadius(float3 rayPos, float3 rayDir, float radiusScale) => throw Gpu.Only;

    public override float StepSize() => throw Gpu.Only;

    [Override]
    public virtual float StepSizeRadius(float radiusScale) => throw Gpu.Only;
}
