// <auto-generated>
// The declarations of the engine's VoxelMarchMethod (VoxelMarchMethod.sdsl, Stride 4.4.0-beta8), written by csl engine. Do not edit: run it again.
// </auto-generated>
// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Sean Boettger <sean@whypenguins.com>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using Csl;
using Csl.Types;
using static Csl.Types.Intrinsics;

namespace Csl.Engine;

[Shader(External = true)]
public abstract partial class VoxelMarchMethod
{
    public virtual float4 March(float3 rayPos, float3 rayDir) => throw Gpu.Only;

    public virtual float StepSize() => throw Gpu.Only;
}
