using System.Reflection;
using Csl.Generators.Conversion;
using Csl.Tool;
using Csl.Generators.Sdsl.Syntax;
using Microsoft.CodeAnalysis;

// csl engine [--out DIR]
//   The C# of every engine shader, declarations only ([Shader(External = true)]), for Csl.Engine.
// csl convert FILE.sdsl... [--engine NAME,...] [--out DIR] [--namespace NS] [--declarations]
//   Shaders to C# [Shader] classes, bodies included, typed against Csl.Engine for the engine's.
//   --declarations writes [Shader(External = true)] classes instead: a project's .sdsl shaders
//   described for C# shaders to extend, the .sdsl staying the source.
//   --engine converts engine shaders by name, to modify them: a C# shader with the engine's name
//   replaces it once registered.
var command = args.Length > 0 ? args[0] : "help";
var rest = args.Skip(1).ToArray();
return command switch
{
    "engine" => Engine(rest),
    "convert" => Convert(rest),
    _ => Usage(),
};

static int Usage()
{
    Console.WriteLine("csl engine [--out DIR]                      C# declarations of the engine's shaders (Csl.Engine)");
    Console.WriteLine("csl convert FILE.sdsl... [--engine NAME,...] [--out DIR] [--namespace NS] [--declarations]");
    Console.WriteLine("                                            shaders to C# [Shader] classes, bodies included");
    Console.WriteLine("                                            (--declarations: external classes, to extend .sdsl shaders from C#)");
    return 2;
}

static string StrideVersion() => typeof(Program).Assembly.GetCustomAttributes<AssemblyMetadataAttribute>().First(a => a.Key == "StrideVersion").Value!;

static List<(string Path, string Text)> EngineFiles()
{
    var paths = EngineShaderFiles.Find(StrideVersion());
    if (paths.Count == 0)
        throw new InvalidOperationException("No engine shaders for Stride " + StrideVersion() + " under " + EngineShaderFiles.PackagesRoot + "; restore a project that references Stride.Engine " + StrideVersion() + " first.");
    return paths.Select(p => (p, File.ReadAllText(p))).ToList();
}

static List<MetadataReference> References(bool withEngine)
{
    var references = new List<MetadataReference>();
    foreach (var path in ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!).Split(Path.PathSeparator))
    {
        var name = Path.GetFileNameWithoutExtension(path);
        if (name.StartsWith("System", StringComparison.Ordinal) || name is "netstandard" or "mscorlib" or "Microsoft.CSharp")
            references.Add(MetadataReference.CreateFromFile(path));
    }
    references.Add(MetadataReference.CreateFromFile(typeof(Csl.ShaderAttribute).Assembly.Location));
    if (withEngine)
        references.Add(MetadataReference.CreateFromFile(Path.Combine(AppContext.BaseDirectory, "Csl.Engine.dll")));
    return references;
}

static int Engine(string[] args)
{
    var outDir = Path.Combine("src", "Csl.Engine", "Shaders");
    for (int i = 0; i < args.Length; i++)
        if (args[i] == "--out") outDir = args[++i];

    // With their bodies, for the CPU to run them (the GPU keeps the engine's .sdsl); the shaders whose
    // bodies do not convert are written as declarations, enough for C# shaders to inherit them.
    var files = EngineFiles();
    var withBodies = new ShaderConverterOptions();
    withBodies.References.AddRange(References(withEngine: false));
    withBodies.CSharp.External = true;
    withBodies.CSharp.Namespace = "Csl.Engine";
    var declarations = new ShaderConverterOptions();
    declarations.References.AddRange(References(withEngine: false));
    declarations.CSharp.DeclarationsOnly = true;
    declarations.CSharp.Namespace = "Csl.Engine";
    var full = ShaderConverter.Convert(files, withBodies).ToDictionary(r => r.Name, StringComparer.Ordinal);
    var results = ShaderConverter.Convert(files, declarations);

    Directory.CreateDirectory(outDir);
    foreach (var old in Directory.GetFiles(outDir, "*.cs"))
        File.Delete(old);
    int written = 0, bodies = 0;
    foreach (var declared in results)
    {
        // External: no SDSL is translated back, so no Sdsl to check; the C# compiling is what counts.
        var result = full.TryGetValue(declared.Name, out var converted) && converted.CSharp != null && converted.ConversionErrors.Count == 0 && converted.CompileErrors.Count == 0 ? converted : declared;
        // A shader whose declarations compile is written, even if its body would not convert: C# shaders
        // only need to inherit it.
        if (result.CSharp == null || result.CompileErrors.Count > 0)
        {
            Console.WriteLine($"skipped {result.Name}: {string.Join("; ", result.CompileErrors.Concat(result.ConversionErrors).Take(2))}");
            continue;
        }
        bool hasBodies = result == converted;
        var header = "// <auto-generated>\n// The engine's " + result.Name + " (" + Path.GetFileName(result.SourcePath) + ", Stride " + StrideVersion() + "), "
            + (hasBodies ? "bodies included for the CPU" : "declarations only: its bodies do not convert") + ", written by csl engine. Do not edit: run it again.\n// </auto-generated>\n";
        File.WriteAllText(Path.Combine(outDir, result.Name + ".cs"), header + result.CSharp);
        written++;
        if (hasBodies)
            bodies++;
    }
    Console.WriteLine($"{written} of {results.Count} engine shaders written to {outDir}, {bodies} with their bodies");
    return 0;
}

static int Convert(string[] args)
{
    string outDir = ".";
    string? ns = null;
    bool declarations = false;
    var files = new List<string>();
    var engineNames = new HashSet<string>(StringComparer.Ordinal);
    for (int i = 0; i < args.Length; i++)
    {
        switch (args[i])
        {
            case "--out": outDir = args[++i]; break;
            case "--namespace": ns = args[++i]; break;
            case "--declarations": declarations = true; break;
            case "--engine": foreach (var name in args[++i].Split(',')) engineNames.Add(name.Trim()); break;
            default: files.Add(args[i]); break;
        }
    }
    if (files.Count == 0 && engineNames.Count == 0)
        return Usage();

    var engine = EngineFiles();
    var inputs = files.Select(f => (Path: Path.GetFullPath(f), Text: File.ReadAllText(f))).ToList();
    foreach (var (path, text) in engine)
    {
        var unit = SdslSyntaxParser.Parse(path, text);
        if (unit.Shaders().Any(s => engineNames.Remove(s.Name)))
            inputs.Add((path, text));
    }
    if (engineNames.Count > 0)
    {
        Console.Error.WriteLine("No engine shader named " + string.Join(", ", engineNames));
        return 1;
    }

    var options = new ShaderConverterOptions();
    options.References.AddRange(References(withEngine: true));
    options.CSharp.Namespace = ns;
    options.CSharp.DeclarationsOnly = declarations;
    options.CSharp.Usings.Add("Csl.Engine");
    foreach (var (path, text) in engine)
        options.KnownShaders.Add(SdslSyntaxParser.Parse(path, text));
    var results = ShaderConverter.Convert(inputs, options);

    Directory.CreateDirectory(outDir);
    int failures = 0;
    foreach (var result in results)
    {
        if (result.CSharp != null)
        {
            var path = Path.Combine(outDir, result.Name + ".cs");
            File.WriteAllText(path, result.CSharp);
            Console.WriteLine($"{result.Name} -> {path}" + (result.Fixes > 0 ? $" ({result.Fixes} implicit conversions made explicit)" : string.Empty));
        }
        foreach (var error in result.ConversionErrors.Concat(result.CompileErrors).Concat(result.TranslationErrors))
        {
            Console.Error.WriteLine($"{result.Name}: {error}");
            failures++;
        }
    }
    return failures == 0 ? 0 : 1;
}
