// <auto-generated>
// Written by tools/gen_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591, CS0660, CS0661
using System;
using System.Runtime.InteropServices;

namespace Csl.Types;

/// <summary>HLSL half4x4: 4 rows of half4, indexed m[row][column].</summary>
[StructLayout(LayoutKind.Sequential)]
[System.Diagnostics.DebuggerNonUserCode]
public struct half4x4
{
    public half4 r0, r1, r2, r3;
    public half4x4(half4 r0, half4 r1, half4 r2, half4 r3) { this.r0 = r0; this.r1 = r1; this.r2 = r2; this.r3 = r3; }
    public half4x4(half m00, half m01, half m02, half m03, half m10, half m11, half m12, half m13, half m20, half m21, half m22, half m23, half m30, half m31, half m32, half m33) { r0 = new half4(m00, m01, m02, m03); r1 = new half4(m10, m11, m12, m13); r2 = new half4(m20, m21, m22, m23); r3 = new half4(m30, m31, m32, m33); }
    public half4x4(half v) { r0 = v; r1 = v; r2 = v; r3 = v; }
    public static implicit operator half4x4(half v) => new half4x4(v);
    public half4 this[int i]
    {
        readonly get => i switch { 0 => r0, 1 => r1, 2 => r2, 3 => r3, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: r0 = value; break; case 1: r1 = value; break; case 2: r2 = value; break; case 3: r3 = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public half4 this[uint i] { readonly get => this[(int)i]; set => this[(int)i] = value; }
    public half _m00 { readonly get => r0.x; set => r0.x = value; }
    public half _11 { readonly get => r0.x; set => r0.x = value; }
    public half _m01 { readonly get => r0.y; set => r0.y = value; }
    public half _12 { readonly get => r0.y; set => r0.y = value; }
    public half _m02 { readonly get => r0.z; set => r0.z = value; }
    public half _13 { readonly get => r0.z; set => r0.z = value; }
    public half _m03 { readonly get => r0.w; set => r0.w = value; }
    public half _14 { readonly get => r0.w; set => r0.w = value; }
    public half _m10 { readonly get => r1.x; set => r1.x = value; }
    public half _21 { readonly get => r1.x; set => r1.x = value; }
    public half _m11 { readonly get => r1.y; set => r1.y = value; }
    public half _22 { readonly get => r1.y; set => r1.y = value; }
    public half _m12 { readonly get => r1.z; set => r1.z = value; }
    public half _23 { readonly get => r1.z; set => r1.z = value; }
    public half _m13 { readonly get => r1.w; set => r1.w = value; }
    public half _24 { readonly get => r1.w; set => r1.w = value; }
    public half _m20 { readonly get => r2.x; set => r2.x = value; }
    public half _31 { readonly get => r2.x; set => r2.x = value; }
    public half _m21 { readonly get => r2.y; set => r2.y = value; }
    public half _32 { readonly get => r2.y; set => r2.y = value; }
    public half _m22 { readonly get => r2.z; set => r2.z = value; }
    public half _33 { readonly get => r2.z; set => r2.z = value; }
    public half _m23 { readonly get => r2.w; set => r2.w = value; }
    public half _34 { readonly get => r2.w; set => r2.w = value; }
    public half _m30 { readonly get => r3.x; set => r3.x = value; }
    public half _41 { readonly get => r3.x; set => r3.x = value; }
    public half _m31 { readonly get => r3.y; set => r3.y = value; }
    public half _42 { readonly get => r3.y; set => r3.y = value; }
    public half _m32 { readonly get => r3.z; set => r3.z = value; }
    public half _43 { readonly get => r3.z; set => r3.z = value; }
    public half _m33 { readonly get => r3.w; set => r3.w = value; }
    public half _44 { readonly get => r3.w; set => r3.w = value; }
    public static explicit operator half4x4(float4x4 v) => new half4x4((half4)v.r0, (half4)v.r1, (half4)v.r2, (half4)v.r3);
    public static explicit operator half4x4(int4x4 v) => new half4x4((half4)v.r0, (half4)v.r1, (half4)v.r2, (half4)v.r3);
    public static explicit operator half4x4(uint4x4 v) => new half4x4((half4)v.r0, (half4)v.r1, (half4)v.r2, (half4)v.r3);
    public static explicit operator half4x4(bool4x4 v) => new half4x4((half4)v.r0, (half4)v.r1, (half4)v.r2, (half4)v.r3);
    public static half4x4 operator +(half4x4 a, half4x4 b) => new half4x4(a.r0 + b.r0, a.r1 + b.r1, a.r2 + b.r2, a.r3 + b.r3);
    public static half4x4 operator +(half4x4 a, half b) => new half4x4(a.r0 + b, a.r1 + b, a.r2 + b, a.r3 + b);
    public static half4x4 operator +(half a, half4x4 b) => new half4x4(a + b.r0, a + b.r1, a + b.r2, a + b.r3);
    public static half4x4 operator -(half4x4 a, half4x4 b) => new half4x4(a.r0 - b.r0, a.r1 - b.r1, a.r2 - b.r2, a.r3 - b.r3);
    public static half4x4 operator -(half4x4 a, half b) => new half4x4(a.r0 - b, a.r1 - b, a.r2 - b, a.r3 - b);
    public static half4x4 operator -(half a, half4x4 b) => new half4x4(a - b.r0, a - b.r1, a - b.r2, a - b.r3);
    public static half4x4 operator *(half4x4 a, half4x4 b) => new half4x4(a.r0 * b.r0, a.r1 * b.r1, a.r2 * b.r2, a.r3 * b.r3);
    public static half4x4 operator *(half4x4 a, half b) => new half4x4(a.r0 * b, a.r1 * b, a.r2 * b, a.r3 * b);
    public static half4x4 operator *(half a, half4x4 b) => new half4x4(a * b.r0, a * b.r1, a * b.r2, a * b.r3);
    public static half4x4 operator /(half4x4 a, half4x4 b) => new half4x4(a.r0 / b.r0, a.r1 / b.r1, a.r2 / b.r2, a.r3 / b.r3);
    public static half4x4 operator /(half4x4 a, half b) => new half4x4(a.r0 / b, a.r1 / b, a.r2 / b, a.r3 / b);
    public static half4x4 operator /(half a, half4x4 b) => new half4x4(a / b.r0, a / b.r1, a / b.r2, a / b.r3);
    public static half4x4 operator %(half4x4 a, half4x4 b) => new half4x4(a.r0 % b.r0, a.r1 % b.r1, a.r2 % b.r2, a.r3 % b.r3);
    public static half4x4 operator %(half4x4 a, half b) => new half4x4(a.r0 % b, a.r1 % b, a.r2 % b, a.r3 % b);
    public static half4x4 operator %(half a, half4x4 b) => new half4x4(a % b.r0, a % b.r1, a % b.r2, a % b.r3);
    public static half4x4 operator -(half4x4 a) => new half4x4(-a.r0, -a.r1, -a.r2, -a.r3);
}
