// <auto-generated>
// Written by tools/gen_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591, CS0660, CS0661
using System;
using System.Runtime.InteropServices;

namespace Csl.Types;

/// <summary>HLSL int4: 4 components of int.</summary>
[StructLayout(LayoutKind.Sequential)]
[System.Diagnostics.DebuggerNonUserCode]
public struct int4 : IEquatable<int4>
{
    public int x, y, z, w;
    public int4(int x, int y, int z, int w) { this.x = x; this.y = y; this.z = z; this.w = w; }
    public int4(int v) { x = v; y = v; z = v; w = v; }
    public int4(int p0, int p1, int2 p2) { x = p0; y = p1; z = p2.x; w = p2.y; }
    public int4(int p0, int2 p1, int p2) { x = p0; y = p1.x; z = p1.y; w = p2; }
    public int4(int p0, int3 p1) { x = p0; y = p1.x; z = p1.y; w = p1.z; }
    public int4(int2 p0, int p1, int p2) { x = p0.x; y = p0.y; z = p1; w = p2; }
    public int4(int2 p0, int2 p1) { x = p0.x; y = p0.y; z = p1.x; w = p1.y; }
    public int4(int3 p0, int p1) { x = p0.x; y = p0.y; z = p0.z; w = p1; }
    public int4(double v) { x = (int)v; y = (int)v; z = (int)v; w = (int)v; }
    public int4(int4 v) { x = v.x; y = v.y; z = v.z; w = v.w; }
    public int4(double p0, double p1, double p2, double p3) { x = (int)p0; y = (int)p1; z = (int)p2; w = (int)p3; }
    public int4(double p0, double p1, uint2 p2) { x = (int)p0; y = (int)p1; z = (int)p2.x; w = (int)p2.y; }
    public int4(double p0, double p1, half2 p2) { x = (int)p0; y = (int)p1; z = (int)(float)p2.x; w = (int)(float)p2.y; }
    public int4(double p0, double p1, float2 p2) { x = (int)p0; y = (int)p1; z = (int)p2.x; w = (int)p2.y; }
    public int4(double p0, double p1, double2 p2) { x = (int)p0; y = (int)p1; z = (int)p2.x; w = (int)p2.y; }
    public int4(double p0, uint2 p1, double p2) { x = (int)p0; y = (int)p1.x; z = (int)p1.y; w = (int)p2; }
    public int4(double p0, half2 p1, double p2) { x = (int)p0; y = (int)(float)p1.x; z = (int)(float)p1.y; w = (int)p2; }
    public int4(double p0, float2 p1, double p2) { x = (int)p0; y = (int)p1.x; z = (int)p1.y; w = (int)p2; }
    public int4(double p0, double2 p1, double p2) { x = (int)p0; y = (int)p1.x; z = (int)p1.y; w = (int)p2; }
    public int4(double p0, uint3 p1) { x = (int)p0; y = (int)p1.x; z = (int)p1.y; w = (int)p1.z; }
    public int4(double p0, half3 p1) { x = (int)p0; y = (int)(float)p1.x; z = (int)(float)p1.y; w = (int)(float)p1.z; }
    public int4(double p0, float3 p1) { x = (int)p0; y = (int)p1.x; z = (int)p1.y; w = (int)p1.z; }
    public int4(double p0, double3 p1) { x = (int)p0; y = (int)p1.x; z = (int)p1.y; w = (int)p1.z; }
    public int4(uint2 p0, double p1, double p2) { x = (int)p0.x; y = (int)p0.y; z = (int)p1; w = (int)p2; }
    public int4(half2 p0, double p1, double p2) { x = (int)(float)p0.x; y = (int)(float)p0.y; z = (int)p1; w = (int)p2; }
    public int4(float2 p0, double p1, double p2) { x = (int)p0.x; y = (int)p0.y; z = (int)p1; w = (int)p2; }
    public int4(double2 p0, double p1, double p2) { x = (int)p0.x; y = (int)p0.y; z = (int)p1; w = (int)p2; }
    public int4(uint2 p0, uint2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(uint2 p0, half2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)(float)p1.x; w = (int)(float)p1.y; }
    public int4(uint2 p0, float2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(uint2 p0, double2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(half2 p0, uint2 p1) { x = (int)(float)p0.x; y = (int)(float)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(half2 p0, half2 p1) { x = (int)(float)p0.x; y = (int)(float)p0.y; z = (int)(float)p1.x; w = (int)(float)p1.y; }
    public int4(half2 p0, float2 p1) { x = (int)(float)p0.x; y = (int)(float)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(half2 p0, double2 p1) { x = (int)(float)p0.x; y = (int)(float)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(float2 p0, uint2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(float2 p0, half2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)(float)p1.x; w = (int)(float)p1.y; }
    public int4(float2 p0, float2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(float2 p0, double2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(double2 p0, uint2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(double2 p0, half2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)(float)p1.x; w = (int)(float)p1.y; }
    public int4(double2 p0, float2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(double2 p0, double2 p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p1.x; w = (int)p1.y; }
    public int4(uint3 p0, double p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p0.z; w = (int)p1; }
    public int4(half3 p0, double p1) { x = (int)(float)p0.x; y = (int)(float)p0.y; z = (int)(float)p0.z; w = (int)p1; }
    public int4(float3 p0, double p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p0.z; w = (int)p1; }
    public int4(double3 p0, double p1) { x = (int)p0.x; y = (int)p0.y; z = (int)p0.z; w = (int)p1; }
    public int4(uint4 p0) { x = (int)p0.x; y = (int)p0.y; z = (int)p0.z; w = (int)p0.w; }
    public int4(half4 p0) { x = (int)(float)p0.x; y = (int)(float)p0.y; z = (int)(float)p0.z; w = (int)(float)p0.w; }
    public int4(float4 p0) { x = (int)p0.x; y = (int)p0.y; z = (int)p0.z; w = (int)p0.w; }
    public int4(double4 p0) { x = (int)p0.x; y = (int)p0.y; z = (int)p0.z; w = (int)p0.w; }
    public static implicit operator int4(int v) => new int4(v);
    public static implicit operator int4(bool4 v) => new int4((v.x ? 1 : 0), (v.y ? 1 : 0), (v.z ? 1 : 0), (v.w ? 1 : 0));
    public static explicit operator int4(uint4 v) => new int4((int)v.x, (int)v.y, (int)v.z, (int)v.w);
    public static explicit operator int4(half4 v) => new int4((int)(float)v.x, (int)(float)v.y, (int)(float)v.z, (int)(float)v.w);
    public static explicit operator int4(float4 v) => new int4((int)v.x, (int)v.y, (int)v.z, (int)v.w);
    public static explicit operator int4(double4 v) => new int4((int)v.x, (int)v.y, (int)v.z, (int)v.w);
    public static explicit operator bool(int4 v) => (v.x != 0);
    public static explicit operator int(int4 v) => v.x;
    public static explicit operator uint(int4 v) => (uint)v.x;
    public static explicit operator half(int4 v) => (half)(float)v.x;
    public static explicit operator float(int4 v) => (float)v.x;
    public static explicit operator double(int4 v) => (double)v.x;
    public int this[int i]
    {
        get => i switch { 0 => x, 1 => y, 2 => z, 3 => w, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; case 3: w = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public int this[uint i] { get => this[(int)i]; set => this[(int)i] = value; }
    public static int4 operator +(int4 a, int4 b) => new int4((int)(a.x + b.x), (int)(a.y + b.y), (int)(a.z + b.z), (int)(a.w + b.w));
    public static int4 operator +(int4 a, int b) => new int4((int)(a.x + b), (int)(a.y + b), (int)(a.z + b), (int)(a.w + b));
    public static int4 operator +(int a, int4 b) => new int4((int)(a + b.x), (int)(a + b.y), (int)(a + b.z), (int)(a + b.w));
    public static int4 operator -(int4 a, int4 b) => new int4((int)(a.x - b.x), (int)(a.y - b.y), (int)(a.z - b.z), (int)(a.w - b.w));
    public static int4 operator -(int4 a, int b) => new int4((int)(a.x - b), (int)(a.y - b), (int)(a.z - b), (int)(a.w - b));
    public static int4 operator -(int a, int4 b) => new int4((int)(a - b.x), (int)(a - b.y), (int)(a - b.z), (int)(a - b.w));
    public static int4 operator *(int4 a, int4 b) => new int4((int)(a.x * b.x), (int)(a.y * b.y), (int)(a.z * b.z), (int)(a.w * b.w));
    public static int4 operator *(int4 a, int b) => new int4((int)(a.x * b), (int)(a.y * b), (int)(a.z * b), (int)(a.w * b));
    public static int4 operator *(int a, int4 b) => new int4((int)(a * b.x), (int)(a * b.y), (int)(a * b.z), (int)(a * b.w));
    public static int4 operator /(int4 a, int4 b) => new int4((int)(a.x / b.x), (int)(a.y / b.y), (int)(a.z / b.z), (int)(a.w / b.w));
    public static int4 operator /(int4 a, int b) => new int4((int)(a.x / b), (int)(a.y / b), (int)(a.z / b), (int)(a.w / b));
    public static int4 operator /(int a, int4 b) => new int4((int)(a / b.x), (int)(a / b.y), (int)(a / b.z), (int)(a / b.w));
    public static int4 operator %(int4 a, int4 b) => new int4((int)(a.x % b.x), (int)(a.y % b.y), (int)(a.z % b.z), (int)(a.w % b.w));
    public static int4 operator %(int4 a, int b) => new int4((int)(a.x % b), (int)(a.y % b), (int)(a.z % b), (int)(a.w % b));
    public static int4 operator %(int a, int4 b) => new int4((int)(a % b.x), (int)(a % b.y), (int)(a % b.z), (int)(a % b.w));
    public static int4 operator -(int4 a) => new int4((int)(-a.x), (int)(-a.y), (int)(-a.z), (int)(-a.w));
    public static int4 operator +(int4 a) => a;
    public static int4 operator ++(int4 a) => a + 1;
    public static int4 operator --(int4 a) => a - 1;
    public static bool4 operator <(int4 a, int4 b) => new bool4(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
    public static bool4 operator <(int4 a, int b) => new bool4(a.x < b, a.y < b, a.z < b, a.w < b);
    public static bool4 operator <(int a, int4 b) => new bool4(a < b.x, a < b.y, a < b.z, a < b.w);
    public static bool4 operator >(int4 a, int4 b) => new bool4(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
    public static bool4 operator >(int4 a, int b) => new bool4(a.x > b, a.y > b, a.z > b, a.w > b);
    public static bool4 operator >(int a, int4 b) => new bool4(a > b.x, a > b.y, a > b.z, a > b.w);
    public static bool4 operator <=(int4 a, int4 b) => new bool4(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
    public static bool4 operator <=(int4 a, int b) => new bool4(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
    public static bool4 operator <=(int a, int4 b) => new bool4(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
    public static bool4 operator >=(int4 a, int4 b) => new bool4(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
    public static bool4 operator >=(int4 a, int b) => new bool4(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
    public static bool4 operator >=(int a, int4 b) => new bool4(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
    public static int4 operator &(int4 a, int4 b) => new int4((int)(a.x & b.x), (int)(a.y & b.y), (int)(a.z & b.z), (int)(a.w & b.w));
    public static int4 operator &(int4 a, int b) => new int4((int)(a.x & b), (int)(a.y & b), (int)(a.z & b), (int)(a.w & b));
    public static int4 operator &(int a, int4 b) => new int4((int)(a & b.x), (int)(a & b.y), (int)(a & b.z), (int)(a & b.w));
    public static int4 operator |(int4 a, int4 b) => new int4((int)(a.x | b.x), (int)(a.y | b.y), (int)(a.z | b.z), (int)(a.w | b.w));
    public static int4 operator |(int4 a, int b) => new int4((int)(a.x | b), (int)(a.y | b), (int)(a.z | b), (int)(a.w | b));
    public static int4 operator |(int a, int4 b) => new int4((int)(a | b.x), (int)(a | b.y), (int)(a | b.z), (int)(a | b.w));
    public static int4 operator ^(int4 a, int4 b) => new int4((int)(a.x ^ b.x), (int)(a.y ^ b.y), (int)(a.z ^ b.z), (int)(a.w ^ b.w));
    public static int4 operator ^(int4 a, int b) => new int4((int)(a.x ^ b), (int)(a.y ^ b), (int)(a.z ^ b), (int)(a.w ^ b));
    public static int4 operator ^(int a, int4 b) => new int4((int)(a ^ b.x), (int)(a ^ b.y), (int)(a ^ b.z), (int)(a ^ b.w));
    public static int4 operator <<(int4 a, int b) => new int4((int)(a.x << b), (int)(a.y << b), (int)(a.z << b), (int)(a.w << b));
    public static int4 operator <<(int4 a, int4 b) => new int4((int)(a.x << b.x), (int)(a.y << b.y), (int)(a.z << b.z), (int)(a.w << b.w));
    public static int4 operator >>(int4 a, int b) => new int4((int)(a.x >> b), (int)(a.y >> b), (int)(a.z >> b), (int)(a.w >> b));
    public static int4 operator >>(int4 a, int4 b) => new int4((int)(a.x >> b.x), (int)(a.y >> b.y), (int)(a.z >> b.z), (int)(a.w >> b.w));
    public static int4 operator ~(int4 a) => new int4((int)(~a.x), (int)(~a.y), (int)(~a.z), (int)(~a.w));
    public static bool4 operator ==(int4 a, int4 b) => new bool4(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
    public static bool4 operator !=(int4 a, int4 b) => new bool4(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
    public static bool4 operator ==(int4 a, int b) => new bool4(a.x == b, a.y == b, a.z == b, a.w == b);
    public static bool4 operator !=(int4 a, int b) => new bool4(a.x != b, a.y != b, a.z != b, a.w != b);
    public bool Equals(int4 other) => x.Equals(other.x) && y.Equals(other.y) && z.Equals(other.z) && w.Equals(other.w);
    public override bool Equals(object? obj) => obj is int4 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y, z, w);
    public override string ToString() => $"int4({x}, {y}, {z}, {w})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public readonly int2 xx => new int2(x, x);
    public int2 xy { readonly get => new int2(x, y); set { x = value.x; y = value.y; } }
    public int2 xz { readonly get => new int2(x, z); set { x = value.x; z = value.y; } }
    public int2 xw { readonly get => new int2(x, w); set { x = value.x; w = value.y; } }
    public int2 yx { readonly get => new int2(y, x); set { y = value.x; x = value.y; } }
    public readonly int2 yy => new int2(y, y);
    public int2 yz { readonly get => new int2(y, z); set { y = value.x; z = value.y; } }
    public int2 yw { readonly get => new int2(y, w); set { y = value.x; w = value.y; } }
    public int2 zx { readonly get => new int2(z, x); set { z = value.x; x = value.y; } }
    public int2 zy { readonly get => new int2(z, y); set { z = value.x; y = value.y; } }
    public readonly int2 zz => new int2(z, z);
    public int2 zw { readonly get => new int2(z, w); set { z = value.x; w = value.y; } }
    public int2 wx { readonly get => new int2(w, x); set { w = value.x; x = value.y; } }
    public int2 wy { readonly get => new int2(w, y); set { w = value.x; y = value.y; } }
    public int2 wz { readonly get => new int2(w, z); set { w = value.x; z = value.y; } }
    public readonly int2 ww => new int2(w, w);
    public readonly int3 xxx => new int3(x, x, x);
    public readonly int3 xxy => new int3(x, x, y);
    public readonly int3 xxz => new int3(x, x, z);
    public readonly int3 xxw => new int3(x, x, w);
    public readonly int3 xyx => new int3(x, y, x);
    public readonly int3 xyy => new int3(x, y, y);
    public int3 xyz { readonly get => new int3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public int3 xyw { readonly get => new int3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
    public readonly int3 xzx => new int3(x, z, x);
    public int3 xzy { readonly get => new int3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public readonly int3 xzz => new int3(x, z, z);
    public int3 xzw { readonly get => new int3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
    public readonly int3 xwx => new int3(x, w, x);
    public int3 xwy { readonly get => new int3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
    public int3 xwz { readonly get => new int3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
    public readonly int3 xww => new int3(x, w, w);
    public readonly int3 yxx => new int3(y, x, x);
    public readonly int3 yxy => new int3(y, x, y);
    public int3 yxz { readonly get => new int3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public int3 yxw { readonly get => new int3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
    public readonly int3 yyx => new int3(y, y, x);
    public readonly int3 yyy => new int3(y, y, y);
    public readonly int3 yyz => new int3(y, y, z);
    public readonly int3 yyw => new int3(y, y, w);
    public int3 yzx { readonly get => new int3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public readonly int3 yzy => new int3(y, z, y);
    public readonly int3 yzz => new int3(y, z, z);
    public int3 yzw { readonly get => new int3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
    public int3 ywx { readonly get => new int3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
    public readonly int3 ywy => new int3(y, w, y);
    public int3 ywz { readonly get => new int3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
    public readonly int3 yww => new int3(y, w, w);
    public readonly int3 zxx => new int3(z, x, x);
    public int3 zxy { readonly get => new int3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public readonly int3 zxz => new int3(z, x, z);
    public int3 zxw { readonly get => new int3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
    public int3 zyx { readonly get => new int3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public readonly int3 zyy => new int3(z, y, y);
    public readonly int3 zyz => new int3(z, y, z);
    public int3 zyw { readonly get => new int3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
    public readonly int3 zzx => new int3(z, z, x);
    public readonly int3 zzy => new int3(z, z, y);
    public readonly int3 zzz => new int3(z, z, z);
    public readonly int3 zzw => new int3(z, z, w);
    public int3 zwx { readonly get => new int3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
    public int3 zwy { readonly get => new int3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
    public readonly int3 zwz => new int3(z, w, z);
    public readonly int3 zww => new int3(z, w, w);
    public readonly int3 wxx => new int3(w, x, x);
    public int3 wxy { readonly get => new int3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
    public int3 wxz { readonly get => new int3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
    public readonly int3 wxw => new int3(w, x, w);
    public int3 wyx { readonly get => new int3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
    public readonly int3 wyy => new int3(w, y, y);
    public int3 wyz { readonly get => new int3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
    public readonly int3 wyw => new int3(w, y, w);
    public int3 wzx { readonly get => new int3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
    public int3 wzy { readonly get => new int3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
    public readonly int3 wzz => new int3(w, z, z);
    public readonly int3 wzw => new int3(w, z, w);
    public readonly int3 wwx => new int3(w, w, x);
    public readonly int3 wwy => new int3(w, w, y);
    public readonly int3 wwz => new int3(w, w, z);
    public readonly int3 www => new int3(w, w, w);
    public readonly int4 xxxx => new int4(x, x, x, x);
    public readonly int4 xxxy => new int4(x, x, x, y);
    public readonly int4 xxxz => new int4(x, x, x, z);
    public readonly int4 xxxw => new int4(x, x, x, w);
    public readonly int4 xxyx => new int4(x, x, y, x);
    public readonly int4 xxyy => new int4(x, x, y, y);
    public readonly int4 xxyz => new int4(x, x, y, z);
    public readonly int4 xxyw => new int4(x, x, y, w);
    public readonly int4 xxzx => new int4(x, x, z, x);
    public readonly int4 xxzy => new int4(x, x, z, y);
    public readonly int4 xxzz => new int4(x, x, z, z);
    public readonly int4 xxzw => new int4(x, x, z, w);
    public readonly int4 xxwx => new int4(x, x, w, x);
    public readonly int4 xxwy => new int4(x, x, w, y);
    public readonly int4 xxwz => new int4(x, x, w, z);
    public readonly int4 xxww => new int4(x, x, w, w);
    public readonly int4 xyxx => new int4(x, y, x, x);
    public readonly int4 xyxy => new int4(x, y, x, y);
    public readonly int4 xyxz => new int4(x, y, x, z);
    public readonly int4 xyxw => new int4(x, y, x, w);
    public readonly int4 xyyx => new int4(x, y, y, x);
    public readonly int4 xyyy => new int4(x, y, y, y);
    public readonly int4 xyyz => new int4(x, y, y, z);
    public readonly int4 xyyw => new int4(x, y, y, w);
    public readonly int4 xyzx => new int4(x, y, z, x);
    public readonly int4 xyzy => new int4(x, y, z, y);
    public readonly int4 xyzz => new int4(x, y, z, z);
    public int4 xyzw { readonly get => new int4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
    public readonly int4 xywx => new int4(x, y, w, x);
    public readonly int4 xywy => new int4(x, y, w, y);
    public int4 xywz { readonly get => new int4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
    public readonly int4 xyww => new int4(x, y, w, w);
    public readonly int4 xzxx => new int4(x, z, x, x);
    public readonly int4 xzxy => new int4(x, z, x, y);
    public readonly int4 xzxz => new int4(x, z, x, z);
    public readonly int4 xzxw => new int4(x, z, x, w);
    public readonly int4 xzyx => new int4(x, z, y, x);
    public readonly int4 xzyy => new int4(x, z, y, y);
    public readonly int4 xzyz => new int4(x, z, y, z);
    public int4 xzyw { readonly get => new int4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
    public readonly int4 xzzx => new int4(x, z, z, x);
    public readonly int4 xzzy => new int4(x, z, z, y);
    public readonly int4 xzzz => new int4(x, z, z, z);
    public readonly int4 xzzw => new int4(x, z, z, w);
    public readonly int4 xzwx => new int4(x, z, w, x);
    public int4 xzwy { readonly get => new int4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
    public readonly int4 xzwz => new int4(x, z, w, z);
    public readonly int4 xzww => new int4(x, z, w, w);
    public readonly int4 xwxx => new int4(x, w, x, x);
    public readonly int4 xwxy => new int4(x, w, x, y);
    public readonly int4 xwxz => new int4(x, w, x, z);
    public readonly int4 xwxw => new int4(x, w, x, w);
    public readonly int4 xwyx => new int4(x, w, y, x);
    public readonly int4 xwyy => new int4(x, w, y, y);
    public int4 xwyz { readonly get => new int4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
    public readonly int4 xwyw => new int4(x, w, y, w);
    public readonly int4 xwzx => new int4(x, w, z, x);
    public int4 xwzy { readonly get => new int4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
    public readonly int4 xwzz => new int4(x, w, z, z);
    public readonly int4 xwzw => new int4(x, w, z, w);
    public readonly int4 xwwx => new int4(x, w, w, x);
    public readonly int4 xwwy => new int4(x, w, w, y);
    public readonly int4 xwwz => new int4(x, w, w, z);
    public readonly int4 xwww => new int4(x, w, w, w);
    public readonly int4 yxxx => new int4(y, x, x, x);
    public readonly int4 yxxy => new int4(y, x, x, y);
    public readonly int4 yxxz => new int4(y, x, x, z);
    public readonly int4 yxxw => new int4(y, x, x, w);
    public readonly int4 yxyx => new int4(y, x, y, x);
    public readonly int4 yxyy => new int4(y, x, y, y);
    public readonly int4 yxyz => new int4(y, x, y, z);
    public readonly int4 yxyw => new int4(y, x, y, w);
    public readonly int4 yxzx => new int4(y, x, z, x);
    public readonly int4 yxzy => new int4(y, x, z, y);
    public readonly int4 yxzz => new int4(y, x, z, z);
    public int4 yxzw { readonly get => new int4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
    public readonly int4 yxwx => new int4(y, x, w, x);
    public readonly int4 yxwy => new int4(y, x, w, y);
    public int4 yxwz { readonly get => new int4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
    public readonly int4 yxww => new int4(y, x, w, w);
    public readonly int4 yyxx => new int4(y, y, x, x);
    public readonly int4 yyxy => new int4(y, y, x, y);
    public readonly int4 yyxz => new int4(y, y, x, z);
    public readonly int4 yyxw => new int4(y, y, x, w);
    public readonly int4 yyyx => new int4(y, y, y, x);
    public readonly int4 yyyy => new int4(y, y, y, y);
    public readonly int4 yyyz => new int4(y, y, y, z);
    public readonly int4 yyyw => new int4(y, y, y, w);
    public readonly int4 yyzx => new int4(y, y, z, x);
    public readonly int4 yyzy => new int4(y, y, z, y);
    public readonly int4 yyzz => new int4(y, y, z, z);
    public readonly int4 yyzw => new int4(y, y, z, w);
    public readonly int4 yywx => new int4(y, y, w, x);
    public readonly int4 yywy => new int4(y, y, w, y);
    public readonly int4 yywz => new int4(y, y, w, z);
    public readonly int4 yyww => new int4(y, y, w, w);
    public readonly int4 yzxx => new int4(y, z, x, x);
    public readonly int4 yzxy => new int4(y, z, x, y);
    public readonly int4 yzxz => new int4(y, z, x, z);
    public int4 yzxw { readonly get => new int4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
    public readonly int4 yzyx => new int4(y, z, y, x);
    public readonly int4 yzyy => new int4(y, z, y, y);
    public readonly int4 yzyz => new int4(y, z, y, z);
    public readonly int4 yzyw => new int4(y, z, y, w);
    public readonly int4 yzzx => new int4(y, z, z, x);
    public readonly int4 yzzy => new int4(y, z, z, y);
    public readonly int4 yzzz => new int4(y, z, z, z);
    public readonly int4 yzzw => new int4(y, z, z, w);
    public int4 yzwx { readonly get => new int4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
    public readonly int4 yzwy => new int4(y, z, w, y);
    public readonly int4 yzwz => new int4(y, z, w, z);
    public readonly int4 yzww => new int4(y, z, w, w);
    public readonly int4 ywxx => new int4(y, w, x, x);
    public readonly int4 ywxy => new int4(y, w, x, y);
    public int4 ywxz { readonly get => new int4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
    public readonly int4 ywxw => new int4(y, w, x, w);
    public readonly int4 ywyx => new int4(y, w, y, x);
    public readonly int4 ywyy => new int4(y, w, y, y);
    public readonly int4 ywyz => new int4(y, w, y, z);
    public readonly int4 ywyw => new int4(y, w, y, w);
    public int4 ywzx { readonly get => new int4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
    public readonly int4 ywzy => new int4(y, w, z, y);
    public readonly int4 ywzz => new int4(y, w, z, z);
    public readonly int4 ywzw => new int4(y, w, z, w);
    public readonly int4 ywwx => new int4(y, w, w, x);
    public readonly int4 ywwy => new int4(y, w, w, y);
    public readonly int4 ywwz => new int4(y, w, w, z);
    public readonly int4 ywww => new int4(y, w, w, w);
    public readonly int4 zxxx => new int4(z, x, x, x);
    public readonly int4 zxxy => new int4(z, x, x, y);
    public readonly int4 zxxz => new int4(z, x, x, z);
    public readonly int4 zxxw => new int4(z, x, x, w);
    public readonly int4 zxyx => new int4(z, x, y, x);
    public readonly int4 zxyy => new int4(z, x, y, y);
    public readonly int4 zxyz => new int4(z, x, y, z);
    public int4 zxyw { readonly get => new int4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
    public readonly int4 zxzx => new int4(z, x, z, x);
    public readonly int4 zxzy => new int4(z, x, z, y);
    public readonly int4 zxzz => new int4(z, x, z, z);
    public readonly int4 zxzw => new int4(z, x, z, w);
    public readonly int4 zxwx => new int4(z, x, w, x);
    public int4 zxwy { readonly get => new int4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
    public readonly int4 zxwz => new int4(z, x, w, z);
    public readonly int4 zxww => new int4(z, x, w, w);
    public readonly int4 zyxx => new int4(z, y, x, x);
    public readonly int4 zyxy => new int4(z, y, x, y);
    public readonly int4 zyxz => new int4(z, y, x, z);
    public int4 zyxw { readonly get => new int4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
    public readonly int4 zyyx => new int4(z, y, y, x);
    public readonly int4 zyyy => new int4(z, y, y, y);
    public readonly int4 zyyz => new int4(z, y, y, z);
    public readonly int4 zyyw => new int4(z, y, y, w);
    public readonly int4 zyzx => new int4(z, y, z, x);
    public readonly int4 zyzy => new int4(z, y, z, y);
    public readonly int4 zyzz => new int4(z, y, z, z);
    public readonly int4 zyzw => new int4(z, y, z, w);
    public int4 zywx { readonly get => new int4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
    public readonly int4 zywy => new int4(z, y, w, y);
    public readonly int4 zywz => new int4(z, y, w, z);
    public readonly int4 zyww => new int4(z, y, w, w);
    public readonly int4 zzxx => new int4(z, z, x, x);
    public readonly int4 zzxy => new int4(z, z, x, y);
    public readonly int4 zzxz => new int4(z, z, x, z);
    public readonly int4 zzxw => new int4(z, z, x, w);
    public readonly int4 zzyx => new int4(z, z, y, x);
    public readonly int4 zzyy => new int4(z, z, y, y);
    public readonly int4 zzyz => new int4(z, z, y, z);
    public readonly int4 zzyw => new int4(z, z, y, w);
    public readonly int4 zzzx => new int4(z, z, z, x);
    public readonly int4 zzzy => new int4(z, z, z, y);
    public readonly int4 zzzz => new int4(z, z, z, z);
    public readonly int4 zzzw => new int4(z, z, z, w);
    public readonly int4 zzwx => new int4(z, z, w, x);
    public readonly int4 zzwy => new int4(z, z, w, y);
    public readonly int4 zzwz => new int4(z, z, w, z);
    public readonly int4 zzww => new int4(z, z, w, w);
    public readonly int4 zwxx => new int4(z, w, x, x);
    public int4 zwxy { readonly get => new int4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
    public readonly int4 zwxz => new int4(z, w, x, z);
    public readonly int4 zwxw => new int4(z, w, x, w);
    public int4 zwyx { readonly get => new int4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
    public readonly int4 zwyy => new int4(z, w, y, y);
    public readonly int4 zwyz => new int4(z, w, y, z);
    public readonly int4 zwyw => new int4(z, w, y, w);
    public readonly int4 zwzx => new int4(z, w, z, x);
    public readonly int4 zwzy => new int4(z, w, z, y);
    public readonly int4 zwzz => new int4(z, w, z, z);
    public readonly int4 zwzw => new int4(z, w, z, w);
    public readonly int4 zwwx => new int4(z, w, w, x);
    public readonly int4 zwwy => new int4(z, w, w, y);
    public readonly int4 zwwz => new int4(z, w, w, z);
    public readonly int4 zwww => new int4(z, w, w, w);
    public readonly int4 wxxx => new int4(w, x, x, x);
    public readonly int4 wxxy => new int4(w, x, x, y);
    public readonly int4 wxxz => new int4(w, x, x, z);
    public readonly int4 wxxw => new int4(w, x, x, w);
    public readonly int4 wxyx => new int4(w, x, y, x);
    public readonly int4 wxyy => new int4(w, x, y, y);
    public int4 wxyz { readonly get => new int4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
    public readonly int4 wxyw => new int4(w, x, y, w);
    public readonly int4 wxzx => new int4(w, x, z, x);
    public int4 wxzy { readonly get => new int4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
    public readonly int4 wxzz => new int4(w, x, z, z);
    public readonly int4 wxzw => new int4(w, x, z, w);
    public readonly int4 wxwx => new int4(w, x, w, x);
    public readonly int4 wxwy => new int4(w, x, w, y);
    public readonly int4 wxwz => new int4(w, x, w, z);
    public readonly int4 wxww => new int4(w, x, w, w);
    public readonly int4 wyxx => new int4(w, y, x, x);
    public readonly int4 wyxy => new int4(w, y, x, y);
    public int4 wyxz { readonly get => new int4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
    public readonly int4 wyxw => new int4(w, y, x, w);
    public readonly int4 wyyx => new int4(w, y, y, x);
    public readonly int4 wyyy => new int4(w, y, y, y);
    public readonly int4 wyyz => new int4(w, y, y, z);
    public readonly int4 wyyw => new int4(w, y, y, w);
    public int4 wyzx { readonly get => new int4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
    public readonly int4 wyzy => new int4(w, y, z, y);
    public readonly int4 wyzz => new int4(w, y, z, z);
    public readonly int4 wyzw => new int4(w, y, z, w);
    public readonly int4 wywx => new int4(w, y, w, x);
    public readonly int4 wywy => new int4(w, y, w, y);
    public readonly int4 wywz => new int4(w, y, w, z);
    public readonly int4 wyww => new int4(w, y, w, w);
    public readonly int4 wzxx => new int4(w, z, x, x);
    public int4 wzxy { readonly get => new int4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
    public readonly int4 wzxz => new int4(w, z, x, z);
    public readonly int4 wzxw => new int4(w, z, x, w);
    public int4 wzyx { readonly get => new int4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
    public readonly int4 wzyy => new int4(w, z, y, y);
    public readonly int4 wzyz => new int4(w, z, y, z);
    public readonly int4 wzyw => new int4(w, z, y, w);
    public readonly int4 wzzx => new int4(w, z, z, x);
    public readonly int4 wzzy => new int4(w, z, z, y);
    public readonly int4 wzzz => new int4(w, z, z, z);
    public readonly int4 wzzw => new int4(w, z, z, w);
    public readonly int4 wzwx => new int4(w, z, w, x);
    public readonly int4 wzwy => new int4(w, z, w, y);
    public readonly int4 wzwz => new int4(w, z, w, z);
    public readonly int4 wzww => new int4(w, z, w, w);
    public readonly int4 wwxx => new int4(w, w, x, x);
    public readonly int4 wwxy => new int4(w, w, x, y);
    public readonly int4 wwxz => new int4(w, w, x, z);
    public readonly int4 wwxw => new int4(w, w, x, w);
    public readonly int4 wwyx => new int4(w, w, y, x);
    public readonly int4 wwyy => new int4(w, w, y, y);
    public readonly int4 wwyz => new int4(w, w, y, z);
    public readonly int4 wwyw => new int4(w, w, y, w);
    public readonly int4 wwzx => new int4(w, w, z, x);
    public readonly int4 wwzy => new int4(w, w, z, y);
    public readonly int4 wwzz => new int4(w, w, z, z);
    public readonly int4 wwzw => new int4(w, w, z, w);
    public readonly int4 wwwx => new int4(w, w, w, x);
    public readonly int4 wwwy => new int4(w, w, w, y);
    public readonly int4 wwwz => new int4(w, w, w, z);
    public readonly int4 wwww => new int4(w, w, w, w);
    public int r { readonly get => x; set => x = value; }
    public int g { readonly get => y; set => y = value; }
    public int b { readonly get => z; set => z = value; }
    public int a { readonly get => w; set => w = value; }
    public readonly int2 rr => new int2(x, x);
    public int2 rg { readonly get => new int2(x, y); set { x = value.x; y = value.y; } }
    public int2 rb { readonly get => new int2(x, z); set { x = value.x; z = value.y; } }
    public int2 ra { readonly get => new int2(x, w); set { x = value.x; w = value.y; } }
    public int2 gr { readonly get => new int2(y, x); set { y = value.x; x = value.y; } }
    public readonly int2 gg => new int2(y, y);
    public int2 gb { readonly get => new int2(y, z); set { y = value.x; z = value.y; } }
    public int2 ga { readonly get => new int2(y, w); set { y = value.x; w = value.y; } }
    public int2 br { readonly get => new int2(z, x); set { z = value.x; x = value.y; } }
    public int2 bg { readonly get => new int2(z, y); set { z = value.x; y = value.y; } }
    public readonly int2 bb => new int2(z, z);
    public int2 ba { readonly get => new int2(z, w); set { z = value.x; w = value.y; } }
    public int2 ar { readonly get => new int2(w, x); set { w = value.x; x = value.y; } }
    public int2 ag { readonly get => new int2(w, y); set { w = value.x; y = value.y; } }
    public int2 ab { readonly get => new int2(w, z); set { w = value.x; z = value.y; } }
    public readonly int2 aa => new int2(w, w);
    public readonly int3 rrr => new int3(x, x, x);
    public readonly int3 rrg => new int3(x, x, y);
    public readonly int3 rrb => new int3(x, x, z);
    public readonly int3 rra => new int3(x, x, w);
    public readonly int3 rgr => new int3(x, y, x);
    public readonly int3 rgg => new int3(x, y, y);
    public int3 rgb { readonly get => new int3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public int3 rga { readonly get => new int3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
    public readonly int3 rbr => new int3(x, z, x);
    public int3 rbg { readonly get => new int3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public readonly int3 rbb => new int3(x, z, z);
    public int3 rba { readonly get => new int3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
    public readonly int3 rar => new int3(x, w, x);
    public int3 rag { readonly get => new int3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
    public int3 rab { readonly get => new int3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
    public readonly int3 raa => new int3(x, w, w);
    public readonly int3 grr => new int3(y, x, x);
    public readonly int3 grg => new int3(y, x, y);
    public int3 grb { readonly get => new int3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public int3 gra { readonly get => new int3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
    public readonly int3 ggr => new int3(y, y, x);
    public readonly int3 ggg => new int3(y, y, y);
    public readonly int3 ggb => new int3(y, y, z);
    public readonly int3 gga => new int3(y, y, w);
    public int3 gbr { readonly get => new int3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public readonly int3 gbg => new int3(y, z, y);
    public readonly int3 gbb => new int3(y, z, z);
    public int3 gba { readonly get => new int3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
    public int3 gar { readonly get => new int3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
    public readonly int3 gag => new int3(y, w, y);
    public int3 gab { readonly get => new int3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
    public readonly int3 gaa => new int3(y, w, w);
    public readonly int3 brr => new int3(z, x, x);
    public int3 brg { readonly get => new int3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public readonly int3 brb => new int3(z, x, z);
    public int3 bra { readonly get => new int3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
    public int3 bgr { readonly get => new int3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public readonly int3 bgg => new int3(z, y, y);
    public readonly int3 bgb => new int3(z, y, z);
    public int3 bga { readonly get => new int3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
    public readonly int3 bbr => new int3(z, z, x);
    public readonly int3 bbg => new int3(z, z, y);
    public readonly int3 bbb => new int3(z, z, z);
    public readonly int3 bba => new int3(z, z, w);
    public int3 bar { readonly get => new int3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
    public int3 bag { readonly get => new int3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
    public readonly int3 bab => new int3(z, w, z);
    public readonly int3 baa => new int3(z, w, w);
    public readonly int3 arr => new int3(w, x, x);
    public int3 arg { readonly get => new int3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
    public int3 arb { readonly get => new int3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
    public readonly int3 ara => new int3(w, x, w);
    public int3 agr { readonly get => new int3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
    public readonly int3 agg => new int3(w, y, y);
    public int3 agb { readonly get => new int3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
    public readonly int3 aga => new int3(w, y, w);
    public int3 abr { readonly get => new int3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
    public int3 abg { readonly get => new int3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
    public readonly int3 abb => new int3(w, z, z);
    public readonly int3 aba => new int3(w, z, w);
    public readonly int3 aar => new int3(w, w, x);
    public readonly int3 aag => new int3(w, w, y);
    public readonly int3 aab => new int3(w, w, z);
    public readonly int3 aaa => new int3(w, w, w);
    public readonly int4 rrrr => new int4(x, x, x, x);
    public readonly int4 rrrg => new int4(x, x, x, y);
    public readonly int4 rrrb => new int4(x, x, x, z);
    public readonly int4 rrra => new int4(x, x, x, w);
    public readonly int4 rrgr => new int4(x, x, y, x);
    public readonly int4 rrgg => new int4(x, x, y, y);
    public readonly int4 rrgb => new int4(x, x, y, z);
    public readonly int4 rrga => new int4(x, x, y, w);
    public readonly int4 rrbr => new int4(x, x, z, x);
    public readonly int4 rrbg => new int4(x, x, z, y);
    public readonly int4 rrbb => new int4(x, x, z, z);
    public readonly int4 rrba => new int4(x, x, z, w);
    public readonly int4 rrar => new int4(x, x, w, x);
    public readonly int4 rrag => new int4(x, x, w, y);
    public readonly int4 rrab => new int4(x, x, w, z);
    public readonly int4 rraa => new int4(x, x, w, w);
    public readonly int4 rgrr => new int4(x, y, x, x);
    public readonly int4 rgrg => new int4(x, y, x, y);
    public readonly int4 rgrb => new int4(x, y, x, z);
    public readonly int4 rgra => new int4(x, y, x, w);
    public readonly int4 rggr => new int4(x, y, y, x);
    public readonly int4 rggg => new int4(x, y, y, y);
    public readonly int4 rggb => new int4(x, y, y, z);
    public readonly int4 rgga => new int4(x, y, y, w);
    public readonly int4 rgbr => new int4(x, y, z, x);
    public readonly int4 rgbg => new int4(x, y, z, y);
    public readonly int4 rgbb => new int4(x, y, z, z);
    public int4 rgba { readonly get => new int4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
    public readonly int4 rgar => new int4(x, y, w, x);
    public readonly int4 rgag => new int4(x, y, w, y);
    public int4 rgab { readonly get => new int4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
    public readonly int4 rgaa => new int4(x, y, w, w);
    public readonly int4 rbrr => new int4(x, z, x, x);
    public readonly int4 rbrg => new int4(x, z, x, y);
    public readonly int4 rbrb => new int4(x, z, x, z);
    public readonly int4 rbra => new int4(x, z, x, w);
    public readonly int4 rbgr => new int4(x, z, y, x);
    public readonly int4 rbgg => new int4(x, z, y, y);
    public readonly int4 rbgb => new int4(x, z, y, z);
    public int4 rbga { readonly get => new int4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
    public readonly int4 rbbr => new int4(x, z, z, x);
    public readonly int4 rbbg => new int4(x, z, z, y);
    public readonly int4 rbbb => new int4(x, z, z, z);
    public readonly int4 rbba => new int4(x, z, z, w);
    public readonly int4 rbar => new int4(x, z, w, x);
    public int4 rbag { readonly get => new int4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
    public readonly int4 rbab => new int4(x, z, w, z);
    public readonly int4 rbaa => new int4(x, z, w, w);
    public readonly int4 rarr => new int4(x, w, x, x);
    public readonly int4 rarg => new int4(x, w, x, y);
    public readonly int4 rarb => new int4(x, w, x, z);
    public readonly int4 rara => new int4(x, w, x, w);
    public readonly int4 ragr => new int4(x, w, y, x);
    public readonly int4 ragg => new int4(x, w, y, y);
    public int4 ragb { readonly get => new int4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
    public readonly int4 raga => new int4(x, w, y, w);
    public readonly int4 rabr => new int4(x, w, z, x);
    public int4 rabg { readonly get => new int4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
    public readonly int4 rabb => new int4(x, w, z, z);
    public readonly int4 raba => new int4(x, w, z, w);
    public readonly int4 raar => new int4(x, w, w, x);
    public readonly int4 raag => new int4(x, w, w, y);
    public readonly int4 raab => new int4(x, w, w, z);
    public readonly int4 raaa => new int4(x, w, w, w);
    public readonly int4 grrr => new int4(y, x, x, x);
    public readonly int4 grrg => new int4(y, x, x, y);
    public readonly int4 grrb => new int4(y, x, x, z);
    public readonly int4 grra => new int4(y, x, x, w);
    public readonly int4 grgr => new int4(y, x, y, x);
    public readonly int4 grgg => new int4(y, x, y, y);
    public readonly int4 grgb => new int4(y, x, y, z);
    public readonly int4 grga => new int4(y, x, y, w);
    public readonly int4 grbr => new int4(y, x, z, x);
    public readonly int4 grbg => new int4(y, x, z, y);
    public readonly int4 grbb => new int4(y, x, z, z);
    public int4 grba { readonly get => new int4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
    public readonly int4 grar => new int4(y, x, w, x);
    public readonly int4 grag => new int4(y, x, w, y);
    public int4 grab { readonly get => new int4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
    public readonly int4 graa => new int4(y, x, w, w);
    public readonly int4 ggrr => new int4(y, y, x, x);
    public readonly int4 ggrg => new int4(y, y, x, y);
    public readonly int4 ggrb => new int4(y, y, x, z);
    public readonly int4 ggra => new int4(y, y, x, w);
    public readonly int4 gggr => new int4(y, y, y, x);
    public readonly int4 gggg => new int4(y, y, y, y);
    public readonly int4 gggb => new int4(y, y, y, z);
    public readonly int4 ggga => new int4(y, y, y, w);
    public readonly int4 ggbr => new int4(y, y, z, x);
    public readonly int4 ggbg => new int4(y, y, z, y);
    public readonly int4 ggbb => new int4(y, y, z, z);
    public readonly int4 ggba => new int4(y, y, z, w);
    public readonly int4 ggar => new int4(y, y, w, x);
    public readonly int4 ggag => new int4(y, y, w, y);
    public readonly int4 ggab => new int4(y, y, w, z);
    public readonly int4 ggaa => new int4(y, y, w, w);
    public readonly int4 gbrr => new int4(y, z, x, x);
    public readonly int4 gbrg => new int4(y, z, x, y);
    public readonly int4 gbrb => new int4(y, z, x, z);
    public int4 gbra { readonly get => new int4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
    public readonly int4 gbgr => new int4(y, z, y, x);
    public readonly int4 gbgg => new int4(y, z, y, y);
    public readonly int4 gbgb => new int4(y, z, y, z);
    public readonly int4 gbga => new int4(y, z, y, w);
    public readonly int4 gbbr => new int4(y, z, z, x);
    public readonly int4 gbbg => new int4(y, z, z, y);
    public readonly int4 gbbb => new int4(y, z, z, z);
    public readonly int4 gbba => new int4(y, z, z, w);
    public int4 gbar { readonly get => new int4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
    public readonly int4 gbag => new int4(y, z, w, y);
    public readonly int4 gbab => new int4(y, z, w, z);
    public readonly int4 gbaa => new int4(y, z, w, w);
    public readonly int4 garr => new int4(y, w, x, x);
    public readonly int4 garg => new int4(y, w, x, y);
    public int4 garb { readonly get => new int4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
    public readonly int4 gara => new int4(y, w, x, w);
    public readonly int4 gagr => new int4(y, w, y, x);
    public readonly int4 gagg => new int4(y, w, y, y);
    public readonly int4 gagb => new int4(y, w, y, z);
    public readonly int4 gaga => new int4(y, w, y, w);
    public int4 gabr { readonly get => new int4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
    public readonly int4 gabg => new int4(y, w, z, y);
    public readonly int4 gabb => new int4(y, w, z, z);
    public readonly int4 gaba => new int4(y, w, z, w);
    public readonly int4 gaar => new int4(y, w, w, x);
    public readonly int4 gaag => new int4(y, w, w, y);
    public readonly int4 gaab => new int4(y, w, w, z);
    public readonly int4 gaaa => new int4(y, w, w, w);
    public readonly int4 brrr => new int4(z, x, x, x);
    public readonly int4 brrg => new int4(z, x, x, y);
    public readonly int4 brrb => new int4(z, x, x, z);
    public readonly int4 brra => new int4(z, x, x, w);
    public readonly int4 brgr => new int4(z, x, y, x);
    public readonly int4 brgg => new int4(z, x, y, y);
    public readonly int4 brgb => new int4(z, x, y, z);
    public int4 brga { readonly get => new int4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
    public readonly int4 brbr => new int4(z, x, z, x);
    public readonly int4 brbg => new int4(z, x, z, y);
    public readonly int4 brbb => new int4(z, x, z, z);
    public readonly int4 brba => new int4(z, x, z, w);
    public readonly int4 brar => new int4(z, x, w, x);
    public int4 brag { readonly get => new int4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
    public readonly int4 brab => new int4(z, x, w, z);
    public readonly int4 braa => new int4(z, x, w, w);
    public readonly int4 bgrr => new int4(z, y, x, x);
    public readonly int4 bgrg => new int4(z, y, x, y);
    public readonly int4 bgrb => new int4(z, y, x, z);
    public int4 bgra { readonly get => new int4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
    public readonly int4 bggr => new int4(z, y, y, x);
    public readonly int4 bggg => new int4(z, y, y, y);
    public readonly int4 bggb => new int4(z, y, y, z);
    public readonly int4 bgga => new int4(z, y, y, w);
    public readonly int4 bgbr => new int4(z, y, z, x);
    public readonly int4 bgbg => new int4(z, y, z, y);
    public readonly int4 bgbb => new int4(z, y, z, z);
    public readonly int4 bgba => new int4(z, y, z, w);
    public int4 bgar { readonly get => new int4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
    public readonly int4 bgag => new int4(z, y, w, y);
    public readonly int4 bgab => new int4(z, y, w, z);
    public readonly int4 bgaa => new int4(z, y, w, w);
    public readonly int4 bbrr => new int4(z, z, x, x);
    public readonly int4 bbrg => new int4(z, z, x, y);
    public readonly int4 bbrb => new int4(z, z, x, z);
    public readonly int4 bbra => new int4(z, z, x, w);
    public readonly int4 bbgr => new int4(z, z, y, x);
    public readonly int4 bbgg => new int4(z, z, y, y);
    public readonly int4 bbgb => new int4(z, z, y, z);
    public readonly int4 bbga => new int4(z, z, y, w);
    public readonly int4 bbbr => new int4(z, z, z, x);
    public readonly int4 bbbg => new int4(z, z, z, y);
    public readonly int4 bbbb => new int4(z, z, z, z);
    public readonly int4 bbba => new int4(z, z, z, w);
    public readonly int4 bbar => new int4(z, z, w, x);
    public readonly int4 bbag => new int4(z, z, w, y);
    public readonly int4 bbab => new int4(z, z, w, z);
    public readonly int4 bbaa => new int4(z, z, w, w);
    public readonly int4 barr => new int4(z, w, x, x);
    public int4 barg { readonly get => new int4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
    public readonly int4 barb => new int4(z, w, x, z);
    public readonly int4 bara => new int4(z, w, x, w);
    public int4 bagr { readonly get => new int4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
    public readonly int4 bagg => new int4(z, w, y, y);
    public readonly int4 bagb => new int4(z, w, y, z);
    public readonly int4 baga => new int4(z, w, y, w);
    public readonly int4 babr => new int4(z, w, z, x);
    public readonly int4 babg => new int4(z, w, z, y);
    public readonly int4 babb => new int4(z, w, z, z);
    public readonly int4 baba => new int4(z, w, z, w);
    public readonly int4 baar => new int4(z, w, w, x);
    public readonly int4 baag => new int4(z, w, w, y);
    public readonly int4 baab => new int4(z, w, w, z);
    public readonly int4 baaa => new int4(z, w, w, w);
    public readonly int4 arrr => new int4(w, x, x, x);
    public readonly int4 arrg => new int4(w, x, x, y);
    public readonly int4 arrb => new int4(w, x, x, z);
    public readonly int4 arra => new int4(w, x, x, w);
    public readonly int4 argr => new int4(w, x, y, x);
    public readonly int4 argg => new int4(w, x, y, y);
    public int4 argb { readonly get => new int4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
    public readonly int4 arga => new int4(w, x, y, w);
    public readonly int4 arbr => new int4(w, x, z, x);
    public int4 arbg { readonly get => new int4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
    public readonly int4 arbb => new int4(w, x, z, z);
    public readonly int4 arba => new int4(w, x, z, w);
    public readonly int4 arar => new int4(w, x, w, x);
    public readonly int4 arag => new int4(w, x, w, y);
    public readonly int4 arab => new int4(w, x, w, z);
    public readonly int4 araa => new int4(w, x, w, w);
    public readonly int4 agrr => new int4(w, y, x, x);
    public readonly int4 agrg => new int4(w, y, x, y);
    public int4 agrb { readonly get => new int4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
    public readonly int4 agra => new int4(w, y, x, w);
    public readonly int4 aggr => new int4(w, y, y, x);
    public readonly int4 aggg => new int4(w, y, y, y);
    public readonly int4 aggb => new int4(w, y, y, z);
    public readonly int4 agga => new int4(w, y, y, w);
    public int4 agbr { readonly get => new int4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
    public readonly int4 agbg => new int4(w, y, z, y);
    public readonly int4 agbb => new int4(w, y, z, z);
    public readonly int4 agba => new int4(w, y, z, w);
    public readonly int4 agar => new int4(w, y, w, x);
    public readonly int4 agag => new int4(w, y, w, y);
    public readonly int4 agab => new int4(w, y, w, z);
    public readonly int4 agaa => new int4(w, y, w, w);
    public readonly int4 abrr => new int4(w, z, x, x);
    public int4 abrg { readonly get => new int4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
    public readonly int4 abrb => new int4(w, z, x, z);
    public readonly int4 abra => new int4(w, z, x, w);
    public int4 abgr { readonly get => new int4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
    public readonly int4 abgg => new int4(w, z, y, y);
    public readonly int4 abgb => new int4(w, z, y, z);
    public readonly int4 abga => new int4(w, z, y, w);
    public readonly int4 abbr => new int4(w, z, z, x);
    public readonly int4 abbg => new int4(w, z, z, y);
    public readonly int4 abbb => new int4(w, z, z, z);
    public readonly int4 abba => new int4(w, z, z, w);
    public readonly int4 abar => new int4(w, z, w, x);
    public readonly int4 abag => new int4(w, z, w, y);
    public readonly int4 abab => new int4(w, z, w, z);
    public readonly int4 abaa => new int4(w, z, w, w);
    public readonly int4 aarr => new int4(w, w, x, x);
    public readonly int4 aarg => new int4(w, w, x, y);
    public readonly int4 aarb => new int4(w, w, x, z);
    public readonly int4 aara => new int4(w, w, x, w);
    public readonly int4 aagr => new int4(w, w, y, x);
    public readonly int4 aagg => new int4(w, w, y, y);
    public readonly int4 aagb => new int4(w, w, y, z);
    public readonly int4 aaga => new int4(w, w, y, w);
    public readonly int4 aabr => new int4(w, w, z, x);
    public readonly int4 aabg => new int4(w, w, z, y);
    public readonly int4 aabb => new int4(w, w, z, z);
    public readonly int4 aaba => new int4(w, w, z, w);
    public readonly int4 aaar => new int4(w, w, w, x);
    public readonly int4 aaag => new int4(w, w, w, y);
    public readonly int4 aaab => new int4(w, w, w, z);
    public readonly int4 aaaa => new int4(w, w, w, w);
}
