// <auto-generated>
// Written by tools/gen_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591, CS0660, CS0661
using System;
using System.Runtime.InteropServices;

namespace Csl.Types;

/// <summary>HLSL uint2x3: 2 rows of uint3, indexed m[row][column].</summary>
[StructLayout(LayoutKind.Sequential)]
[System.Diagnostics.DebuggerNonUserCode]
public struct uint2x3
{
    public uint3 r0, r1;
    public uint2x3(uint3 r0, uint3 r1) { this.r0 = r0; this.r1 = r1; }
    public uint2x3(uint m00, uint m01, uint m02, uint m10, uint m11, uint m12) { r0 = new uint3(m00, m01, m02); r1 = new uint3(m10, m11, m12); }
    public uint2x3(uint v) { r0 = v; r1 = v; }
    public static implicit operator uint2x3(uint v) => new uint2x3(v);
    public uint3 this[int i]
    {
        readonly get => i switch { 0 => r0, 1 => r1, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: r0 = value; break; case 1: r1 = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public uint3 this[uint i] { readonly get => this[(int)i]; set => this[(int)i] = value; }
    public uint _m00 { readonly get => r0.x; set => r0.x = value; }
    public uint _11 { readonly get => r0.x; set => r0.x = value; }
    public uint _m01 { readonly get => r0.y; set => r0.y = value; }
    public uint _12 { readonly get => r0.y; set => r0.y = value; }
    public uint _m02 { readonly get => r0.z; set => r0.z = value; }
    public uint _13 { readonly get => r0.z; set => r0.z = value; }
    public uint _m10 { readonly get => r1.x; set => r1.x = value; }
    public uint _21 { readonly get => r1.x; set => r1.x = value; }
    public uint _m11 { readonly get => r1.y; set => r1.y = value; }
    public uint _22 { readonly get => r1.y; set => r1.y = value; }
    public uint _m12 { readonly get => r1.z; set => r1.z = value; }
    public uint _23 { readonly get => r1.z; set => r1.z = value; }
    public static explicit operator uint2x3(float2x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(float2x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(float3x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(float3x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(float4x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(float4x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(half2x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(half2x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(half3x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(half3x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(half4x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(half4x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(int2x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(int2x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(int3x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(int3x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(int4x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(int4x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(uint2x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(uint3x3 v) => new uint2x3(v.r0, v.r1);
    public static explicit operator uint2x3(uint3x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(uint4x3 v) => new uint2x3(v.r0, v.r1);
    public static explicit operator uint2x3(uint4x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(bool2x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(bool2x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(bool3x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(bool3x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(bool4x3 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static explicit operator uint2x3(bool4x4 v) => new uint2x3((uint3)v.r0, (uint3)v.r1);
    public static uint2x3 operator +(uint2x3 a, uint2x3 b) => new uint2x3(a.r0 + b.r0, a.r1 + b.r1);
    public static uint2x3 operator +(uint2x3 a, uint b) => new uint2x3(a.r0 + b, a.r1 + b);
    public static uint2x3 operator +(uint a, uint2x3 b) => new uint2x3(a + b.r0, a + b.r1);
    public static uint2x3 operator -(uint2x3 a, uint2x3 b) => new uint2x3(a.r0 - b.r0, a.r1 - b.r1);
    public static uint2x3 operator -(uint2x3 a, uint b) => new uint2x3(a.r0 - b, a.r1 - b);
    public static uint2x3 operator -(uint a, uint2x3 b) => new uint2x3(a - b.r0, a - b.r1);
    public static uint2x3 operator *(uint2x3 a, uint2x3 b) => new uint2x3(a.r0 * b.r0, a.r1 * b.r1);
    public static uint2x3 operator *(uint2x3 a, uint b) => new uint2x3(a.r0 * b, a.r1 * b);
    public static uint2x3 operator *(uint a, uint2x3 b) => new uint2x3(a * b.r0, a * b.r1);
    public static uint2x3 operator /(uint2x3 a, uint2x3 b) => new uint2x3(a.r0 / b.r0, a.r1 / b.r1);
    public static uint2x3 operator /(uint2x3 a, uint b) => new uint2x3(a.r0 / b, a.r1 / b);
    public static uint2x3 operator /(uint a, uint2x3 b) => new uint2x3(a / b.r0, a / b.r1);
    public static uint2x3 operator %(uint2x3 a, uint2x3 b) => new uint2x3(a.r0 % b.r0, a.r1 % b.r1);
    public static uint2x3 operator %(uint2x3 a, uint b) => new uint2x3(a.r0 % b, a.r1 % b);
    public static uint2x3 operator %(uint a, uint2x3 b) => new uint2x3(a % b.r0, a % b.r1);
    public static uint2x3 operator -(uint2x3 a) => new uint2x3(-a.r0, -a.r1);
}
