#!/usr/bin/env python3
"""Writes the HLSL types and intrinsics of Csl.Types (namespace Csl.Types).

Run from the repository root: python tools/gen_types.py. The output is committed; this script is
the source of truth for everything repetitive (swizzles, operators, conversions, intrinsic overloads).

The C# types exist so shader code written in C# type-checks the way HLSL would: the same names, the
same swizzles, the same conversions (widening ones implicit, as HLSL's promotion bool < int < uint <
half < float < double; narrowing and truncation explicit, which is where HLSL only warns). The
members also run on the CPU, so shader helpers can be unit tested one thread at a time."""
import itertools, os, re

OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'Csl.Types', 'Language')

# rank: HLSL promotion order. cs: the C# arithmetic type the components compute in.
SCALARS = {
    'bool':   dict(rank=0, kind='bool'),
    'int':    dict(rank=1, kind='int'),
    'uint':   dict(rank=2, kind='int'),
    'half':   dict(rank=3, kind='float'),
    'float':  dict(rank=4, kind='float'),
    'double': dict(rank=5, kind='float'),
}
NUMERIC = [s for s in SCALARS if s != 'bool']
COMPONENTS = ['x', 'y', 'z', 'w']
COLORS = ['r', 'g', 'b', 'a']

HEADER = '''// <auto-generated>
// Written by tools/gen_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591, CS0660, CS0661
using System;
using System.Runtime.InteropServices;

namespace Csl.Types;
'''

def vec(scalar, n): return scalar if n == 1 else f'{scalar}{n}'
def one(scalar): return {'bool': 'true', 'int': '1', 'uint': '1u', 'half': '(half)1f', 'float': '1f', 'double': '1d'}[scalar]
def zero(scalar): return {'bool': 'false', 'int': '0', 'uint': '0u', 'half': 'default(half)', 'float': '0f', 'double': '0d'}[scalar]

def convert(expr, src, dst):
    """C# expression converting one component from src to dst scalar."""
    if src == dst: return expr
    if src == 'bool': return f'({expr} ? {one(dst)} : {zero(dst)})'
    if dst == 'bool': return f'((float){expr} != 0f)' if src == 'half' else f'({expr} != 0)'
    if src == 'half': return f'({dst})(float){expr}'
    if dst == 'half': return f'(half)(float){expr}'
    return f'({dst}){expr}'

def partitions(n):
    """Every way to write n components as a list of vector sizes, for the constructors."""
    if n == 0:
        yield []
        return
    for first in range(1, n + 1):
        for rest in partitions(n - first):
            yield [first] + rest

# -- scalars -----------------------------------------------------------------------------------

def emit_half():
    return HEADER + '''
/// <summary>
/// HLSL half: a 16-bit float on the GPU. Here a float that converts implicitly to float (widening)
/// and explicitly back, so a half expression type-checks where HLSL would take it.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public readonly struct half : IEquatable<half>
{
    private readonly float value;
    public half(float value) { this.value = (float)(Half)value; }
    public static implicit operator float(half v) => v.value;
    public static implicit operator double(half v) => v.value;
    public static explicit operator half(float v) => new half(v);
    public static explicit operator half(double v) => new half((float)v);
    public static implicit operator half(int v) => new half(v);
    public static implicit operator half(uint v) => new half(v);
    public static explicit operator int(half v) => (int)v.value;
    public static explicit operator uint(half v) => (uint)v.value;
    public static half operator -(half a) => new half(-a.value);
    public static half operator +(half a) => a;
    public static half operator +(half a, half b) => new half(a.value + b.value);
    public static half operator -(half a, half b) => new half(a.value - b.value);
    public static half operator *(half a, half b) => new half(a.value * b.value);
    public static half operator /(half a, half b) => new half(a.value / b.value);
    public static half operator %(half a, half b) => new half(a.value % b.value);
    public static half operator ++(half a) => new half(a.value + 1f);
    public static half operator --(half a) => new half(a.value - 1f);
    public bool Equals(half other) => value.Equals(other.value);
    public override bool Equals(object? obj) => obj is half other && Equals(other);
    public override int GetHashCode() => value.GetHashCode();
    public override string ToString() => value.ToString(System.Globalization.CultureInfo.InvariantCulture);
}
'''

def emit_scalar_swizzles():
    out = [HEADER, '/// <summary>Swizzles of scalars: <c>f.xxx</c>, <c>f.r</c>, as HLSL allows.</summary>', 'public static class ScalarSwizzles', '{']
    for scalar in SCALARS:
        out.append(f'    extension({scalar} v)')
        out.append('    {')
        for names in (['x'], ['r']):
            for length in (1, 2, 3, 4):
                sw = names[0] * length
                if length == 1:
                    out.append(f'        public {scalar} {sw} => v;')
                else:
                    out.append(f'        public {scalar}{length} {sw} => new {scalar}{length}(v);')
        out.append('    }')
    out.append('}')
    return '\n'.join(out) + '\n'

# -- vectors -----------------------------------------------------------------------------------

def emit_vector(scalar, n):
    s = SCALARS[scalar]
    name = vec(scalar, n)
    comps = COMPONENTS[:n]
    b = f'bool{n}'
    out = [HEADER, f'/// <summary>HLSL {name}: {n} components of {scalar}.</summary>',
           '[StructLayout(LayoutKind.Sequential)]', f'public struct {name} : IEquatable<{name}>', '{']
    out.append(f'    public {scalar} ' + ', '.join(comps) + ';')
    out.append(f'    public {name}({", ".join(f"{scalar} {c}" for c in comps)}) {{ {" ".join(f"this.{c} = {c};" for c in comps)} }}')
    out.append(f'    public {name}({scalar} v) {{ {" ".join(f"{c} = v;" for c in comps)} }}')
    # constructors from any split of the components into smaller vectors: float4(float2, float, float)
    for parts in partitions(n):
        if len(parts) < 2 or all(p == 1 for p in parts):
            continue
        params, assigns, k = [], [], 0
        for i, p in enumerate(parts):
            params.append(f'{vec(scalar, p)} p{i}')
            if p == 1:
                assigns.append(f'{comps[k]} = p{i};')
                k += 1
            else:
                for j in range(p):
                    assigns.append(f'{comps[k]} = p{i}.{COMPONENTS[j]};')
                    k += 1
        out.append(f'    public {name}({", ".join(params)}) {{ {" ".join(assigns)} }}')
    # HLSL builds a vector from parts of any scalar type: float4(int3, 1), uint3(i, j, k) with ints.
    # Loose overloads take what does not convert implicitly: vector parts of a higher rank, scalars as
    # double. C# overload resolution still picks the exact constructor when the parts match.
    higher = [o for o in SCALARS if SCALARS[o]['rank'] > s['rank']]
    if scalar != 'double':
        splat = convert("v", "double", scalar) if scalar != "half" else "(half)(float)v"
        out.append(f'    public {name}(double v) {{ {" ".join(f"{c} = {splat};" for c in comps)} }}')
    # float3(v) with v a float3: HLSL writes it, C# needs the constructor.
    out.append(f'    public {name}({name} v) {{ {" ".join(f"{c} = v.{c};" for c in comps)} }}')
    for parts in partitions(n):
        choices = [higher if p > 1 else ['double'] for p in parts]
        for combo in itertools.product(*choices):
            if scalar == 'double' and all(p == 1 for p in parts):
                continue
            params, assigns, k = [], [], 0
            for i, (p, t) in enumerate(zip(parts, combo)):
                params.append(f'{vec(t, p)} p{i}')
                if p == 1:
                    assigns.append(f'{comps[k]} = {convert(f"p{i}", "double", scalar) if scalar != "half" else f"(half)(float)p{i}"};')
                    k += 1
                else:
                    for j in range(p):
                        assigns.append(f'{comps[k]} = {convert(f"p{i}.{COMPONENTS[j]}", t, scalar)};')
                        k += 1
            out.append(f'    public {name}({", ".join(params)}) {{ {" ".join(assigns)} }}')
    out.append(f'    public static implicit operator {name}({scalar} v) => new {name}(v);')
    # conversions into this type: same size (implicit when widening), larger (explicit truncation)
    for other in SCALARS:
        for m in (2, 3, 4):
            if other == scalar and m == n:
                continue
            if m < n:
                continue
            src = vec(other, m)
            kind = 'implicit' if m == n and SCALARS[other]['rank'] < s['rank'] else 'explicit'
            body = ', '.join(convert(f'v.{c}', other, scalar) for c in comps)
            out.append(f'    public static {kind} operator {name}({src} v) => new {name}({body});')
    # truncation to a scalar
    for other in SCALARS:
        out.append(f'    public static explicit operator {other}({name} v) => {convert("v.x", scalar, other)};')
    # indexer
    out.append(f'    public {scalar} this[int i]')
    out.append('    {')
    out.append('        get => i switch { ' + ', '.join(f'{i} => {c}' for i, c in enumerate(comps)) + ', _ => throw new IndexOutOfRangeException() };')
    out.append('        set { switch (i) { ' + ' '.join(f'case {i}: {c} = value; break;' for i, c in enumerate(comps)) + ' default: throw new IndexOutOfRangeException(); } }')
    out.append('    }')
    out.append(f'    public {scalar} this[uint i] {{ get => this[(int)i]; set => this[(int)i] = value; }}')

    def cw(op, left, right, cast=True):
        parts = []
        for c in comps:
            l = left.replace('#', c); r = right.replace('#', c)
            e = f'{l} {op} {r}'
            parts.append(f'({scalar})({e})' if cast and scalar not in ('bool',) else e)
        return ', '.join(parts)

    if scalar != 'bool':
        for op in ['+', '-', '*', '/', '%']:
            if scalar == 'half':
                out.append(f'    public static {name} operator {op}({name} a, {name} b) => new {name}({", ".join(f"(half)((float)a.{c} {op} (float)b.{c})" for c in comps)});')
                out.append(f'    public static {name} operator {op}({name} a, {scalar} b) => new {name}({", ".join(f"(half)((float)a.{c} {op} (float)b)" for c in comps)});')
                out.append(f'    public static {name} operator {op}({scalar} a, {name} b) => new {name}({", ".join(f"(half)((float)a {op} (float)b.{c})" for c in comps)});')
            else:
                out.append(f'    public static {name} operator {op}({name} a, {name} b) => new {name}({cw(op, "a.#", "b.#")});')
                out.append(f'    public static {name} operator {op}({name} a, {scalar} b) => new {name}({cw(op, "a.#", "b")});')
                out.append(f'    public static {name} operator {op}({scalar} a, {name} b) => new {name}({cw(op, "a", "b.#")});')
        if scalar == 'half':
            out.append(f'    public static {name} operator -({name} a) => new {name}({", ".join(f"-a.{c}" for c in comps)});')
        elif scalar == 'uint':
            out.append(f'    public static {name} operator -({name} a) => new {name}({", ".join(f"(uint)(-(int)a.{c})" for c in comps)});')
        else:
            out.append(f'    public static {name} operator -({name} a) => new {name}({", ".join(f"({scalar})(-a.{c})" for c in comps)});')
        out.append(f'    public static {name} operator +({name} a) => a;')
        out.append(f'    public static {name} operator ++({name} a) => a + {one(scalar)};')
        out.append(f'    public static {name} operator --({name} a) => a - {one(scalar)};')
        for op in ['<', '>', '<=', '>=']:
            f = (lambda e: f'(float){e}') if scalar == 'half' else (lambda e: e)
            out.append(f'    public static {b} operator {op}({name} a, {name} b) => new {b}({", ".join(f"{f(f"a.{c}")} {op} {f(f"b.{c}")}" for c in comps)});')
            out.append(f'    public static {b} operator {op}({name} a, {scalar} b) => new {b}({", ".join(f"{f(f"a.{c}")} {op} {f("b")}" for c in comps)});')
            out.append(f'    public static {b} operator {op}({scalar} a, {name} b) => new {b}({", ".join(f"{f("a")} {op} {f(f"b.{c}")}" for c in comps)});')
    if scalar in ('int', 'uint'):
        for op in ['&', '|', '^']:
            out.append(f'    public static {name} operator {op}({name} a, {name} b) => new {name}({cw(op, "a.#", "b.#")});')
            out.append(f'    public static {name} operator {op}({name} a, {scalar} b) => new {name}({cw(op, "a.#", "b")});')
            out.append(f'    public static {name} operator {op}({scalar} a, {name} b) => new {name}({cw(op, "a", "b.#")});')
        for op in ['<<', '>>']:
            out.append(f'    public static {name} operator {op}({name} a, int b) => new {name}({cw(op, "a.#", "b")});')
            out.append(f'    public static {name} operator {op}({name} a, {vec("int", n)} b) => new {name}({cw(op, "a.#", "b.#")});')
            if scalar == 'uint':
                out.append(f'    public static {name} operator {op}({name} a, {vec("uint", n)} b) => new {name}({cw(op, "a.#", "(int)b.#")});')
        out.append(f'    public static {name} operator ~({name} a) => new {name}({", ".join(f"({scalar})(~a.{c})" for c in comps)});')
    if scalar == 'bool':
        for op in ['&', '|', '^']:
            out.append(f'    public static {name} operator {op}({name} a, {name} b) => new {name}({", ".join(f"a.{c} {op} b.{c}" for c in comps)});')
        out.append(f'    public static {name} operator !({name} a) => new {name}({", ".join(f"!a.{c}" for c in comps)});')
        # && and || component-wise, as HLSL (before 2021) does them; C# needs true/false for that.
        out.append(f'    public static bool operator true({name} a) => {" && ".join(f"a.{c}" for c in comps)};')
        out.append(f'    public static bool operator false({name} a) => !({" || ".join(f"a.{c}" for c in comps)});')
    eqf = (lambda e: f'(float){e}') if scalar == 'half' else (lambda e: e)
    out.append(f'    public static {b} operator ==({name} a, {name} b) => new {b}({", ".join(f"{eqf(f"a.{c}")} == {eqf(f"b.{c}")}" for c in comps)});')
    out.append(f'    public static {b} operator !=({name} a, {name} b) => new {b}({", ".join(f"{eqf(f"a.{c}")} != {eqf(f"b.{c}")}" for c in comps)});')
    out.append(f'    public static {b} operator ==({name} a, {scalar} b) => new {b}({", ".join(f"{eqf(f"a.{c}")} == {eqf("b")}" for c in comps)});')
    out.append(f'    public static {b} operator !=({name} a, {scalar} b) => new {b}({", ".join(f"{eqf(f"a.{c}")} != {eqf("b")}" for c in comps)});')
    out.append(f'    public bool Equals({name} other) => {" && ".join(f"{c}.Equals(other.{c})" for c in comps)};')
    out.append(f'    public override bool Equals(object? obj) => obj is {name} other && Equals(other);')
    out.append(f'    public override int GetHashCode() => HashCode.Combine({", ".join(comps)});')
    out.append(f'    public override string ToString() => $"{name}({", ".join("{" + c + "}" for c in comps)})";')
    out.append('')
    out.append('    // Swizzles, xyzw and rgba. Setters only where no component repeats.')
    for names in (COMPONENTS[:n], COLORS[:n]):
        mapping = dict(zip(names, comps))
        if names == COLORS[:n]:
            for a, c in zip(names, comps):
                out.append(f'    public {scalar} {a} {{ readonly get => {c}; set => {c} = value; }}')
        for length in (2, 3, 4):
            for combo in itertools.product(names, repeat=length):
                sw = ''.join(combo)
                fields = [mapping[k] for k in combo]
                ctor = f'new {scalar}{length}({", ".join(fields)})'
                if len(set(combo)) == length:
                    setter = ' '.join(f'{f} = value.{COMPONENTS[i]};' for i, f in enumerate(fields))
                    out.append(f'    public {scalar}{length} {sw} {{ readonly get => {ctor}; set {{ {setter} }} }}')
                else:
                    out.append(f'    public readonly {scalar}{length} {sw} => {ctor};')
    out.append('}')
    return '\n'.join(out) + '\n'

# -- matrices ----------------------------------------------------------------------------------

MATRIX_SCALARS = ['float', 'half', 'int', 'uint', 'bool']

def mat(scalar, r, c): return f'{scalar}{r}x{c}'

def emit_matrix(scalar, r, c):
    name = mat(scalar, r, c)
    row = vec(scalar, c)
    rows = [f'r{i}' for i in range(r)]
    out = [HEADER, f'/// <summary>HLSL {name}: {r} rows of {row}, indexed m[row][column].</summary>',
           '[StructLayout(LayoutKind.Sequential)]', f'public struct {name}', '{']
    out.append(f'    public {row} ' + ', '.join(rows) + ';')
    out.append(f'    public {name}({", ".join(f"{row} {x}" for x in rows)}) {{ {" ".join(f"this.{x} = {x};" for x in rows)} }}')
    if r * c > 1 and c > 1:
        params = [f'{scalar} m{i}{j}' for i in range(r) for j in range(c)]
        assigns = [f'r{i} = new {row}({", ".join(f"m{i}{j}" for j in range(c))});' for i in range(r)]
        out.append(f'    public {name}({", ".join(params)}) {{ {" ".join(assigns)} }}')
    out.append(f'    public {name}({scalar} v) {{ {" ".join(f"{x} = v;" for x in rows)} }}')
    out.append(f'    public static implicit operator {name}({scalar} v) => new {name}(v);')
    out.append(f'    public {row} this[int i]')
    out.append('    {')
    out.append('        readonly get => i switch { ' + ', '.join(f'{i} => r{i}' for i in range(r)) + ', _ => throw new IndexOutOfRangeException() };')
    out.append('        set { switch (i) { ' + ' '.join(f'case {i}: r{i} = value; break;' for i in range(r)) + ' default: throw new IndexOutOfRangeException(); } }')
    out.append('    }')
    out.append(f'    public {row} this[uint i] {{ readonly get => this[(int)i]; set => this[(int)i] = value; }}')
    for i in range(r):
        for j in range(c):
            out.append(f'    public {scalar} _m{i}{j} {{ readonly get => r{i}.{COMPONENTS[j]}; set => r{i}.{COMPONENTS[j]} = value; }}')
            out.append(f'    public {scalar} _{i + 1}{j + 1} {{ readonly get => r{i}.{COMPONENTS[j]}; set => r{i}.{COMPONENTS[j]} = value; }}')
    # truncation from bigger matrices, and conversion between scalar types of the same shape
    for other in MATRIX_SCALARS:
        for rr in range(r, 5):
            for cc in range(c, 5):
                if other == scalar and rr == r and cc == c:
                    continue
                src = mat(other, rr, cc)
                target_row = row
                body = ', '.join(f'({target_row})v.r{i}' if not (other == scalar and cc == c) else f'v.r{i}' for i in range(r))
                out.append(f'    public static explicit operator {name}({src} v) => new {name}({body});')
    if scalar != 'bool':
        for op in ['+', '-', '*', '/', '%']:
            out.append(f'    public static {name} operator {op}({name} a, {name} b) => new {name}({", ".join(f"a.r{i} {op} b.r{i}" for i in range(r))});')
            out.append(f'    public static {name} operator {op}({name} a, {scalar} b) => new {name}({", ".join(f"a.r{i} {op} b" for i in range(r))});')
            out.append(f'    public static {name} operator {op}({scalar} a, {name} b) => new {name}({", ".join(f"a {op} b.r{i}" for i in range(r))});')
        out.append(f'    public static {name} operator -({name} a) => new {name}({", ".join(f"-a.r{i}" for i in range(r))});')
    out.append('}')
    return '\n'.join(out) + '\n'

def emit_matrix_intrinsics():
    out = [HEADER, 'public static partial class Intrinsics', '{']
    def t(r, c):
        if r == 1 and c == 1: return 'float'
        if r == 1: return f'float{c}'
        if c == 1: return f'float{r}'
        return mat('float', r, c)
    sizes = (1, 2, 3, 4)
    for r in sizes:
        for k in sizes:
            for c in sizes:
                # vector * matrix, matrix * vector, matrix * matrix, and a row times a column (a dot product)
                if k == 1 or (r == 1 and c == 1 and k == 1):
                    continue
                a, bb, res = t(r, k), t(k, c), t(r, c)
                # vector * matrix, matrix * vector, matrix * matrix, dot for 1xk * kx1
                if r == 1 and c == 1:
                    body = ' + '.join(f'a.{COMPONENTS[i]} * b.{COMPONENTS[i]}' for i in range(k))
                elif r == 1:
                    body = ' + '.join(f'a.{COMPONENTS[i]} * b.r{i}' for i in range(k))
                elif c == 1:
                    body = f'new float{r}(' + ', '.join(f'dot(a.r{i}, b)' if k > 1 else f'a.r{i} * b' for i in range(r)) + ')'
                else:
                    body = f'new {res}(' + ', '.join(
                        ' + '.join(f'a.r{i}.{COMPONENTS[j]} * b.r{j}' for j in range(k)) if k > 1 else f'a.r{i} * b.r0'
                        for i in range(r)) + ')'
                out.append(f'    public static {res} mul({a} a, {bb} b) => {body};')
    for r in (2, 3, 4):
        for c in (2, 3, 4):
            m = mat('float', r, c)
            out.append(f'    public static {m} mul(float a, {m} b) => a * b;')
            out.append(f'    public static {m} mul({m} a, float b) => a * b;')
            tr = mat('float', c, r)
            body = f'new {tr}(' + ', '.join(f'new float{r}(' + ', '.join(f'm.r{i}.{COMPONENTS[j]}' for i in range(r)) + ')' for j in range(c)) + ')'
            out.append(f'    public static {tr} transpose({m} m) => {body};')
    for n in (2, 3, 4):
        out.append(f'    public static float{n} mul(float a, float{n} b) => a * b;')
        out.append(f'    public static float{n} mul(float{n} a, float b) => a * b;')
    out.append('    public static float mul(float a, float b) => a * b;')
    out.append('    public static float determinant(float2x2 m) => m._m00 * m._m11 - m._m01 * m._m10;')
    out.append('    public static float determinant(float3x3 m) => dot(m.r0, cross(m.r1, m.r2));')
    out.append('    public static float determinant(float4x4 m) => throw new NotSupportedException("determinant of a 4x4 runs on the GPU");')
    out.append('}')
    return '\n'.join(out) + '\n'

# -- intrinsics --------------------------------------------------------------------------------

def emit_intrinsics():
    out = [HEADER + '\n/// <summary>HLSL intrinsic functions. <c>using static Csl.Types.Intrinsics;</c> in a shader file, then write them as in HLSL.</summary>\npublic static partial class Intrinsics\n{']
    def comp(fn, result, n, args):
        if n == 1:
            return fn(*args)
        parts = [fn(*[f'{a}.{c}' for a in args]) for c in COMPONENTS[:n]]
        return f'new {vec(result, n)}({", ".join(parts)})'
    unary_float = {
        'abs': 'MathF.Abs({0})', 'floor': 'MathF.Floor({0})', 'ceil': 'MathF.Ceiling({0})',
        'round': 'MathF.Round({0}, MidpointRounding.ToEven)', 'trunc': 'MathF.Truncate({0})',
        'frac': '({0} - MathF.Floor({0}))', 'sqrt': 'MathF.Sqrt({0})', 'rsqrt': '(1f / MathF.Sqrt({0}))',
        'exp': 'GpuExp({0})', 'exp2': 'MathF.Pow(2f, {0})', 'log': 'GpuLog({0})', 'log2': 'MathF.Log2({0})',
        'log10': 'GpuLog10({0})', 'sin': 'GpuSin({0})', 'cos': 'GpuCos({0})', 'tan': 'GpuTan({0})',
        'asin': 'MathF.Asin({0})', 'acos': 'MathF.Acos({0})', 'atan': 'MathF.Atan({0})',
        'sinh': 'MathF.Sinh({0})', 'cosh': 'MathF.Cosh({0})', 'tanh': 'MathF.Tanh({0})',
        'saturate': 'Saturate({0})', 'rcp': '(1f / {0})',
        'radians': '({0} * (MathF.PI / 180f))', 'degrees': '({0} * (180f / MathF.PI))',
    }
    for fn, body in unary_float.items():
        for n in (1, 2, 3, 4):
            out.append(f'    public static {vec("float", n)} {fn}({vec("float", n)} v) => {comp(lambda a: body.format(a), "float", n, ["v"])};')
    for n in (1, 2, 3, 4):
        out.append(f'    public static {vec("int", n)} sign({vec("float", n)} v) => {comp(lambda a: f"MathF.Sign({a})", "int", n, ["v"])};')
        out.append(f'    public static {vec("int", n)} sign({vec("int", n)} v) => {comp(lambda a: f"Math.Sign({a})", "int", n, ["v"])};')
        out.append(f'    public static {vec("int", n)} abs({vec("int", n)} v) => {comp(lambda a: f"Math.Abs({a})", "int", n, ["v"])};')
        out.append(f'    public static {vec("bool", n)} isnan({vec("float", n)} v) => {comp(lambda a: f"float.IsNaN({a})", "bool", n, ["v"])};')
        out.append(f'    public static {vec("bool", n)} isinf({vec("float", n)} v) => {comp(lambda a: f"float.IsInfinity({a})", "bool", n, ["v"])};')
        out.append(f'    public static {vec("bool", n)} isfinite({vec("float", n)} v) => {comp(lambda a: f"float.IsFinite({a})", "bool", n, ["v"])};')
        out.append(f'    public static void clip({vec("float", n)} v) {{ if ({" || ".join(f"v.{c} < 0f" for c in COMPONENTS[:n]) if n > 1 else "v < 0f"}) discard(); }}')
        out.append(f'    public static {vec("float", n)} modf({vec("float", n)} v, out {vec("float", n)} ip) {{ ip = trunc(v); return v - ip; }}')
        out.append(f'    public static {vec("float", n)} frexp({vec("float", n)} v, out {vec("float", n)} exponent) => throw new NotSupportedException();')
        out.append(f'    public static void sincos({vec("float", n)} v, out {vec("float", n)} s, out {vec("float", n)} c) {{ s = sin(v); c = cos(v); }}')
    binary_float = {
        'pow': 'MathF.Pow({0}, {1})', 'atan2': 'MathF.Atan2({0}, {1})', 'fmod': '({0} % {1})',
        'step': '({1} >= {0} ? 1f : 0f)', 'ldexp': '({0} * MathF.Pow(2f, {1}))',
    }
    for fn, body in binary_float.items():
        for n in (1, 2, 3, 4):
            out.append(f'    public static {vec("float", n)} {fn}({vec("float", n)} a, {vec("float", n)} b) => {comp(lambda a, b: body.format(a, b), "float", n, ["a", "b"])};')
    # D3D's min and max return the other operand for a NaN (IEEE minNum); clamp is max then min.
    for scalar, mn, mx in (('float', 'MinNum', 'MaxNum'), ('int', 'Math.Min', 'Math.Max'), ('uint', 'Math.Min', 'Math.Max'), ('double', 'MinNum', 'MaxNum')):
        for n in (1, 2, 3, 4):
            v = vec(scalar, n)
            out.append(f'    public static {v} min({v} a, {v} b) => {comp(lambda a, b: f"{mn}({a}, {b})", scalar, n, ["a", "b"])};')
            out.append(f'    public static {v} max({v} a, {v} b) => {comp(lambda a, b: f"{mx}({a}, {b})", scalar, n, ["a", "b"])};')
            out.append(f'    public static {v} clamp({v} v, {v} lo, {v} hi) => {comp(lambda v, lo, hi: f"{mn}({mx}({v}, {lo}), {hi})", scalar, n, ["v", "lo", "hi"])};')
    for n in (1, 2, 3, 4):
        f = vec('float', n)
        # As the GPU computes it (measured: CslPrecision): mad(b - a, s, a), fused.
        out.append(f'    public static {f} lerp({f} a, {f} b, {f} s) => {comp(lambda a, b, s: f"MathF.FusedMultiplyAdd({b} - {a}, {s}, {a})", "float", n, ["a", "b", "s"])};')
        out.append(f'    public static {f} smoothstep({f} lo, {f} hi, {f} v) => {comp(lambda lo, hi, v: f"SmoothStep({lo}, {hi}, {v})", "float", n, ["lo", "hi", "v"])};')
        # The GPU runs mad as a fused multiply-add (measured: CslPrecision).
        out.append(f'    public static {f} mad({f} a, {f} b, {f} c) => {comp(lambda a, b, c: f"MathF.FusedMultiplyAdd({a}, {b}, {c})", "float", n, ["a", "b", "c"])};')
        i = vec('int', n); u = vec('uint', n)
        out.append(f'    public static {i} mad({i} a, {i} b, {i} c) => a * b + c;')
        out.append(f'    public static {u} mad({u} a, {u} b, {u} c) => a * b + c;')
        out.append(f'    public static {vec("double", n)} fma({vec("double", n)} a, {vec("double", n)} b, {vec("double", n)} c) => a * b + c;')
        # bit casts
        out.append(f'    public static {f} asfloat({u} v) => {comp(lambda a: f"BitConverter.Int32BitsToSingle((int){a})", "float", n, ["v"])};')
        out.append(f'    public static {f} asfloat({i} v) => {comp(lambda a: f"BitConverter.Int32BitsToSingle({a})", "float", n, ["v"])};')
        out.append(f'    public static {f} asfloat({f} v) => v;')
        out.append(f'    public static {u} asuint({f} v) => {comp(lambda a: f"(uint)BitConverter.SingleToInt32Bits({a})", "uint", n, ["v"])};')
        out.append(f'    public static {u} asuint({i} v) => {comp(lambda a: f"(uint){a}", "uint", n, ["v"])};')
        out.append(f'    public static {u} asuint({u} v) => v;')
        out.append(f'    public static {i} asint({f} v) => {comp(lambda a: f"BitConverter.SingleToInt32Bits({a})", "int", n, ["v"])};')
        out.append(f'    public static {i} asint({u} v) => {comp(lambda a: f"(int){a}", "int", n, ["v"])};')
        out.append(f'    public static {i} asint({i} v) => v;')
        out.append(f'    public static {f} f16tof32({u} v) => {comp(lambda a: f"(float)BitConverter.UInt16BitsToHalf((ushort)({a} & 0xFFFF))", "float", n, ["v"])};')
        out.append(f'    public static {u} f32tof16({f} v) => {comp(lambda a: f"(uint)BitConverter.HalfToUInt16Bits((Half){a})", "uint", n, ["v"])};')
        out.append(f'    public static {u} countbits({u} v) => {comp(lambda a: f"(uint)System.Numerics.BitOperations.PopCount({a})", "uint", n, ["v"])};')
        out.append(f'    public static {u} firstbitlow({u} v) => {comp(lambda a: f"FirstBitLow({a})", "uint", n, ["v"])};')
        out.append(f'    public static {u} firstbithigh({u} v) => {comp(lambda a: f"FirstBitHigh({a})", "uint", n, ["v"])};')
        out.append(f'    public static {i} firstbithigh({i} v) => {comp(lambda a: f"(int)FirstBitHigh((uint){a})", "int", n, ["v"])};')
        out.append(f'    public static {u} reversebits({u} v) => {comp(lambda a: f"ReverseBits({a})", "uint", n, ["v"])};')
    out.append('    public static double asdouble(uint low, uint high) => BitConverter.Int64BitsToDouble((long)(((ulong)high << 32) | low));')
    out.append('    private static float SmoothStep(float lo, float hi, float v) { var x = Math.Clamp((v - lo) / (hi - lo), 0f, 1f); return x * x * (3f - 2f * x); }')
    out.append('    private static uint FirstBitLow(uint v) => v == 0 ? uint.MaxValue : (uint)System.Numerics.BitOperations.TrailingZeroCount(v);')
    out.append('    private static uint FirstBitHigh(uint v) => v == 0 ? uint.MaxValue : (uint)(31 - System.Numerics.BitOperations.LeadingZeroCount(v));')
    out.append('    private static uint ReverseBits(uint v) { uint r = 0; for (int i = 0; i < 32; i++) { r = (r << 1) | (v & 1); v >>= 1; } return r; }')
    out.append('    private static float Saturate(float v) => v > 0f ? (v < 1f ? v : 1f) : 0f;')
    out.append('    private static float MinNum(float a, float b) => float.IsNaN(a) ? b : float.IsNaN(b) ? a : MathF.Min(a, b);')
    out.append('    private static float MaxNum(float a, float b) => float.IsNaN(a) ? b : float.IsNaN(b) ? a : MathF.Max(a, b);')
    out.append('    private static double MinNum(double a, double b) => double.IsNaN(a) ? b : double.IsNaN(b) ? a : Math.Min(a, b);')
    out.append('    private static double MaxNum(double a, double b) => double.IsNaN(a) ? b : double.IsNaN(b) ? a : Math.Max(a, b);')
    # Derivatives: the difference with the neighbour lane of the 2x2 quad (Csl.Cpu.Lane).
    for n in (1, 2, 3, 4):
        f = vec('float', n)
        pack = {1: 'new float4(v, 0f, 0f, 0f)', 2: 'new float4(v.x, v.y, 0f, 0f)', 3: 'new float4(v.x, v.y, v.z, 0f)', 4: 'v'}[n]
        unpack = {1: 'd.x', 2: 'd.xy', 3: 'd.xyz', 4: 'd'}[n]
        for name, call, part in (('ddx', 'Derivatives', 'Ddx'), ('ddy', 'Derivatives', 'Ddy'),
                                 ('ddx_coarse', 'Current!.DerivativesCoarse', 'Ddx'), ('ddy_coarse', 'Current!.DerivativesCoarse', 'Ddy'),
                                 ('ddx_fine', 'Current!.DerivativesFine', 'Ddx'), ('ddy_fine', 'Current!.DerivativesFine', 'Ddy')):
            out.append(f'    public static {f} {name}({f} v) {{ var d = Csl.Cpu.Lane.{call}({pack}).{part}; return {unpack}; }}')
        out.append(f'    public static {f} fwidth({f} v) {{ var (x, y) = Csl.Cpu.Lane.Derivatives({pack}); var d = abs(x) + abs(y); return {unpack}; }}')
    for n in (2, 3, 4):
        comps = COMPONENTS[:n]
        f = f'float{n}'
        # dp2/dp3/dp4 as the GPU runs them (measured: CslPrecision): x*x', then fused multiply-adds in order.
        chain = 'a.x * b.x'
        for c in comps[1:]:
            chain = f'MathF.FusedMultiplyAdd(a.{c}, b.{c}, {chain})'
        out.append(f'    public static float dot({f} a, {f} b) => {chain};')
        out.append(f'    public static int dot(int{n} a, int{n} b) => {" + ".join(f"a.{c} * b.{c}" for c in comps)};')
        out.append(f'    public static uint dot(uint{n} a, uint{n} b) => {" + ".join(f"a.{c} * b.{c}" for c in comps)};')
        out.append(f'    public static float length({f} v) => MathF.Sqrt(dot(v, v));')
        out.append(f'    public static float distance({f} a, {f} b) => length(a - b);')
        out.append(f'    public static {f} normalize({f} v) => v * (1f / MathF.Sqrt(dot(v, v)));')
        out.append(f'    public static {f} reflect({f} i, {f} n) => i - 2f * dot(i, n) * n;')
        out.append(f'    public static {f} refract({f} i, {f} n, float eta) {{ var c = dot(-i, n); var k = 1f - eta * eta * (1f - c * c); return k < 0f ? new {f}(0f) : eta * i + (eta * c - MathF.Sqrt(k)) * n; }}')
        out.append(f'    public static {f} faceforward({f} n, {f} i, {f} ng) => dot(i, ng) < 0f ? n : -n;')
        for scalar in NUMERIC:
            if scalar == 'half':
                out.append(f'    public static bool any(half{n} v) => {" || ".join(f"(float)v.{c} != 0f" for c in comps)};')
                out.append(f'    public static bool all(half{n} v) => {" && ".join(f"(float)v.{c} != 0f" for c in comps)};')
                continue
            out.append(f'    public static bool any({scalar}{n} v) => {" || ".join(f"v.{c} != 0" for c in comps)};')
            out.append(f'    public static bool all({scalar}{n} v) => {" && ".join(f"v.{c} != 0" for c in comps)};')
        out.append(f'    public static bool any(bool{n} v) => {" || ".join(f"v.{c}" for c in comps)};')
        out.append(f'    public static bool all(bool{n} v) => {" && ".join(f"v.{c}" for c in comps)};')
    for scalar in ('bool', 'float', 'int', 'uint', 'double'):
        cond = 'v' if scalar == 'bool' else 'v != 0'
        out.append(f'    public static bool any({scalar} v) => {cond};')
        out.append(f'    public static bool all({scalar} v) => {cond};')
    out.append('    public static float3 cross(float3 a, float3 b) => new float3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);')
    out.append('    public static float4 lit(float nDotL, float nDotH, float m) => new float4(1f, MathF.Max(0f, nDotL), nDotL < 0f || nDotH < 0f ? 0f : MathF.Pow(nDotH, m), 1f);')
    out.append('    public static float4 dst(float4 a, float4 b) => new float4(1f, a.y * b.y, a.z, b.w);')
    out.append('    public static float noise(float v) => throw new NotSupportedException();')
    out.append('}')
    return '\n'.join(out) + '\n'

# -- resources ---------------------------------------------------------------------------------

TEXTURES = {
    # name: (coordinate size for Sample, Load location size (with mip), array?, supports Sample, index size)
    'Texture1D': (1, 2, 1),
    'Texture1DArray': (2, 3, 2),
    'Texture2D': (2, 3, 2),
    'Texture2DArray': (3, 4, 3),
    'Texture3D': (3, 4, 3),
    'TextureCube': (3, None, None),
    'TextureCubeArray': (4, None, None),
}

def emit_resources():
    out = [HEADER, """using Csl.Cpu;

/// <summary>
/// Shader resources: handles, as on the GPU, where they are accessed. Given CPU data (a CpuTexture, an
/// array), their members also run on the CPU (Csl.Cpu.ResourceOps), for shader code run there.
/// </summary>
internal static class GpuOnly
{
    public static Exception Exception() => new NotSupportedException("Shader resources are only accessed on the GPU");
}

/// <summary>A sampler: on the CPU, its description (Stride's defaults when it has none).</summary>
public readonly struct SamplerState
{
    private readonly SamplerDescription? description;
    public SamplerState(SamplerDescription description) { this.description = description; }
    public SamplerDescription Description => description ?? SamplerDescription.Default;
    public bool HasDescription => description != null;
}

public readonly struct SamplerComparisonState
{
    private readonly SamplerDescription? description;
    public SamplerComparisonState(SamplerDescription description) { this.description = description; }
    public SamplerDescription Description => description ?? SamplerDescription.Default;
    public bool HasDescription => description != null;
}

/// <summary>Sample counts of a multisampled texture: Texture2DMS&lt;float4, Samples4&gt; is SDSL's Texture2DMS&lt;float4, 4&gt;.</summary>
public readonly struct Samples1 { }
public readonly struct Samples2 { }
public readonly struct Samples4 { }
public readonly struct Samples8 { }
public readonly struct Samples16 { }
public readonly struct Samples32 { }
"""]
    def fv(n): return vec('float', n)
    def iv(n): return vec('int', n)
    def uv(n): return vec('uint', n)
    G = 'throw GpuOnly.Exception()'
    # spatial dimensions and array flag of each texture; None: cube maps, run through their own operations.
    SHAPE = {'Texture1D': (1, False), 'Texture1DArray': (1, True), 'Texture2D': (2, False), 'Texture2DArray': (2, True),
             'Texture3D': (3, False), 'TextureCube': None, 'TextureCubeArray': None,
             'RWTexture1D': (1, False), 'RWTexture1DArray': (1, True), 'RWTexture2D': (2, False), 'RWTexture2DArray': (2, True),
             'RWTexture3D': (3, False), 'RasterizerOrderedTexture2D': (2, False)}
    def data_members(name, generic, kind):
        struct = name + ('<T>' if generic else '')
        if kind == 'texture':
            return [f'    private readonly object? cpu;',
                    f'    /// <summary>A texture whose texels are on the CPU, for shader code run there.</summary>',
                    f'    public {name}(CpuTexture texture) {{ cpu = texture; }}',
                    f'    public CpuTexture? CpuData => cpu as CpuTexture;']
        el = 'T' if generic else 'float4'
        return [f'    private readonly object? cpu;',
                f'    /// <summary>A buffer whose elements are on the CPU, for shader code run there.</summary>',
                f'    public {name}({el}[] data) {{ cpu = data; }}',
                f'    public {el}[]? CpuData => cpu as {el}[];']
    for name, (coord, load, index) in TEXTURES.items():
        shape = SHAPE[name]
        for generic in (True, False):
            t = 'T' if generic else 'float4'
            header = f'public readonly struct {name}<T> where T : struct' if generic else f'/// <summary>{name} of float4, as SDSL writes it without an element type.</summary>\npublic readonly struct {name}'
            out.append(header)
            out.append('{')
            out.extend(data_members(name, generic, 'texture'))
            D, A = shape if shape else (0, False)
            a = 'true' if A else 'false'
            # Cube maps: the face the direction points at, sampled as a 2D slice (ResourceOps.SampleCube).
            cube = name.startswith('TextureCube')
            ca = 'true' if name == 'TextureCubeArray' else 'false'
            def body(expr):
                return expr if shape else G
            if index is not None:
                for v in (iv(index), uv(index)):
                    out.append(f'    public {t} this[{v} location] => {body(f"ResourceOps.Load<{t}>(cpu, {D}, {a}, ResourceOps.I(location), false)")};')
                for v in (iv(load), uv(load)):
                    out.append(f'    public {t} Load({v} location) => {body(f"ResourceOps.Load<{t}>(cpu, {D}, {a}, ResourceOps.I(location), true)")};')
                    out.append(f'    public {t} Load({v} location, {iv(index if name != "Texture1DArray" and name != "Texture2DArray" else index - 1)} offset) => {body(f"ResourceOps.Load<{t}>(cpu, {D}, {a}, ResourceOps.I(location), true, ResourceOps.I(offset))")};')
            spatial = coord if name not in ('Texture1DArray', 'Texture2DArray', 'TextureCubeArray') else coord - 1
            offset = iv(spatial)
            for s in ('Sample', 'SampleLevel', 'SampleBias', 'SampleGrad'):
                extra = {'Sample': '', 'SampleLevel': ', float lod', 'SampleBias': ', float bias', 'SampleGrad': f', {fv(spatial)} ddx, {fv(spatial)} ddy'}[s]
                args = {'Sample': 'ResourceOps.Level.Implicit', 'SampleLevel': 'ResourceOps.Level.Explicit, lod', 'SampleBias': 'ResourceOps.Level.Bias, bias',
                        'SampleGrad': 'ResourceOps.Level.Gradient, 0f'}[s]
                grads = ', ddx: ResourceOps.F(ddx), ddy: ResourceOps.F(ddy)' if s == 'SampleGrad' else ''
                if cube:
                    out.append(f'    public {t} {s}(SamplerState sampler, {fv(coord)} location{extra}) => ResourceOps.SampleCube<{t}>(cpu, sampler, {ca}, ResourceOps.F(location), {args}{grads});')
                else:
                    out.append(f'    public {t} {s}(SamplerState sampler, {fv(coord)} location{extra}) => {body(f"ResourceOps.Sample<{t}>(cpu, sampler, {D}, {a}, ResourceOps.F(location), {args}{grads})")};')
                if not name.startswith('TextureCube'):
                    out.append(f'    public {t} {s}(SamplerState sampler, {fv(coord)} location{extra}, {offset} offset) => {body(f"ResourceOps.Sample<{t}>(cpu, sampler, {D}, {a}, ResourceOps.F(location), {args}, offset: ResourceOps.I(offset){grads})")};')
            for s in ('SampleCmp', 'SampleCmpLevelZero'):
                zero = 'true' if s == 'SampleCmpLevelZero' else 'false'
                if cube:
                    out.append(f'    public float {s}(SamplerComparisonState sampler, {fv(coord)} location, float compare) => ResourceOps.SampleCmpCube(cpu, sampler, {ca}, ResourceOps.F(location), compare, {zero});')
                else:
                    out.append(f'    public float {s}(SamplerComparisonState sampler, {fv(coord)} location, float compare) => {body(f"ResourceOps.SampleCmp(cpu, sampler, {D}, {a}, ResourceOps.F(location), compare, {zero})")};')
                if not name.startswith('TextureCube'):
                    out.append(f'    public float {s}(SamplerComparisonState sampler, {fv(coord)} location, float compare, {offset} offset) => {body(f"ResourceOps.SampleCmp(cpu, sampler, {D}, {a}, ResourceOps.F(location), compare, {zero}, ResourceOps.I(offset))")};')
            if name in ('Texture2D', 'Texture2DArray', 'TextureCube', 'TextureCubeArray'):
                for g in ('Gather', 'GatherRed', 'GatherGreen', 'GatherBlue', 'GatherAlpha'):
                    channel = {'Gather': 0, 'GatherRed': 0, 'GatherGreen': 1, 'GatherBlue': 2, 'GatherAlpha': 3}[g]
                    if cube:
                        out.append(f'    public float4 {g}(SamplerState sampler, {fv(coord)} location) => ResourceOps.GatherCube(cpu, sampler, {ca}, ResourceOps.F(location), {channel});')
                    else:
                        out.append(f'    public float4 {g}(SamplerState sampler, {fv(coord)} location) => {body(f"ResourceOps.Gather(cpu, sampler, {a}, ResourceOps.F(location), {channel})")};')
                    if not name.startswith('TextureCube'):
                        out.append(f'    public float4 {g}(SamplerState sampler, {fv(coord)} location, {offset} offset) => {body(f"ResourceOps.Gather(cpu, sampler, {a}, ResourceOps.F(location), {channel}, ResourceOps.I(offset))")};')
                        if g != 'Gather':
                            out.append(f'    public float4 {g}(SamplerState sampler, {fv(coord)} location, {offset} offset1, {offset} offset2, {offset} offset3, {offset} offset4) => {G};')
                for g in ('GatherCmp', 'GatherCmpRed'):
                    call = f'ResourceOps.GatherCmpCube(cpu, sampler, {ca}, ResourceOps.F(location), compare)' if cube else body(f'ResourceOps.GatherCmp(cpu, sampler, {a}, ResourceOps.F(location), compare)')
                    out.append(f'    public float4 {g}(SamplerComparisonState sampler, {fv(coord)} location, float compare) => {call};')
            if name == 'TextureCube':
                out.append(f'    public float CalculateLevelOfDetail(SamplerState sampler, {fv(spatial)} location) => ResourceOps.CalculateLevelOfDetailCube(cpu, sampler, ResourceOps.F(location));')
            else:
                out.append(f'    public float CalculateLevelOfDetail(SamplerState sampler, {fv(spatial)} location) => {body(f"ResourceOps.CalculateLevelOfDetail(cpu, sampler, {D}, ResourceOps.F(location))")};')
            dims = {'Texture1D': ['width'], 'Texture1DArray': ['width', 'elements'], 'Texture2D': ['width', 'height'],
                    'Texture2DArray': ['width', 'height', 'elements'], 'Texture3D': ['width', 'height', 'depth'],
                    'TextureCube': ['width', 'height'], 'TextureCubeArray': ['width', 'height', 'elements']}[name]
            if name == 'TextureCube':
                # A face's size: a 2D slice's.
                out.extend(dimensions(dims, 2, 'false', True, with_levels=True))
            else:
                out.extend(dimensions(dims, D, a, shape is not None, with_levels=True))
            out.append('}')
            out.append('')
    # RW textures
    for name, (coord, _, index) in [('RWTexture1D', (1, None, 1)), ('RWTexture1DArray', (2, None, 2)), ('RWTexture2D', (2, None, 2)), ('RWTexture2DArray', (3, None, 3)), ('RWTexture3D', (3, None, 3)),
                                    ('RasterizerOrderedTexture2D', (2, None, 2))]:
        D, A = SHAPE[name]
        a = 'true' if A else 'false'
        for generic in (True, False):
            t = 'T' if generic else 'float4'
            out.append(f'public readonly struct {name}<T> where T : struct' if generic else f'public readonly struct {name}')
            out.append('{')
            out.extend(data_members(name, generic, 'texture'))
            for v in (iv(index), uv(index)):
                out.append(f'    public {t} this[{v} location] {{ get => ResourceOps.Load<{t}>(cpu, {D}, {a}, ResourceOps.I(location), false); set => ResourceOps.Store(cpu, {D}, {a}, ResourceOps.I(location), value); }}')
                out.append(f'    public {t} Load({v} location) => ResourceOps.Load<{t}>(cpu, {D}, {a}, ResourceOps.I(location), false);')
            dims = {1: ['width'], 2: ['width', 'height'], 3: ['width', 'height', 'depth']}[index]
            if 'Array' in name:
                dims = dims[:-1] + ['elements']
            out.extend(dimensions(dims, D, a, True, with_levels=False))
            out.append('}')
            out.append('')
    # multisampled: on the GPU only
    for name, index in (('Texture2DMS', 2), ('Texture2DMSArray', 3)):
        for arity in (1, 2):
            params = 'T' if arity == 1 else 'T, TSamples'
            out.append(f'public readonly struct {name}<{params}> where T : struct' + (' where TSamples : struct' if arity == 2 else ''))
            out.append('{')
            for v in (iv(index), uv(index)):
                out.append(f'    public T Load({v} location, int sample) => {G};')
                out.append(f'    public T Load({v} location, int sample, {iv(2)} offset) => {G};')
            dims = ['width', 'height'] + (['elements'] if 'Array' in name else [])
            for ty in ('uint', 'float'):
                out.append(f'    public void GetDimensions({", ".join(f"out {ty} {d}" for d in dims)}, out {ty} samples) => {G};')
            out.append(f'    public float2 GetSamplePosition(int sample) => {G};')
            out.append('}')
            out.append('')
        out.append(f'public readonly struct {name}')
        out.append('{')
        for v in (iv(index), uv(index)):
            out.append(f'    public float4 Load({v} location, int sample) => {G};')
        dims = ['width', 'height'] + (['elements'] if 'Array' in name else [])
        for ty in ('uint', 'float'):
            out.append(f'    public void GetDimensions({", ".join(f"out {ty} {d}" for d in dims)}, out {ty} samples) => {G};')
        out.append('}')
        out.append('')
    # buffers
    for name, rw, structured in (('Buffer', False, False), ('RWBuffer', True, False), ('StructuredBuffer', False, True), ('RWStructuredBuffer', True, True),
                                 ('RasterizerOrderedBuffer', True, False), ('RasterizerOrderedStructuredBuffer', True, True)):
        for generic in (True, False) if not structured else (True,):
            t = 'T' if generic else 'float4'
            out.append(f'public readonly struct {name}<T> where T : struct' if generic else f'public readonly struct {name}')
            out.append('{')
            out.extend(data_members(name, generic, 'buffer'))
            for v in ('int', 'uint'):
                if rw:
                    out.append(f'    public {t} this[{v} index] {{ get => ResourceOps.BufferLoad<{t}>(cpu, index); set => ResourceOps.BufferStore(cpu, index, value); }}')
                else:
                    out.append(f'    public {t} this[{v} index] => ResourceOps.BufferLoad<{t}>(cpu, index);')
                out.append(f'    public {t} Load({v} index) => ResourceOps.BufferLoad<{t}>(cpu, index);')
            if structured:
                out.append(f'    public void GetDimensions(out uint count, out uint stride) {{ count = ResourceOps.BufferCount<{t}>(cpu); stride = ResourceOps.BufferStride<{t}>(); }}')
                if rw:
                    out.append(f'    public uint IncrementCounter() => {G};')
                    out.append(f'    public uint DecrementCounter() => {G};')
            else:
                out.append(f'    public void GetDimensions(out uint count) => count = ResourceOps.BufferCount<{t}>(cpu);')
            out.append('}')
            out.append('')
    out.append(f"""public readonly struct AppendStructuredBuffer<T> where T : struct
{{
    public void Append(T value) => {G};
    public void GetDimensions(out uint count, out uint stride) => {G};
}}

public readonly struct ConsumeStructuredBuffer<T> where T : struct
{{
    public T Consume() => {G};
    public void GetDimensions(out uint count, out uint stride) => {G};
}}
""")
    for name, rw in (('ByteAddressBuffer', False), ('RWByteAddressBuffer', True)):
        out.append(f'public readonly struct {name}')
        out.append('{')
        out.append('    private readonly object? cpu;')
        out.append('    /// <summary>A buffer whose 32-bit words are on the CPU, for shader code run there.</summary>')
        out.append(f'    public {name}(uint[] words) {{ cpu = words; }}')
        out.append('    public uint[]? CpuData => cpu as uint[];')
        for v in ('int', 'uint'):
            out.append(f'    public uint Load({v} address) => ResourceOps.LoadWord(cpu, address);')
            for k in (2, 3, 4):
                words = ', '.join(f'ResourceOps.LoadWord(cpu, address + {4 * i})' for i in range(k))
                out.append(f'    public uint{k} Load{k}({v} address) => new uint{k}({words});')
            if rw:
                out.append(f'    public void Store({v} address, uint value) => ResourceOps.StoreWord(cpu, address, value);')
                for k in (2, 3, 4):
                    stores = ' '.join(f'ResourceOps.StoreWord(cpu, address + {4 * i}, value.{COMPONENTS[i]});' for i in range(k))
                    out.append(f'    public void Store{k}({v} address, uint{k} value) {{ {stores} }}')
                for op in ('Add', 'And', 'Or', 'Xor', 'Min', 'Max', 'Exchange'):
                    out.append(f'    public void Interlocked{op}({v} address, uint value, out uint original) => {G};')
                    if op != 'Exchange':
                        out.append(f'    public void Interlocked{op}({v} address, uint value) => {G};')
                out.append(f'    public void InterlockedCompareExchange({v} address, uint compare, uint value, out uint original) => {G};')
                out.append(f'    public void InterlockedCompareStore({v} address, uint compare, uint value) => {G};')
        out.append('    public void GetDimensions(out uint bytes) => bytes = ResourceOps.BufferCount<uint>(cpu) * 4;')
        out.append('}')
        out.append('')
    return '\n'.join(out) + '\n'

def dimensions(dims, D, a, cpu, with_levels):
    """GetDimensions: the sizes the texture has (at mipLevel), as uint or float."""
    out = []
    G = 'throw GpuOnly.Exception()'
    names = {'width': 'w', 'height': 'h', 'depth': 'd', 'elements': 'd'}
    for ty in ('uint', 'float'):
        sig = ", ".join(f"out {ty} {d}" for d in dims)
        assign = ' '.join(f'{d} = {names[d]};' for d in dims)
        if cpu:
            out.append(f'    public void GetDimensions({sig}) {{ ResourceOps.Dimensions(cpu, {D}, {a}, 0, out var w, out var h, out var d, out _); {assign} }}')
        else:
            out.append(f'    public void GetDimensions({sig}) => {G};')
        if with_levels:
            if cpu:
                out.append(f'    public void GetDimensions(uint mipLevel, {sig}, out {ty} levels) {{ ResourceOps.Dimensions(cpu, {D}, {a}, mipLevel, out var w, out var h, out var d, out var l); {assign} levels = l; }}')
            else:
                out.append(f'    public void GetDimensions(uint mipLevel, {sig}, out {ty} levels) => {G};')
    return out

# -- write -------------------------------------------------------------------------------------

os.makedirs(OUT, exist_ok=True)
for old in os.listdir(OUT):
    if old.endswith('.g.cs'):
        os.remove(os.path.join(OUT, old))
# Not the partial Intrinsics: its handwritten half carries the attribute once for the type.
NON_USER = re.compile(r'^(public|internal)( readonly)?( static)? (struct|class) ', re.M)

def write(file, text):
    # Library code: the debugger's Just My Code steps over it, into the shader that calls it.
    text = NON_USER.sub(lambda m: '[System.Diagnostics.DebuggerNonUserCode]\n' + m.group(0), text)
    with open(os.path.join(OUT, file), 'w', newline='\n') as f:
        f.write(text)
write('half.g.cs', emit_half())
write('ScalarSwizzles.g.cs', emit_scalar_swizzles())
for scalar in SCALARS:
    for n in (2, 3, 4):
        write(f'{vec(scalar, n)}.g.cs', emit_vector(scalar, n))
for scalar in MATRIX_SCALARS:
    for r in (2, 3, 4):
        for c in (2, 3, 4):
            write(f'{mat(scalar, r, c)}.g.cs', emit_matrix(scalar, r, c))
write('Intrinsics.g.cs', emit_intrinsics())
write('Intrinsics.Matrices.g.cs', emit_matrix_intrinsics())
write('Resources.g.cs', emit_resources())
print('written', os.path.normpath(OUT))
