// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591, CS0660, CS0661
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL bool2x4: 2 rows of bool4, indexed m[row][column].</summary>
[StructLayout(LayoutKind.Sequential)]
public struct bool2x4
{
    public bool4 r0, r1;
    public bool2x4(bool4 r0, bool4 r1) { this.r0 = r0; this.r1 = r1; }
    public bool2x4(bool m00, bool m01, bool m02, bool m03, bool m10, bool m11, bool m12, bool m13) { r0 = new bool4(m00, m01, m02, m03); r1 = new bool4(m10, m11, m12, m13); }
    public bool2x4(bool v) { r0 = v; r1 = v; }
    public static implicit operator bool2x4(bool v) => new bool2x4(v);
    public bool4 this[int i]
    {
        readonly get => i switch { 0 => r0, 1 => r1, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: r0 = value; break; case 1: r1 = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public bool4 this[uint i] { readonly get => this[(int)i]; set => this[(int)i] = value; }
    public bool _m00 { readonly get => r0.x; set => r0.x = value; }
    public bool _11 { readonly get => r0.x; set => r0.x = value; }
    public bool _m01 { readonly get => r0.y; set => r0.y = value; }
    public bool _12 { readonly get => r0.y; set => r0.y = value; }
    public bool _m02 { readonly get => r0.z; set => r0.z = value; }
    public bool _13 { readonly get => r0.z; set => r0.z = value; }
    public bool _m03 { readonly get => r0.w; set => r0.w = value; }
    public bool _14 { readonly get => r0.w; set => r0.w = value; }
    public bool _m10 { readonly get => r1.x; set => r1.x = value; }
    public bool _21 { readonly get => r1.x; set => r1.x = value; }
    public bool _m11 { readonly get => r1.y; set => r1.y = value; }
    public bool _22 { readonly get => r1.y; set => r1.y = value; }
    public bool _m12 { readonly get => r1.z; set => r1.z = value; }
    public bool _23 { readonly get => r1.z; set => r1.z = value; }
    public bool _m13 { readonly get => r1.w; set => r1.w = value; }
    public bool _24 { readonly get => r1.w; set => r1.w = value; }
    public static explicit operator bool2x4(float2x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(float3x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(float4x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(half2x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(half3x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(half4x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(int2x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(int3x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(int4x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(uint2x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(uint3x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(uint4x4 v) => new bool2x4((bool4)v.r0, (bool4)v.r1);
    public static explicit operator bool2x4(bool3x4 v) => new bool2x4(v.r0, v.r1);
    public static explicit operator bool2x4(bool4x4 v) => new bool2x4(v.r0, v.r1);
}
