// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591, CS0660, CS0661
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL double2: 2 components of double.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct double2 : IEquatable<double2>
{
    public double x, y;
    public double2(double x, double y) { this.x = x; this.y = y; }
    public double2(double v) { x = v; y = v; }
    public static implicit operator double2(double v) => new double2(v);
    public static implicit operator double2(bool2 v) => new double2((v.x ? 1d : 0d), (v.y ? 1d : 0d));
    public static explicit operator double2(bool3 v) => new double2((v.x ? 1d : 0d), (v.y ? 1d : 0d));
    public static explicit operator double2(bool4 v) => new double2((v.x ? 1d : 0d), (v.y ? 1d : 0d));
    public static implicit operator double2(int2 v) => new double2((double)v.x, (double)v.y);
    public static explicit operator double2(int3 v) => new double2((double)v.x, (double)v.y);
    public static explicit operator double2(int4 v) => new double2((double)v.x, (double)v.y);
    public static implicit operator double2(uint2 v) => new double2((double)v.x, (double)v.y);
    public static explicit operator double2(uint3 v) => new double2((double)v.x, (double)v.y);
    public static explicit operator double2(uint4 v) => new double2((double)v.x, (double)v.y);
    public static implicit operator double2(half2 v) => new double2((double)(float)v.x, (double)(float)v.y);
    public static explicit operator double2(half3 v) => new double2((double)(float)v.x, (double)(float)v.y);
    public static explicit operator double2(half4 v) => new double2((double)(float)v.x, (double)(float)v.y);
    public static implicit operator double2(float2 v) => new double2((double)v.x, (double)v.y);
    public static explicit operator double2(float3 v) => new double2((double)v.x, (double)v.y);
    public static explicit operator double2(float4 v) => new double2((double)v.x, (double)v.y);
    public static explicit operator double2(double3 v) => new double2(v.x, v.y);
    public static explicit operator double2(double4 v) => new double2(v.x, v.y);
    public static explicit operator bool(double2 v) => (v.x != 0);
    public static explicit operator int(double2 v) => (int)v.x;
    public static explicit operator uint(double2 v) => (uint)v.x;
    public static explicit operator half(double2 v) => (half)(float)v.x;
    public static explicit operator float(double2 v) => (float)v.x;
    public static explicit operator double(double2 v) => v.x;
    public double this[int i]
    {
        get => i switch { 0 => x, 1 => y, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public double this[uint i] { get => this[(int)i]; set => this[(int)i] = value; }
    public static double2 operator +(double2 a, double2 b) => new double2((double)(a.x + b.x), (double)(a.y + b.y));
    public static double2 operator +(double2 a, double b) => new double2((double)(a.x + b), (double)(a.y + b));
    public static double2 operator +(double a, double2 b) => new double2((double)(a + b.x), (double)(a + b.y));
    public static double2 operator -(double2 a, double2 b) => new double2((double)(a.x - b.x), (double)(a.y - b.y));
    public static double2 operator -(double2 a, double b) => new double2((double)(a.x - b), (double)(a.y - b));
    public static double2 operator -(double a, double2 b) => new double2((double)(a - b.x), (double)(a - b.y));
    public static double2 operator *(double2 a, double2 b) => new double2((double)(a.x * b.x), (double)(a.y * b.y));
    public static double2 operator *(double2 a, double b) => new double2((double)(a.x * b), (double)(a.y * b));
    public static double2 operator *(double a, double2 b) => new double2((double)(a * b.x), (double)(a * b.y));
    public static double2 operator /(double2 a, double2 b) => new double2((double)(a.x / b.x), (double)(a.y / b.y));
    public static double2 operator /(double2 a, double b) => new double2((double)(a.x / b), (double)(a.y / b));
    public static double2 operator /(double a, double2 b) => new double2((double)(a / b.x), (double)(a / b.y));
    public static double2 operator %(double2 a, double2 b) => new double2((double)(a.x % b.x), (double)(a.y % b.y));
    public static double2 operator %(double2 a, double b) => new double2((double)(a.x % b), (double)(a.y % b));
    public static double2 operator %(double a, double2 b) => new double2((double)(a % b.x), (double)(a % b.y));
    public static double2 operator -(double2 a) => new double2((double)(-a.x), (double)(-a.y));
    public static double2 operator +(double2 a) => a;
    public static double2 operator ++(double2 a) => a + 1d;
    public static double2 operator --(double2 a) => a - 1d;
    public static bool2 operator <(double2 a, double2 b) => new bool2(a.x < b.x, a.y < b.y);
    public static bool2 operator <(double2 a, double b) => new bool2(a.x < b, a.y < b);
    public static bool2 operator <(double a, double2 b) => new bool2(a < b.x, a < b.y);
    public static bool2 operator >(double2 a, double2 b) => new bool2(a.x > b.x, a.y > b.y);
    public static bool2 operator >(double2 a, double b) => new bool2(a.x > b, a.y > b);
    public static bool2 operator >(double a, double2 b) => new bool2(a > b.x, a > b.y);
    public static bool2 operator <=(double2 a, double2 b) => new bool2(a.x <= b.x, a.y <= b.y);
    public static bool2 operator <=(double2 a, double b) => new bool2(a.x <= b, a.y <= b);
    public static bool2 operator <=(double a, double2 b) => new bool2(a <= b.x, a <= b.y);
    public static bool2 operator >=(double2 a, double2 b) => new bool2(a.x >= b.x, a.y >= b.y);
    public static bool2 operator >=(double2 a, double b) => new bool2(a.x >= b, a.y >= b);
    public static bool2 operator >=(double a, double2 b) => new bool2(a >= b.x, a >= b.y);
    public static bool2 operator ==(double2 a, double2 b) => new bool2(a.x == b.x, a.y == b.y);
    public static bool2 operator !=(double2 a, double2 b) => new bool2(a.x != b.x, a.y != b.y);
    public static bool2 operator ==(double2 a, double b) => new bool2(a.x == b, a.y == b);
    public static bool2 operator !=(double2 a, double b) => new bool2(a.x != b, a.y != b);
    public bool Equals(double2 other) => x.Equals(other.x) && y.Equals(other.y);
    public override bool Equals(object? obj) => obj is double2 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y);
    public override string ToString() => $"double2({x}, {y})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public readonly double2 xx => new double2(x, x);
    public double2 xy { readonly get => new double2(x, y); set { x = value.x; y = value.y; } }
    public double2 yx { readonly get => new double2(y, x); set { y = value.x; x = value.y; } }
    public readonly double2 yy => new double2(y, y);
    public readonly double3 xxx => new double3(x, x, x);
    public readonly double3 xxy => new double3(x, x, y);
    public readonly double3 xyx => new double3(x, y, x);
    public readonly double3 xyy => new double3(x, y, y);
    public readonly double3 yxx => new double3(y, x, x);
    public readonly double3 yxy => new double3(y, x, y);
    public readonly double3 yyx => new double3(y, y, x);
    public readonly double3 yyy => new double3(y, y, y);
    public readonly double4 xxxx => new double4(x, x, x, x);
    public readonly double4 xxxy => new double4(x, x, x, y);
    public readonly double4 xxyx => new double4(x, x, y, x);
    public readonly double4 xxyy => new double4(x, x, y, y);
    public readonly double4 xyxx => new double4(x, y, x, x);
    public readonly double4 xyxy => new double4(x, y, x, y);
    public readonly double4 xyyx => new double4(x, y, y, x);
    public readonly double4 xyyy => new double4(x, y, y, y);
    public readonly double4 yxxx => new double4(y, x, x, x);
    public readonly double4 yxxy => new double4(y, x, x, y);
    public readonly double4 yxyx => new double4(y, x, y, x);
    public readonly double4 yxyy => new double4(y, x, y, y);
    public readonly double4 yyxx => new double4(y, y, x, x);
    public readonly double4 yyxy => new double4(y, y, x, y);
    public readonly double4 yyyx => new double4(y, y, y, x);
    public readonly double4 yyyy => new double4(y, y, y, y);
    public double r { readonly get => x; set => x = value; }
    public double g { readonly get => y; set => y = value; }
    public readonly double2 rr => new double2(x, x);
    public double2 rg { readonly get => new double2(x, y); set { x = value.x; y = value.y; } }
    public double2 gr { readonly get => new double2(y, x); set { y = value.x; x = value.y; } }
    public readonly double2 gg => new double2(y, y);
    public readonly double3 rrr => new double3(x, x, x);
    public readonly double3 rrg => new double3(x, x, y);
    public readonly double3 rgr => new double3(x, y, x);
    public readonly double3 rgg => new double3(x, y, y);
    public readonly double3 grr => new double3(y, x, x);
    public readonly double3 grg => new double3(y, x, y);
    public readonly double3 ggr => new double3(y, y, x);
    public readonly double3 ggg => new double3(y, y, y);
    public readonly double4 rrrr => new double4(x, x, x, x);
    public readonly double4 rrrg => new double4(x, x, x, y);
    public readonly double4 rrgr => new double4(x, x, y, x);
    public readonly double4 rrgg => new double4(x, x, y, y);
    public readonly double4 rgrr => new double4(x, y, x, x);
    public readonly double4 rgrg => new double4(x, y, x, y);
    public readonly double4 rggr => new double4(x, y, y, x);
    public readonly double4 rggg => new double4(x, y, y, y);
    public readonly double4 grrr => new double4(y, x, x, x);
    public readonly double4 grrg => new double4(y, x, x, y);
    public readonly double4 grgr => new double4(y, x, y, x);
    public readonly double4 grgg => new double4(y, x, y, y);
    public readonly double4 ggrr => new double4(y, y, x, x);
    public readonly double4 ggrg => new double4(y, y, x, y);
    public readonly double4 gggr => new double4(y, y, y, x);
    public readonly double4 gggg => new double4(y, y, y, y);
}
