// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591, CS0660, CS0661
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL double4: 4 components of double.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct double4 : IEquatable<double4>
{
    public double x, y, z, w;
    public double4(double x, double y, double z, double w) { this.x = x; this.y = y; this.z = z; this.w = w; }
    public double4(double v) { x = v; y = v; z = v; w = v; }
    public double4(double p0, double p1, double2 p2) { x = p0; y = p1; z = p2.x; w = p2.y; }
    public double4(double p0, double2 p1, double p2) { x = p0; y = p1.x; z = p1.y; w = p2; }
    public double4(double p0, double3 p1) { x = p0; y = p1.x; z = p1.y; w = p1.z; }
    public double4(double2 p0, double p1, double p2) { x = p0.x; y = p0.y; z = p1; w = p2; }
    public double4(double2 p0, double2 p1) { x = p0.x; y = p0.y; z = p1.x; w = p1.y; }
    public double4(double3 p0, double p1) { x = p0.x; y = p0.y; z = p0.z; w = p1; }
    public static implicit operator double4(double v) => new double4(v);
    public static implicit operator double4(bool4 v) => new double4((v.x ? 1d : 0d), (v.y ? 1d : 0d), (v.z ? 1d : 0d), (v.w ? 1d : 0d));
    public static implicit operator double4(int4 v) => new double4((double)v.x, (double)v.y, (double)v.z, (double)v.w);
    public static implicit operator double4(uint4 v) => new double4((double)v.x, (double)v.y, (double)v.z, (double)v.w);
    public static implicit operator double4(half4 v) => new double4((double)(float)v.x, (double)(float)v.y, (double)(float)v.z, (double)(float)v.w);
    public static implicit operator double4(float4 v) => new double4((double)v.x, (double)v.y, (double)v.z, (double)v.w);
    public static explicit operator bool(double4 v) => (v.x != 0);
    public static explicit operator int(double4 v) => (int)v.x;
    public static explicit operator uint(double4 v) => (uint)v.x;
    public static explicit operator half(double4 v) => (half)(float)v.x;
    public static explicit operator float(double4 v) => (float)v.x;
    public static explicit operator double(double4 v) => v.x;
    public double this[int i]
    {
        get => i switch { 0 => x, 1 => y, 2 => z, 3 => w, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; case 3: w = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public double this[uint i] { get => this[(int)i]; set => this[(int)i] = value; }
    public static double4 operator +(double4 a, double4 b) => new double4((double)(a.x + b.x), (double)(a.y + b.y), (double)(a.z + b.z), (double)(a.w + b.w));
    public static double4 operator +(double4 a, double b) => new double4((double)(a.x + b), (double)(a.y + b), (double)(a.z + b), (double)(a.w + b));
    public static double4 operator +(double a, double4 b) => new double4((double)(a + b.x), (double)(a + b.y), (double)(a + b.z), (double)(a + b.w));
    public static double4 operator -(double4 a, double4 b) => new double4((double)(a.x - b.x), (double)(a.y - b.y), (double)(a.z - b.z), (double)(a.w - b.w));
    public static double4 operator -(double4 a, double b) => new double4((double)(a.x - b), (double)(a.y - b), (double)(a.z - b), (double)(a.w - b));
    public static double4 operator -(double a, double4 b) => new double4((double)(a - b.x), (double)(a - b.y), (double)(a - b.z), (double)(a - b.w));
    public static double4 operator *(double4 a, double4 b) => new double4((double)(a.x * b.x), (double)(a.y * b.y), (double)(a.z * b.z), (double)(a.w * b.w));
    public static double4 operator *(double4 a, double b) => new double4((double)(a.x * b), (double)(a.y * b), (double)(a.z * b), (double)(a.w * b));
    public static double4 operator *(double a, double4 b) => new double4((double)(a * b.x), (double)(a * b.y), (double)(a * b.z), (double)(a * b.w));
    public static double4 operator /(double4 a, double4 b) => new double4((double)(a.x / b.x), (double)(a.y / b.y), (double)(a.z / b.z), (double)(a.w / b.w));
    public static double4 operator /(double4 a, double b) => new double4((double)(a.x / b), (double)(a.y / b), (double)(a.z / b), (double)(a.w / b));
    public static double4 operator /(double a, double4 b) => new double4((double)(a / b.x), (double)(a / b.y), (double)(a / b.z), (double)(a / b.w));
    public static double4 operator %(double4 a, double4 b) => new double4((double)(a.x % b.x), (double)(a.y % b.y), (double)(a.z % b.z), (double)(a.w % b.w));
    public static double4 operator %(double4 a, double b) => new double4((double)(a.x % b), (double)(a.y % b), (double)(a.z % b), (double)(a.w % b));
    public static double4 operator %(double a, double4 b) => new double4((double)(a % b.x), (double)(a % b.y), (double)(a % b.z), (double)(a % b.w));
    public static double4 operator -(double4 a) => new double4((double)(-a.x), (double)(-a.y), (double)(-a.z), (double)(-a.w));
    public static double4 operator +(double4 a) => a;
    public static double4 operator ++(double4 a) => a + 1d;
    public static double4 operator --(double4 a) => a - 1d;
    public static bool4 operator <(double4 a, double4 b) => new bool4(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
    public static bool4 operator <(double4 a, double b) => new bool4(a.x < b, a.y < b, a.z < b, a.w < b);
    public static bool4 operator <(double a, double4 b) => new bool4(a < b.x, a < b.y, a < b.z, a < b.w);
    public static bool4 operator >(double4 a, double4 b) => new bool4(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
    public static bool4 operator >(double4 a, double b) => new bool4(a.x > b, a.y > b, a.z > b, a.w > b);
    public static bool4 operator >(double a, double4 b) => new bool4(a > b.x, a > b.y, a > b.z, a > b.w);
    public static bool4 operator <=(double4 a, double4 b) => new bool4(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
    public static bool4 operator <=(double4 a, double b) => new bool4(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
    public static bool4 operator <=(double a, double4 b) => new bool4(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
    public static bool4 operator >=(double4 a, double4 b) => new bool4(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
    public static bool4 operator >=(double4 a, double b) => new bool4(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
    public static bool4 operator >=(double a, double4 b) => new bool4(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
    public static bool4 operator ==(double4 a, double4 b) => new bool4(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
    public static bool4 operator !=(double4 a, double4 b) => new bool4(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
    public static bool4 operator ==(double4 a, double b) => new bool4(a.x == b, a.y == b, a.z == b, a.w == b);
    public static bool4 operator !=(double4 a, double b) => new bool4(a.x != b, a.y != b, a.z != b, a.w != b);
    public bool Equals(double4 other) => x.Equals(other.x) && y.Equals(other.y) && z.Equals(other.z) && w.Equals(other.w);
    public override bool Equals(object? obj) => obj is double4 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y, z, w);
    public override string ToString() => $"double4({x}, {y}, {z}, {w})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public readonly double2 xx => new double2(x, x);
    public double2 xy { readonly get => new double2(x, y); set { x = value.x; y = value.y; } }
    public double2 xz { readonly get => new double2(x, z); set { x = value.x; z = value.y; } }
    public double2 xw { readonly get => new double2(x, w); set { x = value.x; w = value.y; } }
    public double2 yx { readonly get => new double2(y, x); set { y = value.x; x = value.y; } }
    public readonly double2 yy => new double2(y, y);
    public double2 yz { readonly get => new double2(y, z); set { y = value.x; z = value.y; } }
    public double2 yw { readonly get => new double2(y, w); set { y = value.x; w = value.y; } }
    public double2 zx { readonly get => new double2(z, x); set { z = value.x; x = value.y; } }
    public double2 zy { readonly get => new double2(z, y); set { z = value.x; y = value.y; } }
    public readonly double2 zz => new double2(z, z);
    public double2 zw { readonly get => new double2(z, w); set { z = value.x; w = value.y; } }
    public double2 wx { readonly get => new double2(w, x); set { w = value.x; x = value.y; } }
    public double2 wy { readonly get => new double2(w, y); set { w = value.x; y = value.y; } }
    public double2 wz { readonly get => new double2(w, z); set { w = value.x; z = value.y; } }
    public readonly double2 ww => new double2(w, w);
    public readonly double3 xxx => new double3(x, x, x);
    public readonly double3 xxy => new double3(x, x, y);
    public readonly double3 xxz => new double3(x, x, z);
    public readonly double3 xxw => new double3(x, x, w);
    public readonly double3 xyx => new double3(x, y, x);
    public readonly double3 xyy => new double3(x, y, y);
    public double3 xyz { readonly get => new double3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public double3 xyw { readonly get => new double3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
    public readonly double3 xzx => new double3(x, z, x);
    public double3 xzy { readonly get => new double3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public readonly double3 xzz => new double3(x, z, z);
    public double3 xzw { readonly get => new double3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
    public readonly double3 xwx => new double3(x, w, x);
    public double3 xwy { readonly get => new double3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
    public double3 xwz { readonly get => new double3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
    public readonly double3 xww => new double3(x, w, w);
    public readonly double3 yxx => new double3(y, x, x);
    public readonly double3 yxy => new double3(y, x, y);
    public double3 yxz { readonly get => new double3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public double3 yxw { readonly get => new double3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
    public readonly double3 yyx => new double3(y, y, x);
    public readonly double3 yyy => new double3(y, y, y);
    public readonly double3 yyz => new double3(y, y, z);
    public readonly double3 yyw => new double3(y, y, w);
    public double3 yzx { readonly get => new double3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public readonly double3 yzy => new double3(y, z, y);
    public readonly double3 yzz => new double3(y, z, z);
    public double3 yzw { readonly get => new double3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
    public double3 ywx { readonly get => new double3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
    public readonly double3 ywy => new double3(y, w, y);
    public double3 ywz { readonly get => new double3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
    public readonly double3 yww => new double3(y, w, w);
    public readonly double3 zxx => new double3(z, x, x);
    public double3 zxy { readonly get => new double3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public readonly double3 zxz => new double3(z, x, z);
    public double3 zxw { readonly get => new double3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
    public double3 zyx { readonly get => new double3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public readonly double3 zyy => new double3(z, y, y);
    public readonly double3 zyz => new double3(z, y, z);
    public double3 zyw { readonly get => new double3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
    public readonly double3 zzx => new double3(z, z, x);
    public readonly double3 zzy => new double3(z, z, y);
    public readonly double3 zzz => new double3(z, z, z);
    public readonly double3 zzw => new double3(z, z, w);
    public double3 zwx { readonly get => new double3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
    public double3 zwy { readonly get => new double3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
    public readonly double3 zwz => new double3(z, w, z);
    public readonly double3 zww => new double3(z, w, w);
    public readonly double3 wxx => new double3(w, x, x);
    public double3 wxy { readonly get => new double3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
    public double3 wxz { readonly get => new double3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
    public readonly double3 wxw => new double3(w, x, w);
    public double3 wyx { readonly get => new double3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
    public readonly double3 wyy => new double3(w, y, y);
    public double3 wyz { readonly get => new double3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
    public readonly double3 wyw => new double3(w, y, w);
    public double3 wzx { readonly get => new double3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
    public double3 wzy { readonly get => new double3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
    public readonly double3 wzz => new double3(w, z, z);
    public readonly double3 wzw => new double3(w, z, w);
    public readonly double3 wwx => new double3(w, w, x);
    public readonly double3 wwy => new double3(w, w, y);
    public readonly double3 wwz => new double3(w, w, z);
    public readonly double3 www => new double3(w, w, w);
    public readonly double4 xxxx => new double4(x, x, x, x);
    public readonly double4 xxxy => new double4(x, x, x, y);
    public readonly double4 xxxz => new double4(x, x, x, z);
    public readonly double4 xxxw => new double4(x, x, x, w);
    public readonly double4 xxyx => new double4(x, x, y, x);
    public readonly double4 xxyy => new double4(x, x, y, y);
    public readonly double4 xxyz => new double4(x, x, y, z);
    public readonly double4 xxyw => new double4(x, x, y, w);
    public readonly double4 xxzx => new double4(x, x, z, x);
    public readonly double4 xxzy => new double4(x, x, z, y);
    public readonly double4 xxzz => new double4(x, x, z, z);
    public readonly double4 xxzw => new double4(x, x, z, w);
    public readonly double4 xxwx => new double4(x, x, w, x);
    public readonly double4 xxwy => new double4(x, x, w, y);
    public readonly double4 xxwz => new double4(x, x, w, z);
    public readonly double4 xxww => new double4(x, x, w, w);
    public readonly double4 xyxx => new double4(x, y, x, x);
    public readonly double4 xyxy => new double4(x, y, x, y);
    public readonly double4 xyxz => new double4(x, y, x, z);
    public readonly double4 xyxw => new double4(x, y, x, w);
    public readonly double4 xyyx => new double4(x, y, y, x);
    public readonly double4 xyyy => new double4(x, y, y, y);
    public readonly double4 xyyz => new double4(x, y, y, z);
    public readonly double4 xyyw => new double4(x, y, y, w);
    public readonly double4 xyzx => new double4(x, y, z, x);
    public readonly double4 xyzy => new double4(x, y, z, y);
    public readonly double4 xyzz => new double4(x, y, z, z);
    public double4 xyzw { readonly get => new double4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
    public readonly double4 xywx => new double4(x, y, w, x);
    public readonly double4 xywy => new double4(x, y, w, y);
    public double4 xywz { readonly get => new double4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
    public readonly double4 xyww => new double4(x, y, w, w);
    public readonly double4 xzxx => new double4(x, z, x, x);
    public readonly double4 xzxy => new double4(x, z, x, y);
    public readonly double4 xzxz => new double4(x, z, x, z);
    public readonly double4 xzxw => new double4(x, z, x, w);
    public readonly double4 xzyx => new double4(x, z, y, x);
    public readonly double4 xzyy => new double4(x, z, y, y);
    public readonly double4 xzyz => new double4(x, z, y, z);
    public double4 xzyw { readonly get => new double4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
    public readonly double4 xzzx => new double4(x, z, z, x);
    public readonly double4 xzzy => new double4(x, z, z, y);
    public readonly double4 xzzz => new double4(x, z, z, z);
    public readonly double4 xzzw => new double4(x, z, z, w);
    public readonly double4 xzwx => new double4(x, z, w, x);
    public double4 xzwy { readonly get => new double4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
    public readonly double4 xzwz => new double4(x, z, w, z);
    public readonly double4 xzww => new double4(x, z, w, w);
    public readonly double4 xwxx => new double4(x, w, x, x);
    public readonly double4 xwxy => new double4(x, w, x, y);
    public readonly double4 xwxz => new double4(x, w, x, z);
    public readonly double4 xwxw => new double4(x, w, x, w);
    public readonly double4 xwyx => new double4(x, w, y, x);
    public readonly double4 xwyy => new double4(x, w, y, y);
    public double4 xwyz { readonly get => new double4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
    public readonly double4 xwyw => new double4(x, w, y, w);
    public readonly double4 xwzx => new double4(x, w, z, x);
    public double4 xwzy { readonly get => new double4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
    public readonly double4 xwzz => new double4(x, w, z, z);
    public readonly double4 xwzw => new double4(x, w, z, w);
    public readonly double4 xwwx => new double4(x, w, w, x);
    public readonly double4 xwwy => new double4(x, w, w, y);
    public readonly double4 xwwz => new double4(x, w, w, z);
    public readonly double4 xwww => new double4(x, w, w, w);
    public readonly double4 yxxx => new double4(y, x, x, x);
    public readonly double4 yxxy => new double4(y, x, x, y);
    public readonly double4 yxxz => new double4(y, x, x, z);
    public readonly double4 yxxw => new double4(y, x, x, w);
    public readonly double4 yxyx => new double4(y, x, y, x);
    public readonly double4 yxyy => new double4(y, x, y, y);
    public readonly double4 yxyz => new double4(y, x, y, z);
    public readonly double4 yxyw => new double4(y, x, y, w);
    public readonly double4 yxzx => new double4(y, x, z, x);
    public readonly double4 yxzy => new double4(y, x, z, y);
    public readonly double4 yxzz => new double4(y, x, z, z);
    public double4 yxzw { readonly get => new double4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
    public readonly double4 yxwx => new double4(y, x, w, x);
    public readonly double4 yxwy => new double4(y, x, w, y);
    public double4 yxwz { readonly get => new double4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
    public readonly double4 yxww => new double4(y, x, w, w);
    public readonly double4 yyxx => new double4(y, y, x, x);
    public readonly double4 yyxy => new double4(y, y, x, y);
    public readonly double4 yyxz => new double4(y, y, x, z);
    public readonly double4 yyxw => new double4(y, y, x, w);
    public readonly double4 yyyx => new double4(y, y, y, x);
    public readonly double4 yyyy => new double4(y, y, y, y);
    public readonly double4 yyyz => new double4(y, y, y, z);
    public readonly double4 yyyw => new double4(y, y, y, w);
    public readonly double4 yyzx => new double4(y, y, z, x);
    public readonly double4 yyzy => new double4(y, y, z, y);
    public readonly double4 yyzz => new double4(y, y, z, z);
    public readonly double4 yyzw => new double4(y, y, z, w);
    public readonly double4 yywx => new double4(y, y, w, x);
    public readonly double4 yywy => new double4(y, y, w, y);
    public readonly double4 yywz => new double4(y, y, w, z);
    public readonly double4 yyww => new double4(y, y, w, w);
    public readonly double4 yzxx => new double4(y, z, x, x);
    public readonly double4 yzxy => new double4(y, z, x, y);
    public readonly double4 yzxz => new double4(y, z, x, z);
    public double4 yzxw { readonly get => new double4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
    public readonly double4 yzyx => new double4(y, z, y, x);
    public readonly double4 yzyy => new double4(y, z, y, y);
    public readonly double4 yzyz => new double4(y, z, y, z);
    public readonly double4 yzyw => new double4(y, z, y, w);
    public readonly double4 yzzx => new double4(y, z, z, x);
    public readonly double4 yzzy => new double4(y, z, z, y);
    public readonly double4 yzzz => new double4(y, z, z, z);
    public readonly double4 yzzw => new double4(y, z, z, w);
    public double4 yzwx { readonly get => new double4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
    public readonly double4 yzwy => new double4(y, z, w, y);
    public readonly double4 yzwz => new double4(y, z, w, z);
    public readonly double4 yzww => new double4(y, z, w, w);
    public readonly double4 ywxx => new double4(y, w, x, x);
    public readonly double4 ywxy => new double4(y, w, x, y);
    public double4 ywxz { readonly get => new double4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
    public readonly double4 ywxw => new double4(y, w, x, w);
    public readonly double4 ywyx => new double4(y, w, y, x);
    public readonly double4 ywyy => new double4(y, w, y, y);
    public readonly double4 ywyz => new double4(y, w, y, z);
    public readonly double4 ywyw => new double4(y, w, y, w);
    public double4 ywzx { readonly get => new double4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
    public readonly double4 ywzy => new double4(y, w, z, y);
    public readonly double4 ywzz => new double4(y, w, z, z);
    public readonly double4 ywzw => new double4(y, w, z, w);
    public readonly double4 ywwx => new double4(y, w, w, x);
    public readonly double4 ywwy => new double4(y, w, w, y);
    public readonly double4 ywwz => new double4(y, w, w, z);
    public readonly double4 ywww => new double4(y, w, w, w);
    public readonly double4 zxxx => new double4(z, x, x, x);
    public readonly double4 zxxy => new double4(z, x, x, y);
    public readonly double4 zxxz => new double4(z, x, x, z);
    public readonly double4 zxxw => new double4(z, x, x, w);
    public readonly double4 zxyx => new double4(z, x, y, x);
    public readonly double4 zxyy => new double4(z, x, y, y);
    public readonly double4 zxyz => new double4(z, x, y, z);
    public double4 zxyw { readonly get => new double4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
    public readonly double4 zxzx => new double4(z, x, z, x);
    public readonly double4 zxzy => new double4(z, x, z, y);
    public readonly double4 zxzz => new double4(z, x, z, z);
    public readonly double4 zxzw => new double4(z, x, z, w);
    public readonly double4 zxwx => new double4(z, x, w, x);
    public double4 zxwy { readonly get => new double4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
    public readonly double4 zxwz => new double4(z, x, w, z);
    public readonly double4 zxww => new double4(z, x, w, w);
    public readonly double4 zyxx => new double4(z, y, x, x);
    public readonly double4 zyxy => new double4(z, y, x, y);
    public readonly double4 zyxz => new double4(z, y, x, z);
    public double4 zyxw { readonly get => new double4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
    public readonly double4 zyyx => new double4(z, y, y, x);
    public readonly double4 zyyy => new double4(z, y, y, y);
    public readonly double4 zyyz => new double4(z, y, y, z);
    public readonly double4 zyyw => new double4(z, y, y, w);
    public readonly double4 zyzx => new double4(z, y, z, x);
    public readonly double4 zyzy => new double4(z, y, z, y);
    public readonly double4 zyzz => new double4(z, y, z, z);
    public readonly double4 zyzw => new double4(z, y, z, w);
    public double4 zywx { readonly get => new double4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
    public readonly double4 zywy => new double4(z, y, w, y);
    public readonly double4 zywz => new double4(z, y, w, z);
    public readonly double4 zyww => new double4(z, y, w, w);
    public readonly double4 zzxx => new double4(z, z, x, x);
    public readonly double4 zzxy => new double4(z, z, x, y);
    public readonly double4 zzxz => new double4(z, z, x, z);
    public readonly double4 zzxw => new double4(z, z, x, w);
    public readonly double4 zzyx => new double4(z, z, y, x);
    public readonly double4 zzyy => new double4(z, z, y, y);
    public readonly double4 zzyz => new double4(z, z, y, z);
    public readonly double4 zzyw => new double4(z, z, y, w);
    public readonly double4 zzzx => new double4(z, z, z, x);
    public readonly double4 zzzy => new double4(z, z, z, y);
    public readonly double4 zzzz => new double4(z, z, z, z);
    public readonly double4 zzzw => new double4(z, z, z, w);
    public readonly double4 zzwx => new double4(z, z, w, x);
    public readonly double4 zzwy => new double4(z, z, w, y);
    public readonly double4 zzwz => new double4(z, z, w, z);
    public readonly double4 zzww => new double4(z, z, w, w);
    public readonly double4 zwxx => new double4(z, w, x, x);
    public double4 zwxy { readonly get => new double4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
    public readonly double4 zwxz => new double4(z, w, x, z);
    public readonly double4 zwxw => new double4(z, w, x, w);
    public double4 zwyx { readonly get => new double4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
    public readonly double4 zwyy => new double4(z, w, y, y);
    public readonly double4 zwyz => new double4(z, w, y, z);
    public readonly double4 zwyw => new double4(z, w, y, w);
    public readonly double4 zwzx => new double4(z, w, z, x);
    public readonly double4 zwzy => new double4(z, w, z, y);
    public readonly double4 zwzz => new double4(z, w, z, z);
    public readonly double4 zwzw => new double4(z, w, z, w);
    public readonly double4 zwwx => new double4(z, w, w, x);
    public readonly double4 zwwy => new double4(z, w, w, y);
    public readonly double4 zwwz => new double4(z, w, w, z);
    public readonly double4 zwww => new double4(z, w, w, w);
    public readonly double4 wxxx => new double4(w, x, x, x);
    public readonly double4 wxxy => new double4(w, x, x, y);
    public readonly double4 wxxz => new double4(w, x, x, z);
    public readonly double4 wxxw => new double4(w, x, x, w);
    public readonly double4 wxyx => new double4(w, x, y, x);
    public readonly double4 wxyy => new double4(w, x, y, y);
    public double4 wxyz { readonly get => new double4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
    public readonly double4 wxyw => new double4(w, x, y, w);
    public readonly double4 wxzx => new double4(w, x, z, x);
    public double4 wxzy { readonly get => new double4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
    public readonly double4 wxzz => new double4(w, x, z, z);
    public readonly double4 wxzw => new double4(w, x, z, w);
    public readonly double4 wxwx => new double4(w, x, w, x);
    public readonly double4 wxwy => new double4(w, x, w, y);
    public readonly double4 wxwz => new double4(w, x, w, z);
    public readonly double4 wxww => new double4(w, x, w, w);
    public readonly double4 wyxx => new double4(w, y, x, x);
    public readonly double4 wyxy => new double4(w, y, x, y);
    public double4 wyxz { readonly get => new double4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
    public readonly double4 wyxw => new double4(w, y, x, w);
    public readonly double4 wyyx => new double4(w, y, y, x);
    public readonly double4 wyyy => new double4(w, y, y, y);
    public readonly double4 wyyz => new double4(w, y, y, z);
    public readonly double4 wyyw => new double4(w, y, y, w);
    public double4 wyzx { readonly get => new double4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
    public readonly double4 wyzy => new double4(w, y, z, y);
    public readonly double4 wyzz => new double4(w, y, z, z);
    public readonly double4 wyzw => new double4(w, y, z, w);
    public readonly double4 wywx => new double4(w, y, w, x);
    public readonly double4 wywy => new double4(w, y, w, y);
    public readonly double4 wywz => new double4(w, y, w, z);
    public readonly double4 wyww => new double4(w, y, w, w);
    public readonly double4 wzxx => new double4(w, z, x, x);
    public double4 wzxy { readonly get => new double4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
    public readonly double4 wzxz => new double4(w, z, x, z);
    public readonly double4 wzxw => new double4(w, z, x, w);
    public double4 wzyx { readonly get => new double4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
    public readonly double4 wzyy => new double4(w, z, y, y);
    public readonly double4 wzyz => new double4(w, z, y, z);
    public readonly double4 wzyw => new double4(w, z, y, w);
    public readonly double4 wzzx => new double4(w, z, z, x);
    public readonly double4 wzzy => new double4(w, z, z, y);
    public readonly double4 wzzz => new double4(w, z, z, z);
    public readonly double4 wzzw => new double4(w, z, z, w);
    public readonly double4 wzwx => new double4(w, z, w, x);
    public readonly double4 wzwy => new double4(w, z, w, y);
    public readonly double4 wzwz => new double4(w, z, w, z);
    public readonly double4 wzww => new double4(w, z, w, w);
    public readonly double4 wwxx => new double4(w, w, x, x);
    public readonly double4 wwxy => new double4(w, w, x, y);
    public readonly double4 wwxz => new double4(w, w, x, z);
    public readonly double4 wwxw => new double4(w, w, x, w);
    public readonly double4 wwyx => new double4(w, w, y, x);
    public readonly double4 wwyy => new double4(w, w, y, y);
    public readonly double4 wwyz => new double4(w, w, y, z);
    public readonly double4 wwyw => new double4(w, w, y, w);
    public readonly double4 wwzx => new double4(w, w, z, x);
    public readonly double4 wwzy => new double4(w, w, z, y);
    public readonly double4 wwzz => new double4(w, w, z, z);
    public readonly double4 wwzw => new double4(w, w, z, w);
    public readonly double4 wwwx => new double4(w, w, w, x);
    public readonly double4 wwwy => new double4(w, w, w, y);
    public readonly double4 wwwz => new double4(w, w, w, z);
    public readonly double4 wwww => new double4(w, w, w, w);
    public double r { readonly get => x; set => x = value; }
    public double g { readonly get => y; set => y = value; }
    public double b { readonly get => z; set => z = value; }
    public double a { readonly get => w; set => w = value; }
    public readonly double2 rr => new double2(x, x);
    public double2 rg { readonly get => new double2(x, y); set { x = value.x; y = value.y; } }
    public double2 rb { readonly get => new double2(x, z); set { x = value.x; z = value.y; } }
    public double2 ra { readonly get => new double2(x, w); set { x = value.x; w = value.y; } }
    public double2 gr { readonly get => new double2(y, x); set { y = value.x; x = value.y; } }
    public readonly double2 gg => new double2(y, y);
    public double2 gb { readonly get => new double2(y, z); set { y = value.x; z = value.y; } }
    public double2 ga { readonly get => new double2(y, w); set { y = value.x; w = value.y; } }
    public double2 br { readonly get => new double2(z, x); set { z = value.x; x = value.y; } }
    public double2 bg { readonly get => new double2(z, y); set { z = value.x; y = value.y; } }
    public readonly double2 bb => new double2(z, z);
    public double2 ba { readonly get => new double2(z, w); set { z = value.x; w = value.y; } }
    public double2 ar { readonly get => new double2(w, x); set { w = value.x; x = value.y; } }
    public double2 ag { readonly get => new double2(w, y); set { w = value.x; y = value.y; } }
    public double2 ab { readonly get => new double2(w, z); set { w = value.x; z = value.y; } }
    public readonly double2 aa => new double2(w, w);
    public readonly double3 rrr => new double3(x, x, x);
    public readonly double3 rrg => new double3(x, x, y);
    public readonly double3 rrb => new double3(x, x, z);
    public readonly double3 rra => new double3(x, x, w);
    public readonly double3 rgr => new double3(x, y, x);
    public readonly double3 rgg => new double3(x, y, y);
    public double3 rgb { readonly get => new double3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public double3 rga { readonly get => new double3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
    public readonly double3 rbr => new double3(x, z, x);
    public double3 rbg { readonly get => new double3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public readonly double3 rbb => new double3(x, z, z);
    public double3 rba { readonly get => new double3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
    public readonly double3 rar => new double3(x, w, x);
    public double3 rag { readonly get => new double3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
    public double3 rab { readonly get => new double3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
    public readonly double3 raa => new double3(x, w, w);
    public readonly double3 grr => new double3(y, x, x);
    public readonly double3 grg => new double3(y, x, y);
    public double3 grb { readonly get => new double3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public double3 gra { readonly get => new double3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
    public readonly double3 ggr => new double3(y, y, x);
    public readonly double3 ggg => new double3(y, y, y);
    public readonly double3 ggb => new double3(y, y, z);
    public readonly double3 gga => new double3(y, y, w);
    public double3 gbr { readonly get => new double3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public readonly double3 gbg => new double3(y, z, y);
    public readonly double3 gbb => new double3(y, z, z);
    public double3 gba { readonly get => new double3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
    public double3 gar { readonly get => new double3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
    public readonly double3 gag => new double3(y, w, y);
    public double3 gab { readonly get => new double3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
    public readonly double3 gaa => new double3(y, w, w);
    public readonly double3 brr => new double3(z, x, x);
    public double3 brg { readonly get => new double3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public readonly double3 brb => new double3(z, x, z);
    public double3 bra { readonly get => new double3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
    public double3 bgr { readonly get => new double3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public readonly double3 bgg => new double3(z, y, y);
    public readonly double3 bgb => new double3(z, y, z);
    public double3 bga { readonly get => new double3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
    public readonly double3 bbr => new double3(z, z, x);
    public readonly double3 bbg => new double3(z, z, y);
    public readonly double3 bbb => new double3(z, z, z);
    public readonly double3 bba => new double3(z, z, w);
    public double3 bar { readonly get => new double3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
    public double3 bag { readonly get => new double3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
    public readonly double3 bab => new double3(z, w, z);
    public readonly double3 baa => new double3(z, w, w);
    public readonly double3 arr => new double3(w, x, x);
    public double3 arg { readonly get => new double3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
    public double3 arb { readonly get => new double3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
    public readonly double3 ara => new double3(w, x, w);
    public double3 agr { readonly get => new double3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
    public readonly double3 agg => new double3(w, y, y);
    public double3 agb { readonly get => new double3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
    public readonly double3 aga => new double3(w, y, w);
    public double3 abr { readonly get => new double3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
    public double3 abg { readonly get => new double3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
    public readonly double3 abb => new double3(w, z, z);
    public readonly double3 aba => new double3(w, z, w);
    public readonly double3 aar => new double3(w, w, x);
    public readonly double3 aag => new double3(w, w, y);
    public readonly double3 aab => new double3(w, w, z);
    public readonly double3 aaa => new double3(w, w, w);
    public readonly double4 rrrr => new double4(x, x, x, x);
    public readonly double4 rrrg => new double4(x, x, x, y);
    public readonly double4 rrrb => new double4(x, x, x, z);
    public readonly double4 rrra => new double4(x, x, x, w);
    public readonly double4 rrgr => new double4(x, x, y, x);
    public readonly double4 rrgg => new double4(x, x, y, y);
    public readonly double4 rrgb => new double4(x, x, y, z);
    public readonly double4 rrga => new double4(x, x, y, w);
    public readonly double4 rrbr => new double4(x, x, z, x);
    public readonly double4 rrbg => new double4(x, x, z, y);
    public readonly double4 rrbb => new double4(x, x, z, z);
    public readonly double4 rrba => new double4(x, x, z, w);
    public readonly double4 rrar => new double4(x, x, w, x);
    public readonly double4 rrag => new double4(x, x, w, y);
    public readonly double4 rrab => new double4(x, x, w, z);
    public readonly double4 rraa => new double4(x, x, w, w);
    public readonly double4 rgrr => new double4(x, y, x, x);
    public readonly double4 rgrg => new double4(x, y, x, y);
    public readonly double4 rgrb => new double4(x, y, x, z);
    public readonly double4 rgra => new double4(x, y, x, w);
    public readonly double4 rggr => new double4(x, y, y, x);
    public readonly double4 rggg => new double4(x, y, y, y);
    public readonly double4 rggb => new double4(x, y, y, z);
    public readonly double4 rgga => new double4(x, y, y, w);
    public readonly double4 rgbr => new double4(x, y, z, x);
    public readonly double4 rgbg => new double4(x, y, z, y);
    public readonly double4 rgbb => new double4(x, y, z, z);
    public double4 rgba { readonly get => new double4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
    public readonly double4 rgar => new double4(x, y, w, x);
    public readonly double4 rgag => new double4(x, y, w, y);
    public double4 rgab { readonly get => new double4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
    public readonly double4 rgaa => new double4(x, y, w, w);
    public readonly double4 rbrr => new double4(x, z, x, x);
    public readonly double4 rbrg => new double4(x, z, x, y);
    public readonly double4 rbrb => new double4(x, z, x, z);
    public readonly double4 rbra => new double4(x, z, x, w);
    public readonly double4 rbgr => new double4(x, z, y, x);
    public readonly double4 rbgg => new double4(x, z, y, y);
    public readonly double4 rbgb => new double4(x, z, y, z);
    public double4 rbga { readonly get => new double4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
    public readonly double4 rbbr => new double4(x, z, z, x);
    public readonly double4 rbbg => new double4(x, z, z, y);
    public readonly double4 rbbb => new double4(x, z, z, z);
    public readonly double4 rbba => new double4(x, z, z, w);
    public readonly double4 rbar => new double4(x, z, w, x);
    public double4 rbag { readonly get => new double4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
    public readonly double4 rbab => new double4(x, z, w, z);
    public readonly double4 rbaa => new double4(x, z, w, w);
    public readonly double4 rarr => new double4(x, w, x, x);
    public readonly double4 rarg => new double4(x, w, x, y);
    public readonly double4 rarb => new double4(x, w, x, z);
    public readonly double4 rara => new double4(x, w, x, w);
    public readonly double4 ragr => new double4(x, w, y, x);
    public readonly double4 ragg => new double4(x, w, y, y);
    public double4 ragb { readonly get => new double4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
    public readonly double4 raga => new double4(x, w, y, w);
    public readonly double4 rabr => new double4(x, w, z, x);
    public double4 rabg { readonly get => new double4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
    public readonly double4 rabb => new double4(x, w, z, z);
    public readonly double4 raba => new double4(x, w, z, w);
    public readonly double4 raar => new double4(x, w, w, x);
    public readonly double4 raag => new double4(x, w, w, y);
    public readonly double4 raab => new double4(x, w, w, z);
    public readonly double4 raaa => new double4(x, w, w, w);
    public readonly double4 grrr => new double4(y, x, x, x);
    public readonly double4 grrg => new double4(y, x, x, y);
    public readonly double4 grrb => new double4(y, x, x, z);
    public readonly double4 grra => new double4(y, x, x, w);
    public readonly double4 grgr => new double4(y, x, y, x);
    public readonly double4 grgg => new double4(y, x, y, y);
    public readonly double4 grgb => new double4(y, x, y, z);
    public readonly double4 grga => new double4(y, x, y, w);
    public readonly double4 grbr => new double4(y, x, z, x);
    public readonly double4 grbg => new double4(y, x, z, y);
    public readonly double4 grbb => new double4(y, x, z, z);
    public double4 grba { readonly get => new double4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
    public readonly double4 grar => new double4(y, x, w, x);
    public readonly double4 grag => new double4(y, x, w, y);
    public double4 grab { readonly get => new double4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
    public readonly double4 graa => new double4(y, x, w, w);
    public readonly double4 ggrr => new double4(y, y, x, x);
    public readonly double4 ggrg => new double4(y, y, x, y);
    public readonly double4 ggrb => new double4(y, y, x, z);
    public readonly double4 ggra => new double4(y, y, x, w);
    public readonly double4 gggr => new double4(y, y, y, x);
    public readonly double4 gggg => new double4(y, y, y, y);
    public readonly double4 gggb => new double4(y, y, y, z);
    public readonly double4 ggga => new double4(y, y, y, w);
    public readonly double4 ggbr => new double4(y, y, z, x);
    public readonly double4 ggbg => new double4(y, y, z, y);
    public readonly double4 ggbb => new double4(y, y, z, z);
    public readonly double4 ggba => new double4(y, y, z, w);
    public readonly double4 ggar => new double4(y, y, w, x);
    public readonly double4 ggag => new double4(y, y, w, y);
    public readonly double4 ggab => new double4(y, y, w, z);
    public readonly double4 ggaa => new double4(y, y, w, w);
    public readonly double4 gbrr => new double4(y, z, x, x);
    public readonly double4 gbrg => new double4(y, z, x, y);
    public readonly double4 gbrb => new double4(y, z, x, z);
    public double4 gbra { readonly get => new double4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
    public readonly double4 gbgr => new double4(y, z, y, x);
    public readonly double4 gbgg => new double4(y, z, y, y);
    public readonly double4 gbgb => new double4(y, z, y, z);
    public readonly double4 gbga => new double4(y, z, y, w);
    public readonly double4 gbbr => new double4(y, z, z, x);
    public readonly double4 gbbg => new double4(y, z, z, y);
    public readonly double4 gbbb => new double4(y, z, z, z);
    public readonly double4 gbba => new double4(y, z, z, w);
    public double4 gbar { readonly get => new double4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
    public readonly double4 gbag => new double4(y, z, w, y);
    public readonly double4 gbab => new double4(y, z, w, z);
    public readonly double4 gbaa => new double4(y, z, w, w);
    public readonly double4 garr => new double4(y, w, x, x);
    public readonly double4 garg => new double4(y, w, x, y);
    public double4 garb { readonly get => new double4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
    public readonly double4 gara => new double4(y, w, x, w);
    public readonly double4 gagr => new double4(y, w, y, x);
    public readonly double4 gagg => new double4(y, w, y, y);
    public readonly double4 gagb => new double4(y, w, y, z);
    public readonly double4 gaga => new double4(y, w, y, w);
    public double4 gabr { readonly get => new double4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
    public readonly double4 gabg => new double4(y, w, z, y);
    public readonly double4 gabb => new double4(y, w, z, z);
    public readonly double4 gaba => new double4(y, w, z, w);
    public readonly double4 gaar => new double4(y, w, w, x);
    public readonly double4 gaag => new double4(y, w, w, y);
    public readonly double4 gaab => new double4(y, w, w, z);
    public readonly double4 gaaa => new double4(y, w, w, w);
    public readonly double4 brrr => new double4(z, x, x, x);
    public readonly double4 brrg => new double4(z, x, x, y);
    public readonly double4 brrb => new double4(z, x, x, z);
    public readonly double4 brra => new double4(z, x, x, w);
    public readonly double4 brgr => new double4(z, x, y, x);
    public readonly double4 brgg => new double4(z, x, y, y);
    public readonly double4 brgb => new double4(z, x, y, z);
    public double4 brga { readonly get => new double4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
    public readonly double4 brbr => new double4(z, x, z, x);
    public readonly double4 brbg => new double4(z, x, z, y);
    public readonly double4 brbb => new double4(z, x, z, z);
    public readonly double4 brba => new double4(z, x, z, w);
    public readonly double4 brar => new double4(z, x, w, x);
    public double4 brag { readonly get => new double4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
    public readonly double4 brab => new double4(z, x, w, z);
    public readonly double4 braa => new double4(z, x, w, w);
    public readonly double4 bgrr => new double4(z, y, x, x);
    public readonly double4 bgrg => new double4(z, y, x, y);
    public readonly double4 bgrb => new double4(z, y, x, z);
    public double4 bgra { readonly get => new double4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
    public readonly double4 bggr => new double4(z, y, y, x);
    public readonly double4 bggg => new double4(z, y, y, y);
    public readonly double4 bggb => new double4(z, y, y, z);
    public readonly double4 bgga => new double4(z, y, y, w);
    public readonly double4 bgbr => new double4(z, y, z, x);
    public readonly double4 bgbg => new double4(z, y, z, y);
    public readonly double4 bgbb => new double4(z, y, z, z);
    public readonly double4 bgba => new double4(z, y, z, w);
    public double4 bgar { readonly get => new double4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
    public readonly double4 bgag => new double4(z, y, w, y);
    public readonly double4 bgab => new double4(z, y, w, z);
    public readonly double4 bgaa => new double4(z, y, w, w);
    public readonly double4 bbrr => new double4(z, z, x, x);
    public readonly double4 bbrg => new double4(z, z, x, y);
    public readonly double4 bbrb => new double4(z, z, x, z);
    public readonly double4 bbra => new double4(z, z, x, w);
    public readonly double4 bbgr => new double4(z, z, y, x);
    public readonly double4 bbgg => new double4(z, z, y, y);
    public readonly double4 bbgb => new double4(z, z, y, z);
    public readonly double4 bbga => new double4(z, z, y, w);
    public readonly double4 bbbr => new double4(z, z, z, x);
    public readonly double4 bbbg => new double4(z, z, z, y);
    public readonly double4 bbbb => new double4(z, z, z, z);
    public readonly double4 bbba => new double4(z, z, z, w);
    public readonly double4 bbar => new double4(z, z, w, x);
    public readonly double4 bbag => new double4(z, z, w, y);
    public readonly double4 bbab => new double4(z, z, w, z);
    public readonly double4 bbaa => new double4(z, z, w, w);
    public readonly double4 barr => new double4(z, w, x, x);
    public double4 barg { readonly get => new double4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
    public readonly double4 barb => new double4(z, w, x, z);
    public readonly double4 bara => new double4(z, w, x, w);
    public double4 bagr { readonly get => new double4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
    public readonly double4 bagg => new double4(z, w, y, y);
    public readonly double4 bagb => new double4(z, w, y, z);
    public readonly double4 baga => new double4(z, w, y, w);
    public readonly double4 babr => new double4(z, w, z, x);
    public readonly double4 babg => new double4(z, w, z, y);
    public readonly double4 babb => new double4(z, w, z, z);
    public readonly double4 baba => new double4(z, w, z, w);
    public readonly double4 baar => new double4(z, w, w, x);
    public readonly double4 baag => new double4(z, w, w, y);
    public readonly double4 baab => new double4(z, w, w, z);
    public readonly double4 baaa => new double4(z, w, w, w);
    public readonly double4 arrr => new double4(w, x, x, x);
    public readonly double4 arrg => new double4(w, x, x, y);
    public readonly double4 arrb => new double4(w, x, x, z);
    public readonly double4 arra => new double4(w, x, x, w);
    public readonly double4 argr => new double4(w, x, y, x);
    public readonly double4 argg => new double4(w, x, y, y);
    public double4 argb { readonly get => new double4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
    public readonly double4 arga => new double4(w, x, y, w);
    public readonly double4 arbr => new double4(w, x, z, x);
    public double4 arbg { readonly get => new double4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
    public readonly double4 arbb => new double4(w, x, z, z);
    public readonly double4 arba => new double4(w, x, z, w);
    public readonly double4 arar => new double4(w, x, w, x);
    public readonly double4 arag => new double4(w, x, w, y);
    public readonly double4 arab => new double4(w, x, w, z);
    public readonly double4 araa => new double4(w, x, w, w);
    public readonly double4 agrr => new double4(w, y, x, x);
    public readonly double4 agrg => new double4(w, y, x, y);
    public double4 agrb { readonly get => new double4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
    public readonly double4 agra => new double4(w, y, x, w);
    public readonly double4 aggr => new double4(w, y, y, x);
    public readonly double4 aggg => new double4(w, y, y, y);
    public readonly double4 aggb => new double4(w, y, y, z);
    public readonly double4 agga => new double4(w, y, y, w);
    public double4 agbr { readonly get => new double4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
    public readonly double4 agbg => new double4(w, y, z, y);
    public readonly double4 agbb => new double4(w, y, z, z);
    public readonly double4 agba => new double4(w, y, z, w);
    public readonly double4 agar => new double4(w, y, w, x);
    public readonly double4 agag => new double4(w, y, w, y);
    public readonly double4 agab => new double4(w, y, w, z);
    public readonly double4 agaa => new double4(w, y, w, w);
    public readonly double4 abrr => new double4(w, z, x, x);
    public double4 abrg { readonly get => new double4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
    public readonly double4 abrb => new double4(w, z, x, z);
    public readonly double4 abra => new double4(w, z, x, w);
    public double4 abgr { readonly get => new double4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
    public readonly double4 abgg => new double4(w, z, y, y);
    public readonly double4 abgb => new double4(w, z, y, z);
    public readonly double4 abga => new double4(w, z, y, w);
    public readonly double4 abbr => new double4(w, z, z, x);
    public readonly double4 abbg => new double4(w, z, z, y);
    public readonly double4 abbb => new double4(w, z, z, z);
    public readonly double4 abba => new double4(w, z, z, w);
    public readonly double4 abar => new double4(w, z, w, x);
    public readonly double4 abag => new double4(w, z, w, y);
    public readonly double4 abab => new double4(w, z, w, z);
    public readonly double4 abaa => new double4(w, z, w, w);
    public readonly double4 aarr => new double4(w, w, x, x);
    public readonly double4 aarg => new double4(w, w, x, y);
    public readonly double4 aarb => new double4(w, w, x, z);
    public readonly double4 aara => new double4(w, w, x, w);
    public readonly double4 aagr => new double4(w, w, y, x);
    public readonly double4 aagg => new double4(w, w, y, y);
    public readonly double4 aagb => new double4(w, w, y, z);
    public readonly double4 aaga => new double4(w, w, y, w);
    public readonly double4 aabr => new double4(w, w, z, x);
    public readonly double4 aabg => new double4(w, w, z, y);
    public readonly double4 aabb => new double4(w, w, z, z);
    public readonly double4 aaba => new double4(w, w, z, w);
    public readonly double4 aaar => new double4(w, w, w, x);
    public readonly double4 aaag => new double4(w, w, w, y);
    public readonly double4 aaab => new double4(w, w, w, z);
    public readonly double4 aaaa => new double4(w, w, w, w);
}
