// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591, CS0660, CS0661
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL int4x2: 4 rows of int2, indexed m[row][column].</summary>
[StructLayout(LayoutKind.Sequential)]
public struct int4x2
{
    public int2 r0, r1, r2, r3;
    public int4x2(int2 r0, int2 r1, int2 r2, int2 r3) { this.r0 = r0; this.r1 = r1; this.r2 = r2; this.r3 = r3; }
    public int4x2(int m00, int m01, int m10, int m11, int m20, int m21, int m30, int m31) { r0 = new int2(m00, m01); r1 = new int2(m10, m11); r2 = new int2(m20, m21); r3 = new int2(m30, m31); }
    public int4x2(int v) { r0 = v; r1 = v; r2 = v; r3 = v; }
    public static implicit operator int4x2(int v) => new int4x2(v);
    public int2 this[int i]
    {
        readonly get => i switch { 0 => r0, 1 => r1, 2 => r2, 3 => r3, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: r0 = value; break; case 1: r1 = value; break; case 2: r2 = value; break; case 3: r3 = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public int2 this[uint i] { readonly get => this[(int)i]; set => this[(int)i] = value; }
    public int _m00 { readonly get => r0.x; set => r0.x = value; }
    public int _11 { readonly get => r0.x; set => r0.x = value; }
    public int _m01 { readonly get => r0.y; set => r0.y = value; }
    public int _12 { readonly get => r0.y; set => r0.y = value; }
    public int _m10 { readonly get => r1.x; set => r1.x = value; }
    public int _21 { readonly get => r1.x; set => r1.x = value; }
    public int _m11 { readonly get => r1.y; set => r1.y = value; }
    public int _22 { readonly get => r1.y; set => r1.y = value; }
    public int _m20 { readonly get => r2.x; set => r2.x = value; }
    public int _31 { readonly get => r2.x; set => r2.x = value; }
    public int _m21 { readonly get => r2.y; set => r2.y = value; }
    public int _32 { readonly get => r2.y; set => r2.y = value; }
    public int _m30 { readonly get => r3.x; set => r3.x = value; }
    public int _41 { readonly get => r3.x; set => r3.x = value; }
    public int _m31 { readonly get => r3.y; set => r3.y = value; }
    public int _42 { readonly get => r3.y; set => r3.y = value; }
    public static explicit operator int4x2(float4x2 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(float4x3 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(float4x4 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(half4x2 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(half4x3 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(half4x4 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(int4x3 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(int4x4 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(uint4x2 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(uint4x3 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(uint4x4 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(bool4x2 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(bool4x3 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static explicit operator int4x2(bool4x4 v) => new int4x2((int2)v.r0, (int2)v.r1, (int2)v.r2, (int2)v.r3);
    public static int4x2 operator +(int4x2 a, int4x2 b) => new int4x2(a.r0 + b.r0, a.r1 + b.r1, a.r2 + b.r2, a.r3 + b.r3);
    public static int4x2 operator +(int4x2 a, int b) => new int4x2(a.r0 + b, a.r1 + b, a.r2 + b, a.r3 + b);
    public static int4x2 operator +(int a, int4x2 b) => new int4x2(a + b.r0, a + b.r1, a + b.r2, a + b.r3);
    public static int4x2 operator -(int4x2 a, int4x2 b) => new int4x2(a.r0 - b.r0, a.r1 - b.r1, a.r2 - b.r2, a.r3 - b.r3);
    public static int4x2 operator -(int4x2 a, int b) => new int4x2(a.r0 - b, a.r1 - b, a.r2 - b, a.r3 - b);
    public static int4x2 operator -(int a, int4x2 b) => new int4x2(a - b.r0, a - b.r1, a - b.r2, a - b.r3);
    public static int4x2 operator *(int4x2 a, int4x2 b) => new int4x2(a.r0 * b.r0, a.r1 * b.r1, a.r2 * b.r2, a.r3 * b.r3);
    public static int4x2 operator *(int4x2 a, int b) => new int4x2(a.r0 * b, a.r1 * b, a.r2 * b, a.r3 * b);
    public static int4x2 operator *(int a, int4x2 b) => new int4x2(a * b.r0, a * b.r1, a * b.r2, a * b.r3);
    public static int4x2 operator /(int4x2 a, int4x2 b) => new int4x2(a.r0 / b.r0, a.r1 / b.r1, a.r2 / b.r2, a.r3 / b.r3);
    public static int4x2 operator /(int4x2 a, int b) => new int4x2(a.r0 / b, a.r1 / b, a.r2 / b, a.r3 / b);
    public static int4x2 operator /(int a, int4x2 b) => new int4x2(a / b.r0, a / b.r1, a / b.r2, a / b.r3);
    public static int4x2 operator %(int4x2 a, int4x2 b) => new int4x2(a.r0 % b.r0, a.r1 % b.r1, a.r2 % b.r2, a.r3 % b.r3);
    public static int4x2 operator %(int4x2 a, int b) => new int4x2(a.r0 % b, a.r1 % b, a.r2 % b, a.r3 % b);
    public static int4x2 operator %(int a, int4x2 b) => new int4x2(a % b.r0, a % b.r1, a % b.r2, a % b.r3);
    public static int4x2 operator -(int4x2 a) => new int4x2(-a.r0, -a.r1, -a.r2, -a.r3);
}
