// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591, CS0660, CS0661
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>Shader resources: opaque handles, as on the GPU. They exist so shader code type-checks; every member runs on the GPU only.</summary>
internal static class GpuOnly
{
    public static Exception Exception() => new NotSupportedException("Shader resources are only accessed on the GPU");
}

public readonly struct SamplerState { }
public readonly struct SamplerComparisonState { }

/// <summary>Sample counts of a multisampled texture: Texture2DMS&lt;float4, Samples4&gt; is SDSL's Texture2DMS&lt;float4, 4&gt;.</summary>
public readonly struct Samples1 { }
public readonly struct Samples2 { }
public readonly struct Samples4 { }
public readonly struct Samples8 { }
public readonly struct Samples16 { }
public readonly struct Samples32 { }

public readonly struct Texture1D<T> where T : struct
{
    public T this[int location] => throw GpuOnly.Exception();
    public T this[uint location] => throw GpuOnly.Exception();
    public T Load(int2 location) => throw GpuOnly.Exception();
    public T Load(int2 location, int offset) => throw GpuOnly.Exception();
    public T Load(uint2 location) => throw GpuOnly.Exception();
    public T Load(uint2 location, int offset) => throw GpuOnly.Exception();
    public T Sample(SamplerState sampler, float location) => throw GpuOnly.Exception();
    public T Sample(SamplerState sampler, float location, int offset) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float location, float lod) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float location, float lod, int offset) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float location, float bias) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float location, float bias, int offset) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float location, float ddx, float ddy) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float location, float ddx, float ddy, int offset) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float location, float compare) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float location, float compare, int offset) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float location, float compare, int offset) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float levels) => throw GpuOnly.Exception();
}

/// <summary>Texture1D of float4, as SDSL writes it without an element type.</summary>
public readonly struct Texture1D
{
    public float4 this[int location] => throw GpuOnly.Exception();
    public float4 this[uint location] => throw GpuOnly.Exception();
    public float4 Load(int2 location) => throw GpuOnly.Exception();
    public float4 Load(int2 location, int offset) => throw GpuOnly.Exception();
    public float4 Load(uint2 location) => throw GpuOnly.Exception();
    public float4 Load(uint2 location, int offset) => throw GpuOnly.Exception();
    public float4 Sample(SamplerState sampler, float location) => throw GpuOnly.Exception();
    public float4 Sample(SamplerState sampler, float location, int offset) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float location, float lod) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float location, float lod, int offset) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float location, float bias) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float location, float bias, int offset) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float location, float ddx, float ddy) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float location, float ddx, float ddy, int offset) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float location, float compare) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float location, float compare, int offset) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float location, float compare, int offset) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float levels) => throw GpuOnly.Exception();
}

public readonly struct Texture1DArray<T> where T : struct
{
    public T this[int2 location] => throw GpuOnly.Exception();
    public T this[uint2 location] => throw GpuOnly.Exception();
    public T Load(int3 location) => throw GpuOnly.Exception();
    public T Load(int3 location, int offset) => throw GpuOnly.Exception();
    public T Load(uint3 location) => throw GpuOnly.Exception();
    public T Load(uint3 location, int offset) => throw GpuOnly.Exception();
    public T Sample(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public T Sample(SamplerState sampler, float2 location, int offset) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float2 location, float lod) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float2 location, float lod, int offset) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float2 location, float bias) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float2 location, float bias, int offset) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float2 location, float ddx, float ddy) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float2 location, float ddx, float ddy, int offset) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float2 location, float compare, int offset) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float2 location, float compare, int offset) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint elements, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float elements, out float levels) => throw GpuOnly.Exception();
}

/// <summary>Texture1DArray of float4, as SDSL writes it without an element type.</summary>
public readonly struct Texture1DArray
{
    public float4 this[int2 location] => throw GpuOnly.Exception();
    public float4 this[uint2 location] => throw GpuOnly.Exception();
    public float4 Load(int3 location) => throw GpuOnly.Exception();
    public float4 Load(int3 location, int offset) => throw GpuOnly.Exception();
    public float4 Load(uint3 location) => throw GpuOnly.Exception();
    public float4 Load(uint3 location, int offset) => throw GpuOnly.Exception();
    public float4 Sample(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 Sample(SamplerState sampler, float2 location, int offset) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float2 location, float lod) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float2 location, float lod, int offset) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float2 location, float bias) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float2 location, float bias, int offset) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float2 location, float ddx, float ddy) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float2 location, float ddx, float ddy, int offset) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float2 location, float compare, int offset) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float2 location, float compare, int offset) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint elements, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float elements, out float levels) => throw GpuOnly.Exception();
}

public readonly struct Texture2D<T> where T : struct
{
    public T this[int2 location] => throw GpuOnly.Exception();
    public T this[uint2 location] => throw GpuOnly.Exception();
    public T Load(int3 location) => throw GpuOnly.Exception();
    public T Load(int3 location, int2 offset) => throw GpuOnly.Exception();
    public T Load(uint3 location) => throw GpuOnly.Exception();
    public T Load(uint3 location, int2 offset) => throw GpuOnly.Exception();
    public T Sample(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public T Sample(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float2 location, float lod) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float2 location, float lod, int2 offset) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float2 location, float bias) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float2 location, float bias, int2 offset) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float2 location, float2 ddx, float2 ddy) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float2 location, float2 ddx, float2 ddy, int2 offset) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float2 location, float compare, int2 offset) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float2 location, float compare, int2 offset) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float2 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float2 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float2 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float2 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherCmp(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float4 GatherCmpRed(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint height, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float height, out float levels) => throw GpuOnly.Exception();
}

/// <summary>Texture2D of float4, as SDSL writes it without an element type.</summary>
public readonly struct Texture2D
{
    public float4 this[int2 location] => throw GpuOnly.Exception();
    public float4 this[uint2 location] => throw GpuOnly.Exception();
    public float4 Load(int3 location) => throw GpuOnly.Exception();
    public float4 Load(int3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 Load(uint3 location) => throw GpuOnly.Exception();
    public float4 Load(uint3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 Sample(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 Sample(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float2 location, float lod) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float2 location, float lod, int2 offset) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float2 location, float bias) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float2 location, float bias, int2 offset) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float2 location, float2 ddx, float2 ddy) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float2 location, float2 ddx, float2 ddy, int2 offset) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float2 location, float compare, int2 offset) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float2 location, float compare, int2 offset) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float2 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float2 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float2 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float2 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float2 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherCmp(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float4 GatherCmpRed(SamplerComparisonState sampler, float2 location, float compare) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint height, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float height, out float levels) => throw GpuOnly.Exception();
}

public readonly struct Texture2DArray<T> where T : struct
{
    public T this[int3 location] => throw GpuOnly.Exception();
    public T this[uint3 location] => throw GpuOnly.Exception();
    public T Load(int4 location) => throw GpuOnly.Exception();
    public T Load(int4 location, int2 offset) => throw GpuOnly.Exception();
    public T Load(uint4 location) => throw GpuOnly.Exception();
    public T Load(uint4 location, int2 offset) => throw GpuOnly.Exception();
    public T Sample(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public T Sample(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float3 location, float lod) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float3 location, float lod, int2 offset) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float3 location, float bias) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float3 location, float bias, int2 offset) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float3 location, float2 ddx, float2 ddy) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float3 location, float2 ddx, float2 ddy, int2 offset) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float3 location, float compare, int2 offset) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float3 location, float compare, int2 offset) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float3 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float3 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float3 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float3 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherCmp(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float4 GatherCmpRed(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint height, out uint elements, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float height, out float elements, out float levels) => throw GpuOnly.Exception();
}

/// <summary>Texture2DArray of float4, as SDSL writes it without an element type.</summary>
public readonly struct Texture2DArray
{
    public float4 this[int3 location] => throw GpuOnly.Exception();
    public float4 this[uint3 location] => throw GpuOnly.Exception();
    public float4 Load(int4 location) => throw GpuOnly.Exception();
    public float4 Load(int4 location, int2 offset) => throw GpuOnly.Exception();
    public float4 Load(uint4 location) => throw GpuOnly.Exception();
    public float4 Load(uint4 location, int2 offset) => throw GpuOnly.Exception();
    public float4 Sample(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 Sample(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float3 location, float lod) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float3 location, float lod, int2 offset) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float3 location, float bias) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float3 location, float bias, int2 offset) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float3 location, float2 ddx, float2 ddy) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float3 location, float2 ddx, float2 ddy, int2 offset) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float3 location, float compare, int2 offset) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float3 location, float compare, int2 offset) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float3 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float3 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float3 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float3 location, int2 offset) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float3 location, int2 offset1, int2 offset2, int2 offset3, int2 offset4) => throw GpuOnly.Exception();
    public float4 GatherCmp(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float4 GatherCmpRed(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float2 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint height, out uint elements, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float height, out float elements, out float levels) => throw GpuOnly.Exception();
}

public readonly struct Texture3D<T> where T : struct
{
    public T this[int3 location] => throw GpuOnly.Exception();
    public T this[uint3 location] => throw GpuOnly.Exception();
    public T Load(int4 location) => throw GpuOnly.Exception();
    public T Load(int4 location, int3 offset) => throw GpuOnly.Exception();
    public T Load(uint4 location) => throw GpuOnly.Exception();
    public T Load(uint4 location, int3 offset) => throw GpuOnly.Exception();
    public T Sample(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public T Sample(SamplerState sampler, float3 location, int3 offset) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float3 location, float lod) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float3 location, float lod, int3 offset) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float3 location, float bias) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float3 location, float bias, int3 offset) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float3 location, float3 ddx, float3 ddy) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float3 location, float3 ddx, float3 ddy, int3 offset) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float3 location, float compare, int3 offset) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float3 location, float compare, int3 offset) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint depth) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint height, out uint depth, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float depth) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float height, out float depth, out float levels) => throw GpuOnly.Exception();
}

/// <summary>Texture3D of float4, as SDSL writes it without an element type.</summary>
public readonly struct Texture3D
{
    public float4 this[int3 location] => throw GpuOnly.Exception();
    public float4 this[uint3 location] => throw GpuOnly.Exception();
    public float4 Load(int4 location) => throw GpuOnly.Exception();
    public float4 Load(int4 location, int3 offset) => throw GpuOnly.Exception();
    public float4 Load(uint4 location) => throw GpuOnly.Exception();
    public float4 Load(uint4 location, int3 offset) => throw GpuOnly.Exception();
    public float4 Sample(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 Sample(SamplerState sampler, float3 location, int3 offset) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float3 location, float lod) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float3 location, float lod, int3 offset) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float3 location, float bias) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float3 location, float bias, int3 offset) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float3 location, float3 ddx, float3 ddy) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float3 location, float3 ddx, float3 ddy, int3 offset) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float3 location, float compare, int3 offset) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float3 location, float compare, int3 offset) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint depth) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint height, out uint depth, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float depth) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float height, out float depth, out float levels) => throw GpuOnly.Exception();
}

public readonly struct TextureCube<T> where T : struct
{
    public T Sample(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float3 location, float lod) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float3 location, float bias) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float3 location, float3 ddx, float3 ddy) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherCmp(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float4 GatherCmpRed(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint height, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float height, out float levels) => throw GpuOnly.Exception();
}

/// <summary>TextureCube of float4, as SDSL writes it without an element type.</summary>
public readonly struct TextureCube
{
    public float4 Sample(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float3 location, float lod) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float3 location, float bias) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float3 location, float3 ddx, float3 ddy) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public float4 GatherCmp(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float4 GatherCmpRed(SamplerComparisonState sampler, float3 location, float compare) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint height, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float height, out float levels) => throw GpuOnly.Exception();
}

public readonly struct TextureCubeArray<T> where T : struct
{
    public T Sample(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public T SampleLevel(SamplerState sampler, float4 location, float lod) => throw GpuOnly.Exception();
    public T SampleBias(SamplerState sampler, float4 location, float bias) => throw GpuOnly.Exception();
    public T SampleGrad(SamplerState sampler, float4 location, float3 ddx, float3 ddy) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float4 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float4 location, float compare) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 GatherCmp(SamplerComparisonState sampler, float4 location, float compare) => throw GpuOnly.Exception();
    public float4 GatherCmpRed(SamplerComparisonState sampler, float4 location, float compare) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint height, out uint elements, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float height, out float elements, out float levels) => throw GpuOnly.Exception();
}

/// <summary>TextureCubeArray of float4, as SDSL writes it without an element type.</summary>
public readonly struct TextureCubeArray
{
    public float4 Sample(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 SampleLevel(SamplerState sampler, float4 location, float lod) => throw GpuOnly.Exception();
    public float4 SampleBias(SamplerState sampler, float4 location, float bias) => throw GpuOnly.Exception();
    public float4 SampleGrad(SamplerState sampler, float4 location, float3 ddx, float3 ddy) => throw GpuOnly.Exception();
    public float SampleCmp(SamplerComparisonState sampler, float4 location, float compare) => throw GpuOnly.Exception();
    public float SampleCmpLevelZero(SamplerComparisonState sampler, float4 location, float compare) => throw GpuOnly.Exception();
    public float4 Gather(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 GatherRed(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 GatherGreen(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 GatherBlue(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 GatherAlpha(SamplerState sampler, float4 location) => throw GpuOnly.Exception();
    public float4 GatherCmp(SamplerComparisonState sampler, float4 location, float compare) => throw GpuOnly.Exception();
    public float4 GatherCmpRed(SamplerComparisonState sampler, float4 location, float compare) => throw GpuOnly.Exception();
    public float CalculateLevelOfDetail(SamplerState sampler, float3 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out uint width, out uint height, out uint elements, out uint levels) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float elements) => throw GpuOnly.Exception();
    public void GetDimensions(uint mipLevel, out float width, out float height, out float elements, out float levels) => throw GpuOnly.Exception();
}

public readonly struct RWTexture1D<T> where T : struct
{
    public T this[int location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(int location) => throw GpuOnly.Exception();
    public T this[uint location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(uint location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width) => throw GpuOnly.Exception();
    public void GetDimensions(out float width) => throw GpuOnly.Exception();
}

public readonly struct RWTexture1D
{
    public float4 this[int location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(int location) => throw GpuOnly.Exception();
    public float4 this[uint location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(uint location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width) => throw GpuOnly.Exception();
    public void GetDimensions(out float width) => throw GpuOnly.Exception();
}

public readonly struct RWTexture1DArray<T> where T : struct
{
    public T this[int2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(int2 location) => throw GpuOnly.Exception();
    public T this[uint2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(uint2 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint elements) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float elements) => throw GpuOnly.Exception();
}

public readonly struct RWTexture1DArray
{
    public float4 this[int2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(int2 location) => throw GpuOnly.Exception();
    public float4 this[uint2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(uint2 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint elements) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float elements) => throw GpuOnly.Exception();
}

public readonly struct RWTexture2D<T> where T : struct
{
    public T this[int2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(int2 location) => throw GpuOnly.Exception();
    public T this[uint2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(uint2 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height) => throw GpuOnly.Exception();
}

public readonly struct RWTexture2D
{
    public float4 this[int2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(int2 location) => throw GpuOnly.Exception();
    public float4 this[uint2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(uint2 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height) => throw GpuOnly.Exception();
}

public readonly struct RWTexture2DArray<T> where T : struct
{
    public T this[int3 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(int3 location) => throw GpuOnly.Exception();
    public T this[uint3 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(uint3 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint elements) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float elements) => throw GpuOnly.Exception();
}

public readonly struct RWTexture2DArray
{
    public float4 this[int3 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(int3 location) => throw GpuOnly.Exception();
    public float4 this[uint3 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(uint3 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint elements) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float elements) => throw GpuOnly.Exception();
}

public readonly struct RWTexture3D<T> where T : struct
{
    public T this[int3 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(int3 location) => throw GpuOnly.Exception();
    public T this[uint3 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(uint3 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint depth) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float depth) => throw GpuOnly.Exception();
}

public readonly struct RWTexture3D
{
    public float4 this[int3 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(int3 location) => throw GpuOnly.Exception();
    public float4 this[uint3 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(uint3 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint depth) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float depth) => throw GpuOnly.Exception();
}

public readonly struct RasterizerOrderedTexture2D<T> where T : struct
{
    public T this[int2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(int2 location) => throw GpuOnly.Exception();
    public T this[uint2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(uint2 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height) => throw GpuOnly.Exception();
}

public readonly struct RasterizerOrderedTexture2D
{
    public float4 this[int2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(int2 location) => throw GpuOnly.Exception();
    public float4 this[uint2 location] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(uint2 location) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height) => throw GpuOnly.Exception();
}

public readonly struct Texture2DMS<T> where T : struct
{
    public T Load(int2 location, int sample) => throw GpuOnly.Exception();
    public T Load(int2 location, int sample, int2 offset) => throw GpuOnly.Exception();
    public T Load(uint2 location, int sample) => throw GpuOnly.Exception();
    public T Load(uint2 location, int sample, int2 offset) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint samples) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float samples) => throw GpuOnly.Exception();
    public float2 GetSamplePosition(int sample) => throw GpuOnly.Exception();
}

public readonly struct Texture2DMS<T, TSamples> where T : struct where TSamples : struct
{
    public T Load(int2 location, int sample) => throw GpuOnly.Exception();
    public T Load(int2 location, int sample, int2 offset) => throw GpuOnly.Exception();
    public T Load(uint2 location, int sample) => throw GpuOnly.Exception();
    public T Load(uint2 location, int sample, int2 offset) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint samples) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float samples) => throw GpuOnly.Exception();
    public float2 GetSamplePosition(int sample) => throw GpuOnly.Exception();
}

public readonly struct Texture2DMS
{
    public float4 Load(int2 location, int sample) => throw GpuOnly.Exception();
    public float4 Load(uint2 location, int sample) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint samples) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float samples) => throw GpuOnly.Exception();
}

public readonly struct Texture2DMSArray<T> where T : struct
{
    public T Load(int3 location, int sample) => throw GpuOnly.Exception();
    public T Load(int3 location, int sample, int2 offset) => throw GpuOnly.Exception();
    public T Load(uint3 location, int sample) => throw GpuOnly.Exception();
    public T Load(uint3 location, int sample, int2 offset) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint elements, out uint samples) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float elements, out float samples) => throw GpuOnly.Exception();
    public float2 GetSamplePosition(int sample) => throw GpuOnly.Exception();
}

public readonly struct Texture2DMSArray<T, TSamples> where T : struct where TSamples : struct
{
    public T Load(int3 location, int sample) => throw GpuOnly.Exception();
    public T Load(int3 location, int sample, int2 offset) => throw GpuOnly.Exception();
    public T Load(uint3 location, int sample) => throw GpuOnly.Exception();
    public T Load(uint3 location, int sample, int2 offset) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint elements, out uint samples) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float elements, out float samples) => throw GpuOnly.Exception();
    public float2 GetSamplePosition(int sample) => throw GpuOnly.Exception();
}

public readonly struct Texture2DMSArray
{
    public float4 Load(int3 location, int sample) => throw GpuOnly.Exception();
    public float4 Load(uint3 location, int sample) => throw GpuOnly.Exception();
    public void GetDimensions(out uint width, out uint height, out uint elements, out uint samples) => throw GpuOnly.Exception();
    public void GetDimensions(out float width, out float height, out float elements, out float samples) => throw GpuOnly.Exception();
}

public readonly struct Buffer<T> where T : struct
{
    public T this[int index] => throw GpuOnly.Exception();
    public T Load(int index) => throw GpuOnly.Exception();
    public T this[uint index] => throw GpuOnly.Exception();
    public T Load(uint index) => throw GpuOnly.Exception();
    public void GetDimensions(out uint count) => throw GpuOnly.Exception();
}

public readonly struct Buffer
{
    public float4 this[int index] => throw GpuOnly.Exception();
    public float4 Load(int index) => throw GpuOnly.Exception();
    public float4 this[uint index] => throw GpuOnly.Exception();
    public float4 Load(uint index) => throw GpuOnly.Exception();
    public void GetDimensions(out uint count) => throw GpuOnly.Exception();
}

public readonly struct RWBuffer<T> where T : struct
{
    public T this[int index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(int index) => throw GpuOnly.Exception();
    public T this[uint index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(uint index) => throw GpuOnly.Exception();
    public void GetDimensions(out uint count) => throw GpuOnly.Exception();
}

public readonly struct RWBuffer
{
    public float4 this[int index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(int index) => throw GpuOnly.Exception();
    public float4 this[uint index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(uint index) => throw GpuOnly.Exception();
    public void GetDimensions(out uint count) => throw GpuOnly.Exception();
}

public readonly struct StructuredBuffer<T> where T : struct
{
    public T this[int index] => throw GpuOnly.Exception();
    public T Load(int index) => throw GpuOnly.Exception();
    public T this[uint index] => throw GpuOnly.Exception();
    public T Load(uint index) => throw GpuOnly.Exception();
    public void GetDimensions(out uint count, out uint stride) => throw GpuOnly.Exception();
}

public readonly struct RWStructuredBuffer<T> where T : struct
{
    public T this[int index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(int index) => throw GpuOnly.Exception();
    public T this[uint index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(uint index) => throw GpuOnly.Exception();
    public void GetDimensions(out uint count, out uint stride) => throw GpuOnly.Exception();
    public uint IncrementCounter() => throw GpuOnly.Exception();
    public uint DecrementCounter() => throw GpuOnly.Exception();
}

public readonly struct RasterizerOrderedBuffer<T> where T : struct
{
    public T this[int index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(int index) => throw GpuOnly.Exception();
    public T this[uint index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(uint index) => throw GpuOnly.Exception();
    public void GetDimensions(out uint count) => throw GpuOnly.Exception();
}

public readonly struct RasterizerOrderedBuffer
{
    public float4 this[int index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(int index) => throw GpuOnly.Exception();
    public float4 this[uint index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public float4 Load(uint index) => throw GpuOnly.Exception();
    public void GetDimensions(out uint count) => throw GpuOnly.Exception();
}

public readonly struct RasterizerOrderedStructuredBuffer<T> where T : struct
{
    public T this[int index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(int index) => throw GpuOnly.Exception();
    public T this[uint index] { get => throw GpuOnly.Exception(); set => throw GpuOnly.Exception(); }
    public T Load(uint index) => throw GpuOnly.Exception();
    public void GetDimensions(out uint count, out uint stride) => throw GpuOnly.Exception();
    public uint IncrementCounter() => throw GpuOnly.Exception();
    public uint DecrementCounter() => throw GpuOnly.Exception();
}

public readonly struct AppendStructuredBuffer<T> where T : struct
{
    public void Append(T value) => throw GpuOnly.Exception();
    public void GetDimensions(out uint count, out uint stride) => throw GpuOnly.Exception();
}

public readonly struct ConsumeStructuredBuffer<T> where T : struct
{
    public T Consume() => throw GpuOnly.Exception();
    public void GetDimensions(out uint count, out uint stride) => throw GpuOnly.Exception();
}

public readonly struct ByteAddressBuffer
{
    public uint Load(int address) => throw GpuOnly.Exception();
    public uint2 Load2(int address) => throw GpuOnly.Exception();
    public uint3 Load3(int address) => throw GpuOnly.Exception();
    public uint4 Load4(int address) => throw GpuOnly.Exception();
    public uint Load(uint address) => throw GpuOnly.Exception();
    public uint2 Load2(uint address) => throw GpuOnly.Exception();
    public uint3 Load3(uint address) => throw GpuOnly.Exception();
    public uint4 Load4(uint address) => throw GpuOnly.Exception();
    public void GetDimensions(out uint bytes) => throw GpuOnly.Exception();
}

public readonly struct RWByteAddressBuffer
{
    public uint Load(int address) => throw GpuOnly.Exception();
    public uint2 Load2(int address) => throw GpuOnly.Exception();
    public uint3 Load3(int address) => throw GpuOnly.Exception();
    public uint4 Load4(int address) => throw GpuOnly.Exception();
    public void Store(int address, uint value) => throw GpuOnly.Exception();
    public void Store2(int address, uint2 value) => throw GpuOnly.Exception();
    public void Store3(int address, uint3 value) => throw GpuOnly.Exception();
    public void Store4(int address, uint4 value) => throw GpuOnly.Exception();
    public void InterlockedAdd(int address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedAdd(int address, uint value) => throw GpuOnly.Exception();
    public void InterlockedAnd(int address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedAnd(int address, uint value) => throw GpuOnly.Exception();
    public void InterlockedOr(int address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedOr(int address, uint value) => throw GpuOnly.Exception();
    public void InterlockedXor(int address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedXor(int address, uint value) => throw GpuOnly.Exception();
    public void InterlockedMin(int address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedMin(int address, uint value) => throw GpuOnly.Exception();
    public void InterlockedMax(int address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedMax(int address, uint value) => throw GpuOnly.Exception();
    public void InterlockedExchange(int address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedCompareExchange(int address, uint compare, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedCompareStore(int address, uint compare, uint value) => throw GpuOnly.Exception();
    public uint Load(uint address) => throw GpuOnly.Exception();
    public uint2 Load2(uint address) => throw GpuOnly.Exception();
    public uint3 Load3(uint address) => throw GpuOnly.Exception();
    public uint4 Load4(uint address) => throw GpuOnly.Exception();
    public void Store(uint address, uint value) => throw GpuOnly.Exception();
    public void Store2(uint address, uint2 value) => throw GpuOnly.Exception();
    public void Store3(uint address, uint3 value) => throw GpuOnly.Exception();
    public void Store4(uint address, uint4 value) => throw GpuOnly.Exception();
    public void InterlockedAdd(uint address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedAdd(uint address, uint value) => throw GpuOnly.Exception();
    public void InterlockedAnd(uint address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedAnd(uint address, uint value) => throw GpuOnly.Exception();
    public void InterlockedOr(uint address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedOr(uint address, uint value) => throw GpuOnly.Exception();
    public void InterlockedXor(uint address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedXor(uint address, uint value) => throw GpuOnly.Exception();
    public void InterlockedMin(uint address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedMin(uint address, uint value) => throw GpuOnly.Exception();
    public void InterlockedMax(uint address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedMax(uint address, uint value) => throw GpuOnly.Exception();
    public void InterlockedExchange(uint address, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedCompareExchange(uint address, uint compare, uint value, out uint original) => throw GpuOnly.Exception();
    public void InterlockedCompareStore(uint address, uint compare, uint value) => throw GpuOnly.Exception();
    public void GetDimensions(out uint bytes) => throw GpuOnly.Exception();
}

